// Vitest fixture for scripts/modules/pocock/provenance-flag.js + audit-provenance-emission.mjs
// SD-LEO-PROTOCOL-POCOCK-PATTERNS-ORCH-001-F FR-9 (≥9 enumerated cases)

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { promises as fsp } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  validProvenanceSource,
  formatAgent,
  formatHuman,
  injectPrefixIdempotent,
  readProvenanceFlag,
  _resetCacheForTests,
  MAX_FIELD_LENGTH,
  AGENT_REGEX,
  HUMAN_REGEX,
  AI_PROVENANCE_PREFIX,
  KNOWN_WRITERS,
  CONFIG_KEY
} from '../../modules/pocock/provenance-flag.js';
import { runAudit } from '../audit-provenance-emission.mjs';

function makeFakeSupabase(value) {
  return {
    from(_tbl) {
      return {
        select(_cols) {
          return {
            eq(_col, _val) {
              return {
                maybeSingle: async () => ({ data: value === null ? null : { value }, error: null })
              };
            }
          };
        }
      };
    }
  };
}

describe('provenance-flag helper', () => {
  beforeEach(() => { _resetCacheForTests(); });
  afterEach(() => { _resetCacheForTests(); });

  it('Case 1 — validProvenanceSource accepts agent:LEAD:557156f7', () => {
    expect(validProvenanceSource('agent:LEAD:557156f7')).toBe(true);
  });

  it('Case 2 — validProvenanceSource accepts human:rick@codestreetlabs.com', () => {
    expect(validProvenanceSource('human:rick@codestreetlabs.com')).toBe(true);
  });

  it('Case 3 — validProvenanceSource rejects empty seat (agent::round-1)', () => {
    expect(validProvenanceSource('agent::round-1')).toBe(false);
  });

  it('Case 4 — validProvenanceSource rejects bare EXEC (no agent prefix)', () => {
    expect(validProvenanceSource('EXEC')).toBe(false);
  });

  it('Case 5 — validProvenanceSource accepts NULL (legacy compat)', () => {
    expect(validProvenanceSource(null)).toBe(true);
    expect(validProvenanceSource(undefined)).toBe(true);
  });

  it('Case 6 — validProvenanceSource rejects length > 256 (MAX_FIELD_LENGTH)', () => {
    const tooLong = 'agent:LEAD:' + 'a'.repeat(250);
    expect(tooLong.length).toBeGreaterThan(256);
    expect(validProvenanceSource(tooLong)).toBe(false);
  });

  it('Case 7 — formatAgent produces matching regex value', () => {
    expect(formatAgent('LEAD', '557156f7')).toBe('agent:LEAD:557156f7');
    expect(AGENT_REGEX.test(formatAgent('TESTING', 'round-3'))).toBe(true);
  });

  it('Case 7b — formatHuman produces matching regex value', () => {
    expect(formatHuman('rick@codestreetlabs.com')).toBe('human:rick@codestreetlabs.com');
    expect(HUMAN_REGEX.test(formatHuman('rickfelix'))).toBe(true);
  });

  it('Case 8 — injectPrefixIdempotent double-call is byte-identical', () => {
    const original = 'Some retrospective body.';
    const once = injectPrefixIdempotent(original);
    const twice = injectPrefixIdempotent(once);
    expect(twice).toBe(once);
    expect(once.startsWith(AI_PROVENANCE_PREFIX)).toBe(true);
  });

  it('Case 9 — readProvenanceFlag env-first precedence: env=prefix wins over DB emit=false', async () => {
    process.env.POCOCK_PROVENANCE_GLOSSARY = 'prefix';
    try {
      const fakeDb = makeFakeSupabase({ glossary: { emit: false, prefix: false } });
      const flag = await readProvenanceFlag('glossary', { supabase: fakeDb });
      expect(flag.emit_source).toBe(true);
      expect(flag.prefix_enabled).toBe(true);
    } finally {
      delete process.env.POCOCK_PROVENANCE_GLOSSARY;
    }
  });

  it('Case 9b — readProvenanceFlag DB fallback when env absent', async () => {
    delete process.env.POCOCK_PROVENANCE_GLOSSARY;
    const fakeDb = makeFakeSupabase({ glossary: { emit: true, prefix: false } });
    const flag = await readProvenanceFlag('glossary', { supabase: fakeDb });
    expect(flag.emit_source).toBe(true);
    expect(flag.prefix_enabled).toBe(false);
  });

  it('Case 9c — readProvenanceFlag default OFF when no env + no DB row', async () => {
    delete process.env.POCOCK_PROVENANCE_GLOSSARY;
    const fakeDb = makeFakeSupabase(null);
    const flag = await readProvenanceFlag('glossary', { supabase: fakeDb });
    expect(flag.emit_source).toBe(false);
    expect(flag.prefix_enabled).toBe(false);
  });

  it('Case 9d — readProvenanceFlag rejects unknown writer (returns default OFF)', async () => {
    const fakeDb = makeFakeSupabase({ unknownWriter: { emit: true, prefix: true } });
    const flag = await readProvenanceFlag('unknownWriter', { supabase: fakeDb });
    expect(flag.emit_source).toBe(false);
  });

  it('exports expected constants', () => {
    expect(MAX_FIELD_LENGTH).toBe(256);
    expect(AI_PROVENANCE_PREFIX).toBe('> *This was generated by AI during triage.*');
    expect(CONFIG_KEY).toBe('pocock_provenance_writers');
    expect(KNOWN_WRITERS).toContain('glossary');
    expect(KNOWN_WRITERS).toContain('feedback');
  });

  it('readProvenanceFlag handles stringified JSON value from app_config TEXT column', async () => {
    delete process.env.POCOCK_PROVENANCE_FEEDBACK;
    const fakeDb = makeFakeSupabase(JSON.stringify({ feedback: { emit: true, prefix: true } }));
    const flag = await readProvenanceFlag('feedback', { supabase: fakeDb });
    expect(flag.emit_source).toBe(true);
    expect(flag.prefix_enabled).toBe(true);
  });
});

describe('audit-provenance-emission walker', () => {
  let root;
  beforeEach(async () => { root = await fsp.mkdtemp(path.join(os.tmpdir(), 'prov-audit-')); });
  afterEach(async () => { await fsp.rm(root, { recursive: true, force: true }); });

  it('walker on empty tree returns zero-row report without crashing', async () => {
    const { rows, summary } = await runAudit({ root, write: false });
    expect(rows.length).toBe(0);
    expect(summary.offender_count).toBe(0);
  });

  it('walker counts in-scope vs excluded call sites correctly', async () => {
    const dir = path.join(root, 'scripts', 'pocock');
    await fsp.mkdir(dir, { recursive: true });
    await fsp.writeFile(path.join(dir, 'a.mjs'), `
import { x } from 'y';
await sb.from('pocock_glossary_terms').insert({ term: 'x' });
await sb.from('sub_agent_execution_results').insert({ source: 'manual' });
await sb.from('feedback').insert({ description: 'hi', provenance_source: 'agent:LEAD:abc' });
`, 'utf8');
    const { rows } = await runAudit({ root, write: false });
    const row = rows.find(r => r.path === 'scripts/pocock/a.mjs');
    expect(row).toBeDefined();
    expect(row.total_call_sites).toBe(3);
    expect(row.excluded_call_sites).toBe(1);
    expect(row.in_scope_call_sites).toBe(2);
    expect(row.emit_count).toBe(1);
    expect(row.coverage_pct).toBe(50);
  });
});
