/**
 * Tests for documentation-generator.js
 * SD-REPLIT-PIPELINE-S20S26-REDESIGN-ORCH-001-C-C
 */
import { describe, it, expect } from 'vitest';
import { generateReadme, detectFramework } from '../../../../lib/eva/bridge/documentation-generator.js';

describe('documentation-generator', () => {
  describe('detectFramework', () => {
    it('detects Next.js', () => {
      expect(detectFramework({ dependencies: { next: '14.0.0', react: '18.0.0' } })).toBe('Next.js');
    });

    it('detects React with Vite', () => {
      expect(detectFramework({ devDependencies: { vite: '5.0.0', '@vitejs/plugin-react': '4.0.0' } })).toBe('React (Vite)');
    });

    it('returns fallback for empty deps', () => {
      expect(detectFramework({})).toBe('JavaScript');
      expect(detectFramework(null)).toBe('Unknown');
    });

    it('falls back to React if only react present', () => {
      expect(detectFramework({ dependencies: { react: '18.0.0' } })).toBe('React');
    });
  });

  describe('generateReadme', () => {
    const fullAnalysis = {
      files: ['src/index.tsx', 'src/App.tsx', 'package.json', 'README.md', 'tsconfig.json', '.env.example'],
      dependencies: {
        name: 'test-venture',
        version: '1.0.0',
        dependencies: { react: '18.0.0', '@supabase/supabase-js': '2.0.0' },
        devDependencies: { vite: '5.0.0', '@vitejs/plugin-react': '4.0.0', typescript: '5.0.0' },
      },
      structure: {
        totalFiles: 6,
        topLevelDirs: ['src'],
        hasTests: false,
      },
    };

    it('generates README with project name', () => {
      const readme = generateReadme(fullAnalysis);
      expect(readme).toContain('# test-venture');
    });

    it('detects tech stack correctly', () => {
      const readme = generateReadme(fullAnalysis);
      expect(readme).toContain('React (Vite)');
      expect(readme).toContain('TypeScript');
      expect(readme).toContain('Supabase');
    });

    it('includes directory structure', () => {
      const readme = generateReadme(fullAnalysis);
      expect(readme).toContain('src/');
    });

    it('includes getting started section', () => {
      const readme = generateReadme(fullAnalysis);
      expect(readme).toContain('npm install');
      expect(readme).toContain('npm run dev');
    });

    it('includes environment variables', () => {
      const readme = generateReadme(fullAnalysis);
      expect(readme).toContain('VITE_SUPABASE_URL');
      expect(readme).toContain('VITE_SUPABASE_ANON_KEY');
    });

    it('handles empty analysis gracefully', () => {
      const readme = generateReadme({});
      expect(readme).toContain('# Project');
      expect(readme).not.toContain('undefined');
    });

    it('handles null analysis', () => {
      const readme = generateReadme(null);
      expect(readme).toContain('# Project');
    });

    it('uses custom project name', () => {
      const readme = generateReadme(fullAnalysis, { projectName: 'My App' });
      expect(readme).toContain('# My App');
    });

    it('includes auto-generated footer', () => {
      const readme = generateReadme(fullAnalysis);
      expect(readme).toContain('Auto-generated by EHG');
    });
  });
});
