#!/usr/bin/env node

/**
 * Modular Venture Scaffold CLI
 * Generates working Playwright config, smoke tests, and CI workflow for new venture repos.
 *
 * Usage:
 *   node templates/venture-scaffold/scaffold.js <venture-name> [--modules testing,ci-cd]
 *   node templates/venture-scaffold/scaffold.js elysian --modules testing
 *   node templates/venture-scaffold/scaffold.js adsonix --modules testing,ci-cd
 *
 * SD-LEO-TESTING-STRATEGY-REDESIGN-ORCH-001-E
 */

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, resolve } from 'path';

// Module registry — extensible for future modules
const MODULE_REGISTRY = {
  testing: {
    name: 'Testing (Playwright)',
    version: '1.0.0',
    description: 'Playwright config, smoke tests, and test fixtures',
    generate: generateTestingModule
  },
  'ci-cd': {
    name: 'CI/CD (GitHub Actions)',
    version: '1.0.0',
    description: 'GitHub Actions workflow for test execution',
    generate: generateCICDModule
  }
};

function generateTestingModule(ventureName, outputDir, options) {
  const baseUrl = options.baseUrl || `http://localhost:${options.port || 8080}`;
  const files = [];

  // playwright.config.js
  files.push({
    path: join(outputDir, 'playwright.config.js'),
    content: `// @ts-check
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests/e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [['html'], ['json', { outputFile: 'test-results/results.json' }], ['list']],
  use: {
    baseURL: process.env.BASE_URL || '${baseUrl}',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    ignoreHTTPSErrors: true,
  },
  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
  ],
});
`
  });

  // tests/e2e directory
  mkdirSync(join(outputDir, 'tests', 'e2e'), { recursive: true });

  // Smoke test
  files.push({
    path: join(outputDir, 'tests', 'e2e', 'smoke.spec.ts'),
    content: `/**
 * Smoke tests for ${ventureName}
 * Verifies the app loads without errors.
 * Generated by venture-scaffold v1.0.0
 */
import { test, expect } from '@playwright/test';

test.describe('${ventureName} Smoke Tests', () => {
  test.beforeEach(async ({ page }) => {
    try {
      const response = await page.goto('/', { timeout: 10000 });
      if (!response || response.status() >= 500) {
        test.skip(true, '${ventureName} app not available');
      }
    } catch {
      test.skip(true, '${ventureName} app not reachable');
    }
  });

  test('home page loads without errors', async ({ page }) => {
    await expect(page.locator('body')).toBeVisible();
    // No unhandled errors
    const errors = [];
    page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });
    await page.waitForTimeout(2000);
    const realErrors = errors.filter(e => !e.includes('favicon') && !e.includes('net::ERR'));
    expect(realErrors).toHaveLength(0);
  });

  test('page has a title', async ({ page }) => {
    const title = await page.title();
    expect(title.length).toBeGreaterThan(0);
  });

  test('no JavaScript runtime errors', async ({ page }) => {
    const errors = [];
    page.on('pageerror', err => errors.push(err.message));
    await page.goto('/');
    await page.waitForTimeout(2000);
    expect(errors).toHaveLength(0);
  });
});
`
  });

  return files;
}

function generateCICDModule(ventureName, outputDir) {
  const files = [];

  mkdirSync(join(outputDir, '.github', 'workflows'), { recursive: true });

  files.push({
    path: join(outputDir, '.github', 'workflows', 'playwright.yml'),
    content: `name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: \${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
`
  });

  return files;
}

function parseArgs(args) {
  const ventureName = args.find(a => !a.startsWith('--'));
  const modulesArg = args.find(a => a.startsWith('--modules'));
  const modules = modulesArg
    ? modulesArg.split('=')[1]?.split(',') || ['testing']
    : ['testing'];
  const outputArg = args.find(a => a.startsWith('--output'));
  const output = outputArg ? outputArg.split('=')[1] : null;
  const portArg = args.find(a => a.startsWith('--port'));
  const port = portArg ? parseInt(portArg.split('=')[1], 10) : 8080;

  return { ventureName, modules, output, port };
}

function main() {
  const args = process.argv.slice(2);

  if (args.length === 0 || args.includes('--help')) {
    console.log('Usage: node scaffold.js <venture-name> [--modules=testing,ci-cd] [--output=path] [--port=8080]');
    console.log('\nAvailable modules:');
    for (const [key, mod] of Object.entries(MODULE_REGISTRY)) {
      console.log(`  ${key}: ${mod.description} (v${mod.version})`);
    }
    process.exit(0);
  }

  const { ventureName, modules, output, port } = parseArgs(args);

  if (!ventureName) {
    console.error('Error: venture name required');
    process.exit(1);
  }

  const outputDir = output || resolve(process.cwd(), ventureName);

  console.log(`\n🏗️  Scaffolding venture: ${ventureName}`);
  console.log(`   Output: ${outputDir}`);
  console.log(`   Modules: ${modules.join(', ')}`);
  console.log(`   Port: ${port}`);
  console.log('');

  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  let totalFiles = 0;

  for (const moduleName of modules) {
    const mod = MODULE_REGISTRY[moduleName];
    if (!mod) {
      console.warn(`   ⚠️  Unknown module: ${moduleName} (skipping)`);
      continue;
    }

    console.log(`   📦 ${mod.name} v${mod.version}`);
    const files = mod.generate(ventureName, outputDir, { port, baseUrl: `http://localhost:${port}` });

    for (const file of files) {
      const dir = join(file.path, '..');
      if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
      writeFileSync(file.path, file.content, 'utf-8');
      console.log(`      ✅ ${file.path.replace(outputDir, '.')}`);
      totalFiles++;
    }
  }

  console.log(`\n✅ Scaffold complete: ${totalFiles} files generated`);
  console.log(`\n💡 Next steps:`);
  console.log(`   cd ${ventureName}`);
  console.log(`   npm install @playwright/test`);
  console.log(`   npx playwright install chromium`);
  console.log(`   npx playwright test`);
}

main();
