-- ============================================================================
-- STRATEGIC DIRECTIVE: SD-ARTIFACT-INTEGRATION-001
-- Title: 25-Stage Artifact Integration + Stage-Gated Runtime Consumption
-- Priority: HIGH
-- Created: 2025-12-14
-- ============================================================================
-- Execute in Supabase SQL Editor OR via Node.js script
-- This follows LEO Protocol v4.3.3 database-first approach
-- ============================================================================
-- BOUNDARY ENFORCEMENT:
--   EHG_Engineering = governance/build-time + LEO Protocol (generates artifacts)
--   EHG = runtime consumption only (read-optimized, no generation)
-- ============================================================================

INSERT INTO strategic_directives_v2 (
    id,
    sd_key,
    title,
    category,
    priority,
    status,
    version,
    sd_type,
    description,
    rationale,
    scope,
    strategic_intent,
    success_criteria,
    risks,
    dependencies,
    success_metrics,
    stakeholders,
    metadata,
    target_application,
    current_phase,
    created_by
) VALUES (
    'SD-ARTIFACT-INTEGRATION-001',
    'SD-ARTIFACT-INTEGRATION-001',
    '25-Stage Artifact Integration + Stage-Gated Runtime Consumption',
    'feature',
    'high',
    'draft',
    '1.0',
    'feature',

    -- DESCRIPTION
    'Integrate governance-generated artifacts into the EHG runtime 25-stage venture workflow via a policy-driven, stage-gated consumption model. Establishes a clear boundary where EHG_Engineering (governance) generates and validates artifacts through LEO Protocol, while EHG (runtime) only consumes approved artifacts through read-optimized panels at specific stage gates.',

    -- RATIONALE
    'BUSINESS RATIONALE:
- Ventures need visual/design artifacts to progress through stages (currently missing)
- Runtime has partial stage coverage (6/25 stages = 24%) leaving ventures incomplete
- Quality gates exist in database but are NOT surfaced in UI, leading to approval confusion
- Vision Brief visualizations generated by governance have no consumption path in runtime

TECHNICAL RATIONALE:
- No unified stage_policy.yaml creates drift between governance and runtime expectations
- venture_artifacts table exists but no ArtifactPanel components to display them
- SuperDesign (first-party engine in EHG_Engineering) generates design contracts with no runtime visibility
- Nano Banana (third-party Gemini Image API) produces visualizations stored in Supabase with no runtime fetch
- Boundary violation risk: runtime could accidentally call governance scripts without clear separation

ARCHITECTURAL RATIONALE:
- Policy-driven: stage_policy.yaml as single source of truth for artifact requirements
- Artifact contract: Schema-validated immutable artifacts with provenance tracking
- Gate enforcement: Runtime blocks stage progression until required artifacts approved
- Separation of concerns: Generation (governance) vs Display (runtime)',

    -- SCOPE
    'INCLUDED IN SCOPE:
1. stage_policy.yaml - Canonical artifact requirements per stage
2. Artifact contract schema - Immutable, schema-validated artifact format
3. ArtifactPanel React component - Generic artifact display for runtime
4. Stage gate enforcement - Block progression without approved artifacts
5. Vision Brief consumption - Display governance visualizations in runtime
6. Quality score display - Surface validation_status in stage UI

EXCLUDED FROM SCOPE (NON-GOALS):
- Runtime artifact GENERATION (violates boundary)
- Runtime calling any governance scripts (violates boundary)
- SuperDesign engine implementation (exists, not this SD)
- Nano Banana API integration (exists, not this SD)
- Artifact drift detection (Phase 2 scope)
- Full-page visual viewers (minimal scope for Phase 1)
- Test report viewers (minimal scope for Phase 1)

BOUNDARY RULES (HARD):
- Runtime MUST NOT call governance scripts (no generate-vision-*.js from EHG)
- Runtime MUST NOT run LEO Protocol (LEO stays in EHG_Engineering)
- Runtime CAN read governance artifact URLs (via SD metadata or venture_artifacts)
- Governance owns artifact schema; runtime is read-only consumer

SYSTEMS AFFECTED:
- EHG_Engineering: stage_policy.yaml, artifact_contract.schema.json
- EHG Runtime: Stage viewer components (Stages 1-25), ArtifactPanel, gate UI
- Database: venture_artifacts table (read path), sd.metadata.vision_discovery
- Supabase Storage: vision-briefs bucket (read path only)',

    -- STRATEGIC INTENT
    'STRATEGIC ALIGNMENT:
This SD establishes the foundational architecture for artifact-driven venture workflows, enabling ventures to benefit from governance-generated assets (vision briefs, design contracts, wireframes) without compromising the build-time/runtime boundary.

ORGANIZATIONAL IMPACT:
- Chairman gains visibility: Quality gates surface in runtime UI, not hidden in database
- Ventures complete faster: Required artifacts shown in-context at relevant stages
- SuperDesign leverage: First-party design engine outputs become actionable in runtime
- Reduced manual checking: Gate enforcement automated via stage_policy

ENGINE OWNERSHIP (CRITICAL):
- SuperDesign = FIRST-PARTY custom engine in EHG_Engineering
  * Token extraction, wireframes-to-spec, design_contract JSON
  * Owned and governed by EHG_Engineering
  * NOT a third-party service
- Nano Banana = THIRD-PARTY Gemini Image API for visual generation
  * Used via visualization-provider.js
  * External dependency, costs per-image

QUALITY GATE INTEGRATION:
- 85% threshold for artifact validation_status
- Four Buckets classification (Facts, Assumptions, Simulations, Unknowns) per artifact
- Epistemic tagging required at decision stages (3, 5, 16)',

    -- SUCCESS CRITERIA (JSONB array)
    jsonb_build_array(
        jsonb_build_object(
            'id', 'SC-001',
            'criterion', 'stage_policy.yaml exists and defines artifact requirements for all 25 stages',
            'measure', 'YAML validation passes, all stages have required_artifacts array',
            'priority', 'CRITICAL'
        ),
        jsonb_build_object(
            'id', 'SC-002',
            'criterion', 'ArtifactPanel component displays governance artifacts in runtime',
            'measure', 'E2E test: Navigate to Stage 2, vision brief visualization renders if exists',
            'priority', 'CRITICAL'
        ),
        jsonb_build_object(
            'id', 'SC-003',
            'criterion', 'Stage progression blocked when required artifacts missing/unapproved',
            'measure', 'E2E test: Cannot advance Stage 3 without approved market validation artifact',
            'priority', 'CRITICAL'
        ),
        jsonb_build_object(
            'id', 'SC-004',
            'criterion', 'Runtime NEVER calls governance generation scripts',
            'measure', 'Code audit: No imports of generate-vision-*.js in EHG runtime',
            'priority', 'CRITICAL'
        ),
        jsonb_build_object(
            'id', 'SC-005',
            'criterion', 'Quality score (validation_status) visible in stage UI',
            'measure', 'UI displays validation_status badge on artifact cards, threshold indicator',
            'priority', 'HIGH'
        ),
        jsonb_build_object(
            'id', 'SC-006',
            'criterion', 'Vision Brief visualization from governance displays in runtime Stage 2-3',
            'measure', 'E2E test: Image from sd.metadata.vision_discovery.visualization.url renders',
            'priority', 'HIGH'
        ),
        jsonb_build_object(
            'id', 'SC-007',
            'criterion', 'Stage viewers expanded from 6/25 to 16/25 (64% coverage)',
            'measure', 'Component audit: StageViewer components exist for stages 1-16',
            'priority', 'HIGH'
        ),
        jsonb_build_object(
            'id', 'SC-008',
            'criterion', 'Artifact contract schema validates all governance outputs',
            'measure', 'JSON Schema validation runs on artifact insert, invalid data rejected',
            'priority', 'HIGH'
        )
    ),

    -- RISKS (JSONB array)
    jsonb_build_array(
        jsonb_build_object(
            'risk', 'Boundary violation: Runtime accidentally imports governance scripts',
            'severity', 'high',
            'probability', 'medium',
            'mitigation', 'Lint rule + PR check: Block imports from scripts/*.js in runtime. Explicit boundary comment in stage_policy.yaml.',
            'owner', 'EXEC'
        ),
        jsonb_build_object(
            'risk', 'Stage policy drift: Runtime and governance disagree on artifact requirements',
            'severity', 'medium',
            'probability', 'medium',
            'mitigation', 'Single source of truth: stage_policy.yaml in EHG_Engineering, runtime reads via API or build-time copy.',
            'owner', 'PLAN'
        ),
        jsonb_build_object(
            'risk', 'Visualization URL stale: Governance regenerates but runtime caches old URL',
            'severity', 'low',
            'probability', 'medium',
            'mitigation', 'Include prompt_hash in artifact metadata; runtime compares hash to detect staleness.',
            'owner', 'EXEC'
        ),
        jsonb_build_object(
            'risk', 'Gate enforcement too strict: Ventures stuck on stages with missing artifacts',
            'severity', 'medium',
            'probability', 'medium',
            'mitigation', 'Soft gate with Chairman override flag. Display "Required artifact missing" with request button.',
            'owner', 'PLAN'
        ),
        jsonb_build_object(
            'risk', 'Supabase storage permissions: Runtime cannot read vision-briefs bucket',
            'severity', 'low',
            'probability', 'low',
            'mitigation', 'Bucket is public. Verify RLS allows anonymous read on storage path.',
            'owner', 'DATABASE'
        ),
        jsonb_build_object(
            'risk', 'SuperDesign engine not ready: Design contracts not generated at scale',
            'severity', 'medium',
            'probability', 'low',
            'mitigation', 'Phase 1 focuses on Vision Brief artifacts (already implemented). SuperDesign contracts are Phase 2 enhancement.',
            'owner', 'LEAD'
        )
    ),

    -- DEPENDENCIES (JSONB array)
    jsonb_build_array(
        jsonb_build_object(
            'dependency', 'Vision Brief generation scripts (generate-vision-brief.js)',
            'type', 'technical',
            'status', 'ready',
            'notes', 'Already implemented in EHG_Engineering, stores in sd.metadata.vision_discovery'
        ),
        jsonb_build_object(
            'dependency', 'Vision visualization script (generate-vision-visualization.js)',
            'type', 'technical',
            'status', 'ready',
            'notes', 'Stores image URL in sd.metadata.vision_discovery.visualization.url'
        ),
        jsonb_build_object(
            'dependency', 'venture_artifacts table in EHG database',
            'type', 'technical',
            'status', 'ready',
            'notes', 'Exists with 64 artifact types, versioning, quality_score fields'
        ),
        jsonb_build_object(
            'dependency', 'stages_v2.yaml (25-stage definition)',
            'type', 'technical',
            'status', 'ready',
            'notes', 'Defines phases, stages, gates, artifacts per stage'
        ),
        jsonb_build_object(
            'dependency', 'Supabase Storage vision-briefs bucket',
            'type', 'technical',
            'status', 'ready',
            'notes', 'Public bucket for visualization images'
        ),
        jsonb_build_object(
            'dependency', 'SuperDesign engine (first-party)',
            'type', 'technical',
            'status', 'partial',
            'notes', 'Token extraction exists; wireframes-to-spec in progress. Not blocking Phase 1.'
        ),
        jsonb_build_object(
            'dependency', 'Nano Banana integration (Gemini Image API)',
            'type', 'external',
            'status', 'ready',
            'notes', 'visualization-provider.js implements Gemini 2.5 Flash image generation'
        )
    ),

    -- SUCCESS METRICS (JSONB object)
    jsonb_build_object(
        'implementation', jsonb_build_object(
            'stage_policy_coverage', '25/25 stages defined',
            'artifact_panel_coverage', '16/25 stages with viewers',
            'gate_enforcement_stages', 'Stages 3, 5, 10, 16 (decision gates)',
            'total_effort_hours', 40
        ),
        'quality', jsonb_build_object(
            'boundary_violations', '0 (hard requirement)',
            'artifact_schema_validation_rate', '100%',
            'gate_pass_rate_target', '>85%',
            'staleness_detection_accuracy', '>95%'
        ),
        'adoption', jsonb_build_object(
            'runtime_artifact_display_rate', '>80% of ventures see artifacts',
            'gate_override_rate', '<10% (Chairman overrides)',
            'artifact_request_from_runtime', '>20% ventures request missing artifacts'
        ),
        'business', jsonb_build_object(
            'venture_progression_improvement', '15% faster through stages with artifacts',
            'chairman_visibility_increase', 'Quality gates visible in UI vs hidden in DB',
            'superdesign_leverage', 'Design contracts consumable in runtime'
        )
    ),

    -- STAKEHOLDERS (JSONB array)
    jsonb_build_array(
        jsonb_build_object(
            'name', 'Chairman',
            'role', 'Executive Sponsor & Boundary Enforcer',
            'involvement', 'Approve boundary rules, override stuck gates, review artifact quality',
            'contact', 'Primary stakeholder'
        ),
        jsonb_build_object(
            'name', 'LEAD Agent',
            'role', 'Boundary Validator',
            'involvement', 'Verify governance/runtime separation, approve stage_policy',
            'contact', 'LEO Protocol agent'
        ),
        jsonb_build_object(
            'name', 'PLAN Agent',
            'role', 'Schema Designer',
            'involvement', 'Design artifact_contract schema, stage_policy structure, PRD',
            'contact', 'LEO Protocol agent'
        ),
        jsonb_build_object(
            'name', 'EXEC Agent',
            'role', 'Implementation Lead',
            'involvement', 'Build ArtifactPanel, gate enforcement, stage viewers',
            'contact', 'LEO Protocol agent'
        ),
        jsonb_build_object(
            'name', 'DATABASE Sub-Agent',
            'role', 'Schema & Migration',
            'involvement', 'Extend venture_artifacts if needed, RLS policies',
            'contact', 'LEO Protocol sub-agent'
        ),
        jsonb_build_object(
            'name', 'DESIGN Sub-Agent',
            'role', 'UI/UX for ArtifactPanel',
            'involvement', 'Component design, artifact card layout, gate indicator UX',
            'contact', 'LEO Protocol sub-agent'
        ),
        jsonb_build_object(
            'name', 'Venture Users',
            'role', 'End Users',
            'involvement', 'Consume artifacts in stages, request missing artifacts, provide feedback',
            'contact', 'EHG application users'
        )
    ),

    -- METADATA (JSONB object)
    jsonb_build_object(
        'estimated_effort_hours', 40,
        'complexity', 'MEDIUM',
        'impact_scope', 'Runtime stage workflow, artifact display, gate enforcement',
        'breaking_changes', false,
        'requires_migration', false,
        'phased_delivery', true,
        'phases', jsonb_build_array(
            jsonb_build_object(
                'phase', 1,
                'name', 'Policy + Schema',
                'deliverables', jsonb_build_array(
                    'stage_policy.yaml',
                    'artifact_contract.schema.json'
                ),
                'effort_hours', 8
            ),
            jsonb_build_object(
                'phase', 2,
                'name', 'ArtifactPanel + Vision Brief Display',
                'deliverables', jsonb_build_array(
                    'ArtifactPanel component',
                    'Vision Brief viewer in Stage 2-3',
                    'Gate indicator UI'
                ),
                'effort_hours', 16
            ),
            jsonb_build_object(
                'phase', 3,
                'name', 'Gate Enforcement + Stage Expansion',
                'deliverables', jsonb_build_array(
                    'Gate blocking logic',
                    'Stage viewers 7-16',
                    'Quality score display'
                ),
                'effort_hours', 16
            )
        ),
        'boundary_rules', jsonb_build_object(
            'runtime_cannot_call', jsonb_build_array(
                'generate-vision-brief.js',
                'generate-vision-visualization.js',
                'approve-vision-brief.js',
                'Any LEO Protocol scripts'
            ),
            'runtime_can_read', jsonb_build_array(
                'sd.metadata.vision_discovery',
                'venture_artifacts table',
                'Supabase Storage vision-briefs bucket'
            ),
            'governance_owns', jsonb_build_array(
                'stage_policy.yaml',
                'artifact_contract.schema.json',
                'All generation scripts',
                'LEO Protocol execution'
            )
        ),
        'engine_ownership', jsonb_build_object(
            'superdesign', jsonb_build_object(
                'type', 'first-party',
                'location', 'EHG_Engineering',
                'description', 'Custom design engine: token extraction, wireframes-to-spec, design_contract JSON',
                'owner', 'EHG_Engineering'
            ),
            'nano_banana', jsonb_build_object(
                'type', 'third-party',
                'provider', 'Google Gemini',
                'api', 'gemini-2.5-flash-image',
                'description', 'Visual generation API for vision brief images',
                'cost_model', 'per-image'
            )
        ),
        'acceptance_criteria_count', 8,
        'stages_affected', 25,
        'new_files', jsonb_build_array(
            'config/stage_policy.yaml',
            'config/artifact_contract.schema.json',
            'src/components/artifacts/ArtifactPanel.tsx',
            'src/components/artifacts/VisionBriefViewer.tsx',
            'src/components/gates/GateIndicator.tsx'
        ),
        'modified_files', jsonb_build_array(
            'Stage viewer components (1-16)',
            'Venture workflow orchestrator'
        )
    ),

    -- TARGET APPLICATION
    'EHG',  -- Runtime application

    -- CURRENT PHASE
    'LEAD_APPROVAL',

    -- CREATED BY
    'human:Chairman'
);

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- Verify insertion
SELECT
    id,
    sd_key,
    title,
    category,
    priority,
    status,
    version,
    sd_type,
    target_application,
    current_phase,
    created_at,
    created_by
FROM strategic_directives_v2
WHERE id = 'SD-ARTIFACT-INTEGRATION-001';

-- Check success criteria count (should be 8)
SELECT
    id,
    jsonb_array_length(success_criteria) as success_criteria_count
FROM strategic_directives_v2
WHERE id = 'SD-ARTIFACT-INTEGRATION-001';

-- Check risks count (should be 6)
SELECT
    id,
    jsonb_array_length(risks) as risks_count
FROM strategic_directives_v2
WHERE id = 'SD-ARTIFACT-INTEGRATION-001';

-- Check boundary rules in metadata
SELECT
    id,
    metadata->'boundary_rules'->'runtime_cannot_call' as runtime_blocked,
    metadata->'engine_ownership' as engines
FROM strategic_directives_v2
WHERE id = 'SD-ARTIFACT-INTEGRATION-001';

-- ============================================================================
-- SUCCESS MESSAGE
-- ============================================================================
DO $$
BEGIN
  RAISE NOTICE '============================================================================';
  RAISE NOTICE 'SD-ARTIFACT-INTEGRATION-001 created successfully!';
  RAISE NOTICE '============================================================================';
  RAISE NOTICE '';
  RAISE NOTICE 'BOUNDARY ENFORCEMENT:';
  RAISE NOTICE '  - Runtime CANNOT call: generate-vision-*.js, LEO Protocol scripts';
  RAISE NOTICE '  - Runtime CAN read: sd.metadata, venture_artifacts, Storage bucket';
  RAISE NOTICE '  - Governance OWNS: stage_policy.yaml, artifact schema, all generation';
  RAISE NOTICE '';
  RAISE NOTICE 'ENGINE OWNERSHIP:';
  RAISE NOTICE '  - SuperDesign: FIRST-PARTY custom engine in EHG_Engineering';
  RAISE NOTICE '  - Nano Banana: THIRD-PARTY Gemini Image API';
  RAISE NOTICE '';
  RAISE NOTICE 'Next Steps (LEO Protocol):';
  RAISE NOTICE '1. LEAD Agent: Review and approve directive (LEAD_APPROVAL phase)';
  RAISE NOTICE '2. PLAN Agent: Create PRD with stage_policy schema';
  RAISE NOTICE '3. EXEC Agent: Implement ArtifactPanel, gate enforcement';
  RAISE NOTICE '';
  RAISE NOTICE 'View in dashboard: /strategic-directives/SD-ARTIFACT-INTEGRATION-001';
  RAISE NOTICE '============================================================================';
END $$;
