#!/usr/bin/env node

/**
 * Awwwards Curated Design Reference Seeder
 * SD: SD-MAN-INFRA-AWWWARDS-CURATED-DESIGN-001
 *
 * Seeds the design_reference_library table with a curated dataset of
 * 63 award-winning sites across 7 archetypes (9 per archetype).
 *
 * Uses a static JSON dataset instead of live scraping — Awwwards blocks
 * automated scraping, and this is a $0-budget one-time seed.
 *
 * Usage:
 *   node scripts/eva/srip/awwwards-scraper.mjs             # Insert into Supabase
 *   node scripts/eva/srip/awwwards-scraper.mjs --dry-run    # Print without inserting
 */

import dotenv from 'dotenv';
dotenv.config();

// ---------------------------------------------------------------------------
// Static curated dataset: 63 award-winning sites (9 per archetype)
// ---------------------------------------------------------------------------

export const CURATED_REFERENCES = [
  // =========================================================================
  // SAAS (9 sites)
  // =========================================================================
  {
    url: 'https://stripe.com',
    site_name: 'Stripe',
    archetype_category: 'saas',
    design_score: 9.10,
    usability_score: 9.20,
    creativity_score: 8.80,
    content_score: 9.00,
    tech_stack: 'React, Next.js, Ruby',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2024-03-15',
    description: 'Payment infrastructure platform with industry-leading developer docs and interactive API demos.',
  },
  {
    url: 'https://linear.app',
    site_name: 'Linear',
    archetype_category: 'saas',
    design_score: 9.30,
    usability_score: 9.00,
    creativity_score: 9.20,
    content_score: 8.70,
    tech_stack: 'React, Next.js, TypeScript',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2024-01-22',
    description: 'Issue tracking tool with exceptional motion design and keyboard-first UX.',
  },
  {
    url: 'https://notion.so',
    site_name: 'Notion',
    archetype_category: 'saas',
    design_score: 8.90,
    usability_score: 9.40,
    creativity_score: 8.60,
    content_score: 9.10,
    tech_stack: 'React, Next.js, Electron',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2023-11-05',
    description: 'All-in-one workspace blending notes, docs, and databases with playful illustration style.',
  },
  {
    url: 'https://vercel.com',
    site_name: 'Vercel',
    archetype_category: 'saas',
    design_score: 9.20,
    usability_score: 8.90,
    creativity_score: 9.10,
    content_score: 8.80,
    tech_stack: 'Next.js, React, TypeScript',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2024-06-10',
    description: 'Frontend cloud platform with dark-mode-first design and real-time deployment previews.',
  },
  {
    url: 'https://pitch.com',
    site_name: 'Pitch',
    archetype_category: 'saas',
    design_score: 9.00,
    usability_score: 8.80,
    creativity_score: 9.30,
    content_score: 8.90,
    tech_stack: 'React, WebGL, Electron',
    agency_name: 'In-house',
    country: 'Germany',
    date_awarded: '2023-09-18',
    description: 'Collaborative presentation software with stunning template gallery and real-time co-editing.',
  },
  {
    url: 'https://www.loom.com',
    site_name: 'Loom',
    archetype_category: 'saas',
    design_score: 8.70,
    usability_score: 9.10,
    creativity_score: 8.50,
    content_score: 9.20,
    tech_stack: 'React, Node.js, WebRTC',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2023-07-12',
    description: 'Async video messaging platform with clean onboarding and inline video players.',
  },
  {
    url: 'https://www.figma.com',
    site_name: 'Figma',
    archetype_category: 'saas',
    design_score: 9.40,
    usability_score: 9.30,
    creativity_score: 9.50,
    content_score: 9.00,
    tech_stack: 'C++, WebAssembly, React',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2024-02-28',
    description: 'Collaborative design tool with WebGL canvas and pioneering multiplayer editing.',
  },
  {
    url: 'https://www.framer.com',
    site_name: 'Framer',
    archetype_category: 'saas',
    design_score: 9.30,
    usability_score: 8.70,
    creativity_score: 9.40,
    content_score: 8.60,
    tech_stack: 'React, Framer Motion, TypeScript',
    agency_name: 'In-house',
    country: 'Netherlands',
    date_awarded: '2024-04-03',
    description: 'No-code website builder with live canvas editing and production-grade code export.',
  },
  {
    url: 'https://www.raycast.com',
    site_name: 'Raycast',
    archetype_category: 'saas',
    design_score: 9.00,
    usability_score: 9.50,
    creativity_score: 8.90,
    content_score: 8.80,
    tech_stack: 'Swift, React, TypeScript',
    agency_name: 'In-house',
    country: 'United Kingdom',
    date_awarded: '2024-05-20',
    description: 'Productivity launcher with developer-focused extensions and stunning dark UI.',
  },

  // =========================================================================
  // MARKETPLACE (9 sites)
  // =========================================================================
  {
    url: 'https://www.airbnb.com',
    site_name: 'Airbnb',
    archetype_category: 'marketplace',
    design_score: 9.10,
    usability_score: 9.50,
    creativity_score: 8.90,
    content_score: 9.30,
    tech_stack: 'React, Next.js, Ruby on Rails',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2024-01-10',
    description: 'Global accommodation marketplace with immersive photo galleries and map-based search.',
  },
  {
    url: 'https://www.etsy.com',
    site_name: 'Etsy',
    archetype_category: 'marketplace',
    design_score: 8.50,
    usability_score: 9.00,
    creativity_score: 8.40,
    content_score: 8.80,
    tech_stack: 'React, PHP, MySQL',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2023-06-25',
    description: 'Handmade and vintage marketplace with personalized discovery and seller storytelling.',
  },
  {
    url: 'https://www.fiverr.com',
    site_name: 'Fiverr',
    archetype_category: 'marketplace',
    design_score: 8.60,
    usability_score: 8.90,
    creativity_score: 8.30,
    content_score: 8.70,
    tech_stack: 'React, Node.js, Python',
    agency_name: 'In-house',
    country: 'Israel',
    date_awarded: '2023-08-14',
    description: 'Freelance services marketplace with AI-powered matching and category-driven browsing.',
  },
  {
    url: 'https://www.stockx.com',
    site_name: 'StockX',
    archetype_category: 'marketplace',
    design_score: 8.80,
    usability_score: 8.70,
    creativity_score: 8.60,
    content_score: 8.50,
    tech_stack: 'React, Node.js, Go',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2023-10-02',
    description: 'Sneaker and streetwear marketplace using stock-market-style pricing with live bid/ask.',
  },
  {
    url: 'https://www.vinted.com',
    site_name: 'Vinted',
    archetype_category: 'marketplace',
    design_score: 8.40,
    usability_score: 9.10,
    creativity_score: 8.20,
    content_score: 8.90,
    tech_stack: 'React, Ruby on Rails, Go',
    agency_name: 'In-house',
    country: 'Lithuania',
    date_awarded: '2024-02-15',
    description: 'Second-hand fashion marketplace with zero-commission selling and smart catalog filters.',
  },
  {
    url: 'https://www.behance.net',
    site_name: 'Behance',
    archetype_category: 'marketplace',
    design_score: 9.00,
    usability_score: 8.60,
    creativity_score: 9.10,
    content_score: 8.40,
    tech_stack: 'React, GraphQL, Adobe stack',
    agency_name: 'Adobe',
    country: 'United States',
    date_awarded: '2023-12-08',
    description: 'Creative portfolio and talent marketplace with immersive project showcases.',
  },
  {
    url: 'https://www.reverb.com',
    site_name: 'Reverb',
    archetype_category: 'marketplace',
    design_score: 8.70,
    usability_score: 9.00,
    creativity_score: 8.50,
    content_score: 8.80,
    tech_stack: 'React, Ruby on Rails, Elasticsearch',
    agency_name: 'In-house (Etsy)',
    country: 'United States',
    date_awarded: '2023-05-17',
    description: 'Musical instrument marketplace with gear-specific filters and price guide data.',
  },
  {
    url: 'https://www.goat.com',
    site_name: 'GOAT',
    archetype_category: 'marketplace',
    design_score: 8.90,
    usability_score: 8.80,
    creativity_score: 8.70,
    content_score: 8.30,
    tech_stack: 'React Native, Go, PostgreSQL',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2024-03-22',
    description: 'Authenticated sneaker marketplace with 3D product views and authentication guarantee.',
  },
  {
    url: 'https://www.peerspace.com',
    site_name: 'Peerspace',
    archetype_category: 'marketplace',
    design_score: 8.50,
    usability_score: 9.20,
    creativity_score: 8.30,
    content_score: 8.90,
    tech_stack: 'React, Node.js, PostgreSQL',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2023-09-30',
    description: 'Event and production space marketplace with rich photo tours and instant booking.',
  },

  // =========================================================================
  // FINTECH (9 sites)
  // =========================================================================
  {
    url: 'https://www.revolut.com',
    site_name: 'Revolut',
    archetype_category: 'fintech',
    design_score: 9.00,
    usability_score: 8.90,
    creativity_score: 8.80,
    content_score: 8.70,
    tech_stack: 'React, Kotlin, Swift',
    agency_name: 'In-house',
    country: 'United Kingdom',
    date_awarded: '2024-01-18',
    description: 'Digital banking super-app with sleek card management UI and real-time currency exchange.',
  },
  {
    url: 'https://www.wise.com',
    site_name: 'Wise',
    archetype_category: 'fintech',
    design_score: 8.80,
    usability_score: 9.30,
    creativity_score: 8.50,
    content_score: 9.10,
    tech_stack: 'React, Java, PostgreSQL',
    agency_name: 'In-house',
    country: 'United Kingdom',
    date_awarded: '2023-11-20',
    description: 'International money transfer platform with transparent fee calculator and trust-building UX.',
  },
  {
    url: 'https://mercury.com',
    site_name: 'Mercury',
    archetype_category: 'fintech',
    design_score: 9.20,
    usability_score: 9.00,
    creativity_score: 9.10,
    content_score: 8.80,
    tech_stack: 'React, Haskell, PostgreSQL',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2024-04-12',
    description: 'Startup banking with minimalist dashboard design and integrated treasury management.',
  },
  {
    url: 'https://www.robinhood.com',
    site_name: 'Robinhood',
    archetype_category: 'fintech',
    design_score: 8.90,
    usability_score: 9.20,
    creativity_score: 8.60,
    content_score: 8.70,
    tech_stack: 'React, Python, Go',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2023-08-05',
    description: 'Commission-free trading platform with signature green line charts and gamified portfolio view.',
  },
  {
    url: 'https://www.brex.com',
    site_name: 'Brex',
    archetype_category: 'fintech',
    design_score: 9.10,
    usability_score: 8.80,
    creativity_score: 9.00,
    content_score: 8.60,
    tech_stack: 'React, Elixir, Kotlin',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2024-02-08',
    description: 'Corporate card and spend management with polished dark UI and real-time expense tracking.',
  },
  {
    url: 'https://www.ramp.com',
    site_name: 'Ramp',
    archetype_category: 'fintech',
    design_score: 8.70,
    usability_score: 9.10,
    creativity_score: 8.40,
    content_score: 9.00,
    tech_stack: 'React, Python, PostgreSQL',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2023-12-15',
    description: 'Finance automation platform with clean data visualization and AI-powered savings insights.',
  },
  {
    url: 'https://www.n26.com',
    site_name: 'N26',
    archetype_category: 'fintech',
    design_score: 9.00,
    usability_score: 9.10,
    creativity_score: 8.70,
    content_score: 8.80,
    tech_stack: 'React, Kotlin, Swift',
    agency_name: 'In-house',
    country: 'Germany',
    date_awarded: '2024-05-02',
    description: 'Mobile-first digital bank with transparent pricing pages and smooth onboarding flow.',
  },
  {
    url: 'https://www.coinbase.com',
    site_name: 'Coinbase',
    archetype_category: 'fintech',
    design_score: 8.80,
    usability_score: 8.90,
    creativity_score: 8.50,
    content_score: 8.60,
    tech_stack: 'React, Go, Ruby on Rails',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2023-10-28',
    description: 'Cryptocurrency exchange with beginner-friendly interface and institutional-grade security.',
  },
  {
    url: 'https://www.plaid.com',
    site_name: 'Plaid',
    archetype_category: 'fintech',
    design_score: 9.30,
    usability_score: 8.70,
    creativity_score: 9.20,
    content_score: 8.90,
    tech_stack: 'React, Node.js, Python',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2024-06-18',
    description: 'Financial data infrastructure with award-winning developer documentation and animated diagrams.',
  },

  // =========================================================================
  // HEALTHTECH (9 sites)
  // =========================================================================
  {
    url: 'https://www.onemedical.com',
    site_name: 'One Medical',
    archetype_category: 'healthtech',
    design_score: 8.60,
    usability_score: 9.20,
    creativity_score: 8.30,
    content_score: 9.10,
    tech_stack: 'React, Ruby on Rails',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2023-07-22',
    description: 'Primary care membership with soothing color palette and frictionless appointment booking.',
  },
  {
    url: 'https://www.hims.com',
    site_name: 'Hims & Hers',
    archetype_category: 'healthtech',
    design_score: 9.10,
    usability_score: 8.80,
    creativity_score: 9.00,
    content_score: 8.70,
    tech_stack: 'React, Next.js, Shopify',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2024-03-05',
    description: 'Telehealth and wellness brand with bold typography and destigmatizing visual language.',
  },
  {
    url: 'https://www.headspace.com',
    site_name: 'Headspace',
    archetype_category: 'healthtech',
    design_score: 9.20,
    usability_score: 9.10,
    creativity_score: 9.40,
    content_score: 9.00,
    tech_stack: 'React, Swift, Kotlin',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2024-01-30',
    description: 'Meditation and mindfulness app with signature illustration style and calming motion design.',
  },
  {
    url: 'https://www.noom.com',
    site_name: 'Noom',
    archetype_category: 'healthtech',
    design_score: 8.50,
    usability_score: 9.00,
    creativity_score: 8.20,
    content_score: 8.90,
    tech_stack: 'React, Python, Kotlin',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2023-09-12',
    description: 'Behavior change weight management with psychology-based onboarding quiz and progress tracking.',
  },
  {
    url: 'https://www.calm.com',
    site_name: 'Calm',
    archetype_category: 'healthtech',
    design_score: 9.00,
    usability_score: 9.30,
    creativity_score: 8.80,
    content_score: 9.20,
    tech_stack: 'React, Swift, Node.js',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2024-04-20',
    description: 'Sleep and meditation app with nature-inspired backgrounds and ambient soundscapes.',
  },
  {
    url: 'https://ro.co',
    site_name: 'Ro',
    archetype_category: 'healthtech',
    design_score: 8.80,
    usability_score: 8.90,
    creativity_score: 8.50,
    content_score: 8.80,
    tech_stack: 'React, Next.js, Python',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2023-11-28',
    description: 'Direct-to-patient healthcare platform with clean clinical design and transparent pricing.',
  },
  {
    url: 'https://www.oura.com',
    site_name: 'Oura',
    archetype_category: 'healthtech',
    design_score: 9.30,
    usability_score: 8.70,
    creativity_score: 9.20,
    content_score: 8.60,
    tech_stack: 'React, Next.js, Swift',
    agency_name: 'In-house',
    country: 'Finland',
    date_awarded: '2024-05-15',
    description: 'Health-tracking ring with premium product photography and data-rich health dashboards.',
  },
  {
    url: 'https://www.whoop.com',
    site_name: 'WHOOP',
    archetype_category: 'healthtech',
    design_score: 9.10,
    usability_score: 8.60,
    creativity_score: 9.00,
    content_score: 8.50,
    tech_stack: 'React, Swift, Python',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2024-02-22',
    description: 'Performance wearable with athlete-focused branding and detailed strain/recovery metrics.',
  },
  {
    url: 'https://www.zocdoc.com',
    site_name: 'Zocdoc',
    archetype_category: 'healthtech',
    design_score: 8.40,
    usability_score: 9.40,
    creativity_score: 8.10,
    content_score: 9.10,
    tech_stack: 'React, .NET, PostgreSQL',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2023-06-08',
    description: 'Doctor booking platform with instant availability search and playful character illustrations.',
  },

  // =========================================================================
  // E-COMMERCE (9 sites)
  // =========================================================================
  {
    url: 'https://www.apple.com/store',
    site_name: 'Apple Store',
    archetype_category: 'e-commerce',
    design_score: 9.50,
    usability_score: 9.40,
    creativity_score: 9.30,
    content_score: 9.20,
    tech_stack: 'React, Swift, Custom CMS',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2024-06-01',
    description: 'Premium product shopping with immersive 3D product configurators and seamless checkout.',
  },
  {
    url: 'https://www.allbirds.com',
    site_name: 'Allbirds',
    archetype_category: 'e-commerce',
    design_score: 8.90,
    usability_score: 9.10,
    creativity_score: 8.70,
    content_score: 9.00,
    tech_stack: 'React, Shopify Plus, Node.js',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2023-10-15',
    description: 'Sustainable footwear brand with earthy palette, carbon footprint labels, and quick-buy flow.',
  },
  {
    url: 'https://www.glossier.com',
    site_name: 'Glossier',
    archetype_category: 'e-commerce',
    design_score: 9.20,
    usability_score: 8.80,
    creativity_score: 9.10,
    content_score: 8.70,
    tech_stack: 'React, Next.js, Contentful',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2024-02-14',
    description: 'Beauty brand with millennial pink aesthetic, editorial product pages, and community reviews.',
  },
  {
    url: 'https://www.everlane.com',
    site_name: 'Everlane',
    archetype_category: 'e-commerce',
    design_score: 8.70,
    usability_score: 9.00,
    creativity_score: 8.40,
    content_score: 9.20,
    tech_stack: 'React, Ruby on Rails, Shopify',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2023-08-28',
    description: 'Transparent fashion retail with factory cost breakdowns and minimal grid layouts.',
  },
  {
    url: 'https://www.aesop.com',
    site_name: 'Aesop',
    archetype_category: 'e-commerce',
    design_score: 9.40,
    usability_score: 8.60,
    creativity_score: 9.50,
    content_score: 8.80,
    tech_stack: 'React, Next.js, Contentful',
    agency_name: 'In-house',
    country: 'Australia',
    date_awarded: '2024-04-08',
    description: 'Premium skincare with literary-inspired copy, warm tones, and elegant product carousels.',
  },
  {
    url: 'https://www.warbyparker.com',
    site_name: 'Warby Parker',
    archetype_category: 'e-commerce',
    design_score: 8.80,
    usability_score: 9.30,
    creativity_score: 8.60,
    content_score: 9.10,
    tech_stack: 'React, Next.js, Ruby on Rails',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2023-12-20',
    description: 'Eyewear DTC with virtual try-on AR feature and lifestyle-driven product photography.',
  },
  {
    url: 'https://www.mejuri.com',
    site_name: 'Mejuri',
    archetype_category: 'e-commerce',
    design_score: 9.00,
    usability_score: 8.70,
    creativity_score: 8.80,
    content_score: 8.60,
    tech_stack: 'React, Shopify Plus, Contentful',
    agency_name: 'In-house',
    country: 'Canada',
    date_awarded: '2024-01-05',
    description: 'Fine jewelry DTC with soft editorial imagery and curated collection storytelling.',
  },
  {
    url: 'https://www.gymshark.com',
    site_name: 'Gymshark',
    archetype_category: 'e-commerce',
    design_score: 8.60,
    usability_score: 9.00,
    creativity_score: 8.50,
    content_score: 8.90,
    tech_stack: 'React, Shopify Plus, Node.js',
    agency_name: 'In-house',
    country: 'United Kingdom',
    date_awarded: '2023-07-30',
    description: 'Athletic apparel with influencer-driven content, quick-view product cards, and loyalty program.',
  },
  {
    url: 'https://www.away.com',
    site_name: 'Away',
    archetype_category: 'e-commerce',
    design_score: 8.80,
    usability_score: 8.90,
    creativity_score: 8.70,
    content_score: 9.10,
    tech_stack: 'React, Next.js, Shopify',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2024-03-18',
    description: 'Travel luggage brand with wanderlust editorial design and feature comparison tool.',
  },

  // =========================================================================
  // PORTFOLIO (9 sites)
  // =========================================================================
  {
    url: 'https://www.awwwards.com/sites/bruno-simon',
    site_name: 'Bruno Simon Portfolio',
    archetype_category: 'portfolio',
    design_score: 9.60,
    usability_score: 8.20,
    creativity_score: 9.80,
    content_score: 8.40,
    tech_stack: 'Three.js, WebGL, Cannon.js',
    agency_name: 'Bruno Simon',
    country: 'France',
    date_awarded: '2023-05-10',
    description: 'Interactive 3D portfolio where visitors drive a toy car through the resume — a WebGL masterpiece.',
  },
  {
    url: 'https://www.seanhalpin.xyz',
    site_name: 'Sean Halpin',
    archetype_category: 'portfolio',
    design_score: 9.10,
    usability_score: 8.90,
    creativity_score: 9.20,
    content_score: 8.60,
    tech_stack: 'Next.js, Framer Motion, GSAP',
    agency_name: 'Sean Halpin',
    country: 'Ireland',
    date_awarded: '2024-02-05',
    description: 'Designer portfolio with smooth page transitions, case study deep-dives, and scroll animations.',
  },
  {
    url: 'https://www.lfrfrr.com',
    site_name: 'Loris Fregolent',
    archetype_category: 'portfolio',
    design_score: 9.30,
    usability_score: 8.50,
    creativity_score: 9.50,
    content_score: 8.30,
    tech_stack: 'GSAP, Three.js, Nuxt.js',
    agency_name: 'Loris Fregolent',
    country: 'Italy',
    date_awarded: '2024-04-15',
    description: 'Creative developer portfolio with kinetic typography and WebGL shader experiments.',
  },
  {
    url: 'https://www.denissnellenberg.com',
    site_name: 'Denis Snellenberg',
    archetype_category: 'portfolio',
    design_score: 9.40,
    usability_score: 8.40,
    creativity_score: 9.60,
    content_score: 8.20,
    tech_stack: 'GSAP, WebGL, Next.js',
    agency_name: 'Denis Snellenberg',
    country: 'Netherlands',
    date_awarded: '2023-11-12',
    description: 'Award-winning freelance portfolio with liquid distortion effects and monochrome palette.',
  },
  {
    url: 'https://brittanychiang.com',
    site_name: 'Brittany Chiang',
    archetype_category: 'portfolio',
    design_score: 8.80,
    usability_score: 9.40,
    creativity_score: 8.60,
    content_score: 9.00,
    tech_stack: 'Gatsby, React, Styled Components',
    agency_name: 'Brittany Chiang',
    country: 'United States',
    date_awarded: '2023-06-20',
    description: 'Software engineer portfolio with clean dark theme, accessible design, and project archive.',
  },
  {
    url: 'https://www.timothysamuel.com',
    site_name: 'Timothy Samuel',
    archetype_category: 'portfolio',
    design_score: 9.20,
    usability_score: 8.60,
    creativity_score: 9.30,
    content_score: 8.50,
    tech_stack: 'Three.js, GSAP, React',
    agency_name: 'Timothy Samuel',
    country: 'United States',
    date_awarded: '2024-05-28',
    description: 'Creative director portfolio with immersive parallax storytelling and editorial layout.',
  },
  {
    url: 'https://www.tamalsen.dev',
    site_name: 'Tamal Sen',
    archetype_category: 'portfolio',
    design_score: 8.90,
    usability_score: 9.10,
    creativity_score: 8.80,
    content_score: 8.70,
    tech_stack: 'Next.js, Framer Motion, MDX',
    agency_name: 'Tamal Sen',
    country: 'India',
    date_awarded: '2024-01-15',
    description: 'Developer portfolio with blog integration, code snippets, and subtle micro-interactions.',
  },
  {
    url: 'https://www.mayagao.com',
    site_name: 'Maya Gao',
    archetype_category: 'portfolio',
    design_score: 9.00,
    usability_score: 8.80,
    creativity_score: 9.10,
    content_score: 8.60,
    tech_stack: 'React, Three.js, GLSL',
    agency_name: 'Maya Gao',
    country: 'Canada',
    date_awarded: '2023-08-22',
    description: 'Digital artist portfolio with generative art backgrounds and immersive project showcases.',
  },
  {
    url: 'https://www.joshcomeau.com',
    site_name: 'Josh Comeau',
    archetype_category: 'portfolio',
    design_score: 9.10,
    usability_score: 9.50,
    creativity_score: 9.00,
    content_score: 9.40,
    tech_stack: 'Next.js, MDX, Styled Components',
    agency_name: 'Josh Comeau',
    country: 'Canada',
    date_awarded: '2024-06-12',
    description: 'Developer blog-portfolio with interactive code playgrounds and whimsical spring animations.',
  },

  // =========================================================================
  // CORPORATE (9 sites)
  // =========================================================================
  {
    url: 'https://www.tesla.com',
    site_name: 'Tesla',
    archetype_category: 'corporate',
    design_score: 9.30,
    usability_score: 9.10,
    creativity_score: 9.20,
    content_score: 8.80,
    tech_stack: 'React, Next.js, Node.js',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2024-05-08',
    description: 'Automotive corporate site with full-bleed video, 3D car configurator, and cinematic storytelling.',
  },
  {
    url: 'https://www.ibm.com/design',
    site_name: 'IBM Design',
    archetype_category: 'corporate',
    design_score: 9.00,
    usability_score: 9.20,
    creativity_score: 8.70,
    content_score: 9.10,
    tech_stack: 'React, Carbon Design System',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2023-09-25',
    description: 'Enterprise design language hub with open-source component library and design thinking resources.',
  },
  {
    url: 'https://about.google',
    site_name: 'Google About',
    archetype_category: 'corporate',
    design_score: 8.80,
    usability_score: 9.30,
    creativity_score: 8.60,
    content_score: 9.20,
    tech_stack: 'Angular, Material Design, Web Components',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2024-02-20',
    description: 'Corporate about page with Material Design 3 components, data storytelling, and accessibility.',
  },
  {
    url: 'https://www.salesforce.com',
    site_name: 'Salesforce',
    archetype_category: 'corporate',
    design_score: 8.70,
    usability_score: 9.00,
    creativity_score: 8.40,
    content_score: 8.90,
    tech_stack: 'React, Lightning Design System',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2023-11-15',
    description: 'Enterprise CRM with character-driven brand (Astro), interactive product tours, and ROI calculators.',
  },
  {
    url: 'https://www.hubspot.com',
    site_name: 'HubSpot',
    archetype_category: 'corporate',
    design_score: 8.60,
    usability_score: 9.10,
    creativity_score: 8.30,
    content_score: 9.30,
    tech_stack: 'React, HubSpot CMS, Node.js',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2024-03-10',
    description: 'Inbound marketing platform with content-rich resource library and conversion-optimized layouts.',
  },
  {
    url: 'https://www.mckinsey.com',
    site_name: 'McKinsey & Company',
    archetype_category: 'corporate',
    design_score: 8.90,
    usability_score: 8.80,
    creativity_score: 8.50,
    content_score: 9.40,
    tech_stack: 'React, Gatsby, Contentful',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2023-07-05',
    description: 'Management consulting with data-driven editorial design and insight visualization.',
  },
  {
    url: 'https://www.spacex.com',
    site_name: 'SpaceX',
    archetype_category: 'corporate',
    design_score: 9.40,
    usability_score: 8.50,
    creativity_score: 9.50,
    content_score: 8.60,
    tech_stack: 'React, Three.js, WebGL',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2024-06-25',
    description: 'Aerospace corporate site with cinematic full-screen video, mission timelines, and live telemetry.',
  },
  {
    url: 'https://www.patagonia.com',
    site_name: 'Patagonia',
    archetype_category: 'corporate',
    design_score: 8.80,
    usability_score: 9.00,
    creativity_score: 8.70,
    content_score: 9.50,
    tech_stack: 'React, Next.js, Contentful',
    agency_name: 'In-house',
    country: 'United States',
    date_awarded: '2024-01-28',
    description: 'Outdoor brand merging activism with commerce through documentary storytelling and impact reports.',
  },
  {
    url: 'https://www.deloitte.com',
    site_name: 'Deloitte',
    archetype_category: 'corporate',
    design_score: 8.50,
    usability_score: 8.90,
    creativity_score: 8.30,
    content_score: 9.00,
    tech_stack: 'React, Adobe Experience Manager',
    agency_name: 'In-house',
    country: 'United Kingdom',
    date_awarded: '2023-10-08',
    description: 'Professional services firm with insight-led content architecture and industry navigator tools.',
  },
];

// ---------------------------------------------------------------------------
// Main execution
// ---------------------------------------------------------------------------

async function main() {
  const isDryRun = process.argv.includes('--dry-run');

  console.log('=== Awwwards Curated Design Reference Seeder ===');
  console.log(`Total references: ${CURATED_REFERENCES.length}`);
  console.log(`Dry run: ${isDryRun}\n`);

  // Print archetype breakdown
  const archetypeCounts = {};
  for (const ref of CURATED_REFERENCES) {
    archetypeCounts[ref.archetype_category] = (archetypeCounts[ref.archetype_category] || 0) + 1;
  }
  console.log('Archetype breakdown:');
  for (const [archetype, count] of Object.entries(archetypeCounts).sort()) {
    console.log(`  ${archetype}: ${count}`);
  }
  console.log('');

  if (isDryRun) {
    console.log('--- DRY RUN: Printing first 3 entries per archetype ---\n');
    const seen = {};
    for (const ref of CURATED_REFERENCES) {
      if (!seen[ref.archetype_category]) seen[ref.archetype_category] = 0;
      if (seen[ref.archetype_category] < 3) {
        console.log(`[${ref.archetype_category}] ${ref.site_name} (${ref.url})`);
        console.log(`  Scores: D=${ref.design_score} U=${ref.usability_score} C=${ref.creativity_score} Co=${ref.content_score}`);
        console.log(`  Agency: ${ref.agency_name} | Country: ${ref.country} | Tech: ${ref.tech_stack}`);
        console.log('');
        seen[ref.archetype_category]++;
      }
    }
    console.log('Dry run complete. No data was inserted.');
    return;
  }

  // Dynamic import of the service to allow --dry-run without Supabase credentials
  const { bulkInsertReferences } = await import('../../../lib/eva/services/design-reference-library.js');

  console.log('Connecting to Supabase and inserting references...');
  try {
    const inserted = await bulkInsertReferences(CURATED_REFERENCES);
    console.log(`Successfully upserted ${inserted.length} design references.`);
  } catch (err) {
    console.error(`Failed to insert references: ${err.message}`);
    process.exit(1);
  }
}

// Only auto-execute when run directly (not when imported as a module in tests)
const isDirectRun =
  import.meta.url === `file://${process.argv[1]}` ||
  import.meta.url === `file:///${process.argv[1].replace(/\\/g, '/')}`;

if (isDirectRun) {
  main();
}
