/**
 * SRIP Synthesis Engine Module
 * SD: SD-MAN-ORCH-SRIP-CLONER-INTEGRATION-001-C
 *
 * Stage 3 of the SRIP pipeline: Synthesis
 * Merges Site DNA structure with Brand Interview identity into a comprehensive
 * one-shot replication prompt.
 *
 * Input: siteDnaId + brandInterviewId
 * Output: Synthesis prompt stored in srip_synthesis_prompts table
 */

import { createSupabaseServiceClient } from '../../../lib/supabase-client.js';
import dotenv from 'dotenv';

dotenv.config();

// ============================================================================
// Prompt Section Builders
// ============================================================================

/**
 * Build the DESIGN_SYSTEM section from DNA design tokens + brand colors/typography.
 */
function buildDesignSystemSection(dnaJson, brandAnswers) {
  const tokens = dnaJson.design_tokens || {};
  const colors = tokens.colors || {};
  const typography = tokens.typography || {};

  const section = {
    title: 'DESIGN_SYSTEM',
    instructions: 'Apply these design tokens as the foundation for all visual styling.',
    colors: {
      primary: brandAnswers.color_primary || colors.primary || '#000000',
      secondary: brandAnswers.color_secondary || colors.secondary || '#666666',
      accent: colors.accent || null,
      background: colors.background || '#ffffff',
      text: colors.text || '#333333',
      additional: colors.additional || [],
    },
    typography: {
      font_family: brandAnswers.typography_preference || typography.font_family || 'system-ui, sans-serif',
      heading_font: typography.heading_font || null,
      size_scale: typography.size_scale || ['14px', '16px', '20px', '24px', '32px', '48px'],
      weights: typography.weights || [400, 600, 700],
      line_heights: typography.line_heights || [1.2, 1.5, 1.6],
    },
    spacing: tokens.spacing || ['4px', '8px', '16px', '24px', '32px', '48px'],
    border_radius: tokens.border_radius || ['4px', '8px'],
    shadows: tokens.shadows || [],
  };

  return section;
}

/**
 * Build the LAYOUT section from DNA macro architecture + section blueprints.
 */
function buildLayoutSection(dnaJson, brandAnswers) {
  const macro = dnaJson.macro_architecture || {};
  const blueprints = dnaJson.section_blueprints || {};

  const section = {
    title: 'LAYOUT',
    instructions: 'Replicate this page structure and layout pattern.',
    grid_system: macro.grid_system || 'flexbox',
    responsive_approach: macro.responsive_approach || 'mobile-first',
    page_flow: macro.page_flow || 'single-column',
    layout_style: brandAnswers.layout_style || 'minimal',
    content_density: brandAnswers.content_density || 'moderate',
    sections: macro.sections || [],
    blueprints: blueprints.blueprints || [],
  };

  return section;
}

/**
 * Build the COMPONENTS section from DNA component behaviors.
 */
function buildComponentsSection(dnaJson, brandAnswers) {
  const behaviors = dnaJson.component_behaviors || {};

  const section = {
    title: 'COMPONENTS',
    instructions: 'Implement these interactive components with the specified visual patterns.',
    call_to_action_style: brandAnswers.call_to_action_style || 'bold buttons',
    components: behaviors.components || [],
  };

  return section;
}

/**
 * Build the BRAND_VOICE section from brand interview answers.
 */
function buildBrandVoiceSection(brandAnswers) {
  const section = {
    title: 'BRAND_VOICE',
    instructions: 'Apply this brand identity to all content and visual elements.',
    brand_name: brandAnswers.brand_name || 'Unnamed Brand',
    tagline: brandAnswers.tagline || null,
    tone_of_voice: brandAnswers.tone_of_voice || 'professional',
    target_audience: brandAnswers.target_audience || null,
    imagery_style: brandAnswers.imagery_style || 'photography',
    competitive_positioning: brandAnswers.competitive_positioning || null,
  };

  return section;
}

/**
 * Build the TECHNICAL section from DNA tech stack detection.
 */
function buildTechnicalSection(dnaJson) {
  const techStack = dnaJson.tech_stack || {};

  const section = {
    title: 'TECHNICAL',
    instructions: 'Use this technical approach for the implementation.',
    framework: techStack.framework || 'React',
    css_approach: techStack.css_approach || 'Tailwind',
    build_tool: techStack.build_tool || 'Vite',
    key_libraries: techStack.key_libraries || [],
    rendering: techStack.rendering || 'CSR',
  };

  return section;
}

// ============================================================================
// Prompt Assembly
// ============================================================================

/**
 * Assemble the full synthesis prompt text from all sections.
 */
function assemblePromptText(sections) {
  const lines = [
    '# SITE REPLICATION PROMPT',
    '# Generated by SRIP Synthesis Engine',
    `# Generated at: ${new Date().toISOString()}`,
    '',
    'Replicate the reference site using the specifications below.',
    'Each section provides constraints and design decisions to follow precisely.',
    '',
  ];

  for (const section of sections) {
    lines.push(`## ${section.title}`);
    lines.push(`> ${section.instructions}`);
    lines.push('');

    // Serialize section data (excluding title and instructions)
    const data = { ...section };
    delete data.title;
    delete data.instructions;

    for (const [key, value] of Object.entries(data)) {
      if (value === null || value === undefined) continue;

      if (Array.isArray(value)) {
        if (value.length === 0) continue;
        lines.push(`### ${key.replace(/_/g, ' ').toUpperCase()}`);
        if (typeof value[0] === 'object') {
          for (const item of value) {
            const itemStr = Object.entries(item)
              .map(([k, v]) => `${k}: ${typeof v === 'object' ? JSON.stringify(v) : v}`)
              .join(' | ');
            lines.push(`- ${itemStr}`);
          }
        } else {
          lines.push(value.map(v => `- ${v}`).join('\n'));
        }
        lines.push('');
      } else if (typeof value === 'object') {
        lines.push(`### ${key.replace(/_/g, ' ').toUpperCase()}`);
        for (const [subKey, subVal] of Object.entries(value)) {
          if (subVal === null || subVal === undefined) continue;
          if (Array.isArray(subVal)) {
            lines.push(`- ${subKey}: ${subVal.join(', ')}`);
          } else {
            lines.push(`- ${subKey}: ${subVal}`);
          }
        }
        lines.push('');
      } else {
        lines.push(`- **${key.replace(/_/g, ' ')}**: ${value}`);
      }
    }

    lines.push('---');
    lines.push('');
  }

  return lines.join('\n');
}

// ============================================================================
// Main Entry Point
// ============================================================================

/**
 * Generate a synthesis prompt from Site DNA + Brand Interview data.
 *
 * @param {object} params
 * @param {string} params.siteDnaId - UUID of the srip_site_dna record
 * @param {string} params.brandInterviewId - UUID of the srip_brand_interviews record
 * @param {object} [params.supabase] - Optional Supabase client
 * @returns {object|null} The stored synthesis prompt record, or null on failure
 */
export async function generateSynthesisPrompt({ siteDnaId, brandInterviewId, supabase }) {
  if (!supabase) {
    supabase = createSupabaseServiceClient();
  }

  console.log('\n   Synthesis Engine');
  console.log(`   Site DNA: ${siteDnaId}`);
  console.log(`   Brand Interview: ${brandInterviewId}`);

  // Load Site DNA
  const { data: siteDna, error: dnaError } = await supabase
    .from('srip_site_dna')
    .select('id, venture_id, dna_json, reference_url, quality_score')
    .eq('id', siteDnaId)
    .single();

  if (dnaError || !siteDna) {
    console.error(`   Site DNA not found: ${dnaError?.message || 'no data'}`);
    return null;
  }

  // Load Brand Interview
  const { data: interview, error: interviewError } = await supabase
    .from('srip_brand_interviews')
    .select('id, venture_id, answers, pre_populated_count, manual_input_count, status')
    .eq('id', brandInterviewId)
    .single();

  if (interviewError || !interview) {
    console.error(`   Brand interview not found: ${interviewError?.message || 'no data'}`);
    return null;
  }

  const dnaJson = siteDna.dna_json || {};
  const brandAnswers = interview.answers || {};

  console.log(`   DNA quality: ${siteDna.quality_score || 'N/A'}/100`);
  console.log(`   Brand completeness: ${interview.pre_populated_count}/${interview.pre_populated_count + interview.manual_input_count} answered`);

  // Build prompt sections
  const sections = [
    buildDesignSystemSection(dnaJson, brandAnswers),
    buildLayoutSection(dnaJson, brandAnswers),
    buildComponentsSection(dnaJson, brandAnswers),
    buildBrandVoiceSection(brandAnswers),
    buildTechnicalSection(dnaJson),
  ];

  // Assemble full prompt text
  const promptText = assemblePromptText(sections);

  // Estimate token count (rough: ~4 chars per token)
  const tokenCount = Math.ceil(promptText.length / 4);

  // Calculate fidelity target based on data completeness
  const dnaStepCount = Object.keys(dnaJson).filter(k => !dnaJson[k]?.error).length;
  const answeredCount = Object.values(brandAnswers).filter(v => v != null).length;
  const totalInputs = 6 + 12; // 6 DNA steps + 12 brand questions
  const fidelityTarget = Math.round(((dnaStepCount + answeredCount) / totalInputs) * 100);

  console.log(`\n   Prompt length: ${promptText.length} chars (~${tokenCount} tokens)`);
  console.log(`   Fidelity target: ${fidelityTarget}%`);
  console.log(`   Sections: ${sections.map(s => s.title).join(', ')}`);

  // Store in database
  const promptRecord = {
    venture_id: siteDna.venture_id || interview.venture_id || null,
    site_dna_id: siteDnaId,
    brand_interview_id: brandInterviewId,
    prompt_text: promptText,
    fidelity_target: fidelityTarget,
    version: 1,
    token_count: tokenCount,
    status: 'active',
    created_by: 'SRIP_SYNTHESIS_ENGINE',
  };

  const { data, error } = await supabase
    .from('srip_synthesis_prompts')
    .insert(promptRecord)
    .select('id, version, token_count, fidelity_target, status');

  if (error) {
    console.error(`   DB insert failed: ${error.message}`);
    return null;
  }

  const result = data[0];
  console.log(`\n   Synthesis prompt stored: ${result.id}`);
  console.log(`   Version: ${result.version} | Tokens: ${result.token_count} | Fidelity: ${result.fidelity_target}%`);

  return result;
}

// Export section builders for testing
export {
  buildDesignSystemSection,
  buildLayoutSection,
  buildComponentsSection,
  buildBrandVoiceSection,
  buildTechnicalSection,
  assemblePromptText,
};
