/**
 * Placeholder Content Detection Gate for LEAD-TO-PLAN
 * SD-LEO-INFRA-PROTOCOL-FILE-STATE-001
 *
 * Warns when SD fields contain only default template text from leo-create-sd.js.
 * These placeholders pass validation gates but carry zero real information,
 * wasting the LEAD review phase.
 *
 * This gate issues WARNINGS only (does not block handoff).
 *
 * SD-LEO-INFRA-STRUCTURED-FIELDS-HONEST-001 / FR-4: this gate is named for the filler defect and
 * COULD NOT FIRE ON IT. It inspected only the LABEL keys (`change`, `criterion`) while the filler
 * lives in the VALUE keys (`impact`, `measure`), and none of the three filler constants appeared in
 * any pattern list repo-wide — so a row reading {criterion: <real>, measure: 'See description for
 * details'} scored as a CUSTOM entry. 1,442 SDs / 7,683 entries accumulated underneath it.
 *
 * Value-side inspection is added below and the verdict is now COMPUTED and EXPOSED as
 * `placeholder_free`. `pass` is deliberately left `true` — see the return statement for why that
 * restraint is intentional rather than incomplete.
 */

// FR-4: shared classifier so the gate and the FR-3 detector cannot drift apart on what counts as
// filler. Exact-equality lives in one place.
import { classifyEntry, VALUE_KEY_BY_FIELD } from '../../../../../../lib/sd-fields/unpopulated.js';

/**
 * Known placeholder patterns generated by buildDefaultStrategicObjectives(),
 * buildDefaultKeyChanges(), and buildDefaultSuccessCriteria() in leo-create-sd.js.
 *
 * Each pattern is a regex that matches the template text regardless of the
 * SD title interpolated into it.
 */
const PLACEHOLDER_PATTERNS = [
  // From buildDefaultStrategicObjectives()
  /^Implement .+ as specified in the SD scope$/,
  /^Maintain backward compatibility with existing functionality$/,
  /^Deliver user-facing value with clear acceptance criteria$/,
  /^Ensure comprehensive test coverage for new functionality$/,
  /^Address root cause to prevent recurrence$/,
  /^Improve code quality without changing external behavior$/,
  /^Eliminate identified security vulnerabilities$/,

  // From buildDefaultKeyChanges()
  /^Implement core changes for: .+$/,
  /^Add UI components or API endpoints as required$/,
  /^Add tests for new functionality$/,
  /^Update documentation for new feature$/,
  /^Fix identified defect and add regression test$/,
  /^Update related documentation if needed$/,
  /^Update infrastructure components$/,
  /^Verify deployment and operational readiness$/,
  /^Restructure code while preserving behavior$/,
  /^Add or update tests to verify no regressions$/,

  // From buildDefaultSuccessCriteria()
  /^All implementation items from scope are complete$/,
  /^Code passes lint and type checks$/,
  /^PR reviewed and approved$/,
  /^Root cause addressed, not just symptoms$/,
  /^Feature accessible to target users$/,
];

/**
 * Check if a string matches any known placeholder pattern.
 * @param {string} text - Text to check
 * @returns {boolean} True if the text matches a placeholder pattern
 */
export function isPlaceholderText(text) {
  if (!text || typeof text !== 'string') return false;
  const trimmed = text.trim();
  return PLACEHOLDER_PATTERNS.some(pattern => pattern.test(trimmed));
}

/**
 * Analyze an array field for placeholder content.
 * Returns the count and percentage of placeholder entries.
 *
 * @param {Array} items - Array of strings or objects with string values
 * @param {string} [textKey] - If items are objects, the key to check (e.g., 'change')
 * @returns {{ total: number, placeholders: number, percentage: number }}
 */
export function analyzePlaceholderContent(items, textKey) {
  if (!Array.isArray(items) || items.length === 0) {
    return { total: 0, placeholders: 0, percentage: 0 };
  }

  let total = 0;
  let placeholders = 0;

  for (const item of items) {
    const text = textKey && typeof item === 'object' ? item[textKey] : item;
    if (typeof text === 'string') {
      total++;
      if (isPlaceholderText(text)) {
        placeholders++;
      }
    }
  }

  return {
    total,
    placeholders,
    percentage: total > 0 ? Math.round((placeholders / total) * 100) : 0
  };
}

/**
 * Validate SD fields for placeholder content.
 *
 * Checks:
 * - strategic_objectives for template defaults
 * - key_changes for template defaults
 * - success_criteria for template defaults
 * - description for very short or generic text
 *
 * @param {Object} sd - Strategic Directive
 * @returns {Object} Validation result with warnings
 */
export async function validatePlaceholderContent(sd) {
  const warnings = [];
  let score = 100;

  console.log('   Checking for placeholder/template content...');

  // Check strategic_objectives
  const objectives = sd.strategic_objectives || [];
  const objAnalysis = analyzePlaceholderContent(objectives);
  if (objAnalysis.placeholders > 0) {
    const msg = `strategic_objectives: ${objAnalysis.placeholders}/${objAnalysis.total} entries are default templates (${objAnalysis.percentage}%)`;
    warnings.push(msg);
    console.log(`   ⚠️  ${msg}`);
    score -= objAnalysis.percentage >= 100 ? 30 : 15;
  } else if (objAnalysis.total > 0) {
    console.log(`   ✅ strategic_objectives: ${objAnalysis.total} custom entries`);
  }

  // Check key_changes (may be objects with 'change' key)
  const changes = sd.key_changes || [];
  const changeAnalysis = analyzePlaceholderContent(changes, 'change');
  if (changeAnalysis.placeholders > 0) {
    const msg = `key_changes: ${changeAnalysis.placeholders}/${changeAnalysis.total} entries are default templates (${changeAnalysis.percentage}%)`;
    warnings.push(msg);
    console.log(`   ⚠️  ${msg}`);
    score -= changeAnalysis.percentage >= 100 ? 30 : 15;
  } else if (changeAnalysis.total > 0) {
    console.log(`   ✅ key_changes: ${changeAnalysis.total} custom entries`);
  }

  // Check success_criteria
  const criteria = sd.success_criteria || [];
  // SD-LEO-ORCH-CAPA-RECORD-TRUTH-002-A / TR-1: textKey MUST be 'criterion' -- without it, the
  // common {criterion, measure} object shape silently reports 0 placeholders (item[textKey] is
  // never consulted for a string-typed item, so plain-string entries are unaffected by this change).
  const criteriaAnalysis = analyzePlaceholderContent(criteria, 'criterion');
  if (criteriaAnalysis.placeholders > 0) {
    const msg = `success_criteria: ${criteriaAnalysis.placeholders}/${criteriaAnalysis.total} entries are default templates (${criteriaAnalysis.percentage}%)`;
    warnings.push(msg);
    console.log(`   ⚠️  ${msg}`);
    score -= criteriaAnalysis.percentage >= 100 ? 20 : 10;
  } else if (criteriaAnalysis.total > 0) {
    console.log(`   ✅ success_criteria: ${criteriaAnalysis.total} custom entries`);
  }

  // SD-LEO-INFRA-STRUCTURED-FIELDS-HONEST-001 / FR-4 — INSPECT THE VALUE SIDE.
  //
  // THIS GATE IS NAMED FOR THIS DEFECT AND COULD NOT FIRE ON IT. Every check above reads the LABEL
  // key — `change` for key_changes, the string/`criterion` form for success_criteria — while the
  // filler lives in the VALUE key: `measure` and `impact`. So a row reading
  // {criterion: <real title>, measure: 'See description for details'} scored as a CUSTOM entry.
  // None of the three filler constants appeared in any pattern list repo-wide. Measured
  // consequence: 1,442 SDs / 7,683 filler entries accumulated underneath a gate written to catch
  // exactly them. The analyzer already accepted a key argument — it was simply never called with
  // the one that mattered.
  //
  // Exact-equality via the shared classifier, never substring: a substring detector flags rows that
  // DESCRIBE the phrase as rows that HAVE it (measured: 1,097 vs 1,096, the delta being a row
  // documenting this very defect).
  const valueSideFindings = [];
  for (const [field, valueKey] of Object.entries(VALUE_KEY_BY_FIELD)) {
    const arr = sd[field];
    if (!Array.isArray(arr) || arr.length === 0) continue;
    let filler = 0; let unpopulated = 0;
    for (const entry of arr) {
      const verdict = classifyEntry(entry, valueKey);
      if (verdict === 'legacy_filler') filler++;
      else if (verdict === 'unpopulated') unpopulated++;
    }
    if (filler > 0) {
      const msg = `${field}.${valueKey}: ${filler}/${arr.length} entries are generator FILLER (reads like content, means nothing)`;
      warnings.push(msg);
      console.log(`   ⚠️  ${msg}`);
      valueSideFindings.push({ field, valueKey, filler, unpopulated });
      score -= filler === arr.length ? 20 : 10;
    } else if (unpopulated > 0) {
      // Acknowledged-empty is HONEST, not a defect. Reported for visibility, no penalty —
      // penalising it would push authors back toward filler, which is the opposite of the point.
      const msg = `${field}.${valueKey}: ${unpopulated}/${arr.length} entries explicitly UNPOPULATED (honest, not filler)`;
      warnings.push(msg);
      console.log(`   ℹ️  ${msg}`);
      valueSideFindings.push({ field, valueKey, filler: 0, unpopulated });
    }
  }
  const valueSideFiller = valueSideFindings.reduce((n, f) => n + f.filler, 0);

  // Check description length (very short descriptions are likely placeholders)
  const desc = sd.description || '';
  if (desc.length > 0 && desc.length < 50) {
    warnings.push(`description is very short (${desc.length} chars) - consider adding detail`);
    console.log(`   ⚠️  description is very short (${desc.length} chars)`);
    score -= 10;
  } else if (desc.length > 0) {
    console.log(`   ✅ description has substance (${desc.length} chars)`);
  }

  const totalPlaceholders = objAnalysis.placeholders + changeAnalysis.placeholders + criteriaAnalysis.placeholders + valueSideFiller;
  if (totalPlaceholders === 0) {
    console.log('   ✅ No placeholder content detected');
  } else {
    console.log(`\n   ⚠️  ${totalPlaceholders} placeholder(s) found - consider enriching SD before PLAN phase`);
  }

  // SD-LEO-ORCH-CAPA-RECORD-TRUTH-002-A / FR-1+FR-2 — THE FLIP, NARROWLY SCOPED.
  //
  // SD-LEO-INFRA-STRUCTURED-FIELDS-HONEST-001 left `pass` hardcoded true because a blanket flip
  // (any filler anywhere) would have failed 1,442 existing SDs on day one with no sequencing plan.
  // This SD carries a coordinator ruling to flip `pass` AND `required` together, but ONLY for a
  // narrow trigger: success_criteria[].criterion is 100% template text (measured: 852/4,779
  // completed SDs, 17.8%). That predicate is deliberately UNRELATED to value_side_filler,
  // objectives, or key_changes — a single non-template success_criteria entry, however much filler
  // surrounds it, does not block. See FR-2 in the PRD for why 100% (not "any") is the boundary.
  const criteriaIsFullyTemplate = criteriaAnalysis.total > 0 && criteriaAnalysis.percentage === 100;
  const blockingIssues = [];
  if (criteriaIsFullyTemplate) {
    // FR-3: name every offending entry and state a concrete remedy. A blocking gate whose message
    // is vague is the exact "steers the operator into the broken path" defect this SD exists to
    // close — the message must let the operator fix it without re-deriving what "template" means.
    const offending = [];
    criteria.forEach((item, index) => {
      const text = typeof item === 'object' && item !== null ? item.criterion : item;
      if (typeof text === 'string' && isPlaceholderText(text)) {
        offending.push({ index, text: text.trim() });
      }
    });
    const named = offending.map((o) => `#${o.index} "${o.text}"`).join(', ');
    blockingIssues.push(
      `success_criteria is 100% template text (${offending.length}/${criteria.length}): ${named}. ` +
      'Replace each with a measurable, SD-specific exit condition tied to this SD\'s actual scope ' +
      '(e.g. a concrete assertion an operator can verify) — not generic boilerplate like ' +
      `"${offending[0]?.text}".`
    );
  }

  return {
    pass: !criteriaIsFullyTemplate, // FR-1: false ONLY when success_criteria is 100% template.
    placeholder_free: totalPlaceholders === 0,
    placeholders_found: totalPlaceholders,
    value_side_filler: valueSideFiller, // FR-4: disclosure only — never affects pass.
    score: Math.max(score, 50),
    max_score: 100,
    issues: blockingIssues,
    warnings
  };
}

/**
 * Create the placeholder content detection gate.
 *
 * @returns {Object} Gate configuration
 */
export function createPlaceholderContentGate() {
  return {
    name: 'GATE_PLACEHOLDER_CONTENT_DETECTION',
    validator: async (ctx) => {
      console.log('\n📝 GATE: Placeholder Content Detection');
      console.log('-'.repeat(50));
      return validatePlaceholderContent(ctx.sd);
    },
    // SD-LEO-ORCH-CAPA-RECORD-TRUTH-002-A / FR-1: required:true, but the gate only ever returns
    // pass:false for the narrow 100%-template-success_criteria trigger above -- every other finding
    // (objectives, key_changes, value-side filler, <100% success_criteria) stays warning-only.
    required: true,
    remediation: 'Enrich SD fields with specific, actionable content before proceeding to PLAN phase. Replace template text in strategic_objectives, key_changes, and success_criteria with real requirements. See the blocking issue (when present) for which success_criteria entries specifically need rewriting.'
  };
}
