/**
 * EXEC SECURITY — SD-LEO-INFRA-SCHEDULED-WORKTREE-REAPER-001. Layer 2 on BOTH stage-2 routes.
 *
 * MY CLAIM WAS OVERSTATED. The S1 commit said the source tree was protected by "TWO layers, both
 * mutation-proved INDEPENDENTLY". Measured: layer 2 had ONE call site, inside hasOrphanSD. `idle`
 * is also a stage-2 removal category and never consulted it, so the idle route had ONE layer (the
 * marker), not two. Never unprotected — the marker gate at worktree-reaper.mjs:1371 is a
 * pre-classification chokepoint — but the "two layers" claim was false for that route.
 *
 * THIS FILE THEN RE-COMMITTED THE VACUITY CLASS IT WAS WRITTEN TO FIX, and the reviewer measured
 * it: three of its cases were GENERATED by iterating SOURCE_TREE_DIRNAMES, so emptying that
 * constant — i.e. DELETING the protection entirely — took the suite from 6 tests to 4. Two cases
 * VANISHED rather than failed, and a loop-bodied case PASSED having executed ZERO assertions.
 * A suite that shrinks when the thing it guards is deleted is worse than no suite.
 *
 * SO: every case below is driven by HARDCODED LITERALS, and SOURCE_TREE_DIRNAMES is the SUBJECT of
 * an assertion rather than the SOURCE of the cases. Production data never decides how many tests
 * run.
 */
import { describe, it, expect } from 'vitest';
import path from 'node:path';
import {
  isIdle, hasOrphanSD, isSourceTreeBasename, SOURCE_TREE_DIRNAMES,
} from '../../../lib/worktree-reaper/detectors.js';

// HARDCODED, deliberately duplicating the production constant rather than importing it as the
// loop source. If someone deletes an entry from the constant, these cases still RUN and turn RED.
const REAPER_SRC = '.reaper-source';
const SPAWN_SRC = '.spawn-source';

const POOL = path.join('C:', 'pool', '.worktrees');
const wtAt = (name) => ({ path: path.join(POOL, name), branch: 'whatever' });

// Old enough to be idle by any threshold, with no claim: the worst case for a source tree.
const idleCtx = {
  now: Date.parse('2026-08-08T12:00:00Z'),
  thresholdMs: 24 * 3600 * 1000,
  claimMap: new Map(),
  runGit: () => ({ code: 0, stdout: '1000000000' }), // last commit in 2001
};
const orphanCtx = { activeSdSet: new Set(), claimMap: new Map() };
const orphanOf = (name) => hasOrphanSD({ ...wtAt(name), key: name }, orphanCtx);

describe('the constant itself is the SUBJECT of an assertion, not the source of the cases', () => {
  it('SOURCE_TREE_DIRNAMES contains exactly the two names, and is non-empty', () => {
    // The anti-vacuity anchor. Emptying or trimming the constant fails HERE, loudly, instead of
    // silently removing test cases elsewhere.
    expect(SOURCE_TREE_DIRNAMES.length).toBeGreaterThan(0);
    expect([...SOURCE_TREE_DIRNAMES].sort()).toEqual([REAPER_SRC, SPAWN_SRC].sort());
  });

  it('the predicate is EXACT, not prefix — IDLE-2', () => {
    // The bug this replaced: the constant was spread into a startsWith list while isIdle used
    // includes, so ONE name got TWO answers. `.reaper-source-2` is not a source tree.
    expect(isSourceTreeBasename(REAPER_SRC)).toBe(true);
    expect(isSourceTreeBasename(SPAWN_SRC)).toBe(true);
    expect(isSourceTreeBasename('.reaper-source-2')).toBe(false);
    expect(isSourceTreeBasename('reaper-source')).toBe(false);
    expect(isSourceTreeBasename('')).toBe(false);
    expect(isSourceTreeBasename(undefined)).toBe(false);
  });
});

describe('BOTH stage-2 routes refuse the source trees, and agree with each other', () => {
  it(`isIdle REFUSES ${REAPER_SRC}`, () => {
    const r = isIdle(wtAt(REAPER_SRC), idleCtx);
    expect(r.matched).toBe(false);
    expect(r.reason).toBe('source_tree_protected');
  });

  it(`isIdle REFUSES ${SPAWN_SRC}`, () => {
    const r = isIdle(wtAt(SPAWN_SRC), idleCtx);
    expect(r.matched).toBe(false);
    expect(r.reason).toBe('source_tree_protected');
  });

  it(`hasOrphanSD REFUSES ${REAPER_SRC} — and by the SOURCE-TREE rule, not by fail-closed`, () => {
    // The reason is the discriminator. matched:false alone is reachable by several paths
    // (fail-closed, prefix list), so asserting only the boolean cannot tell which rule fired —
    // the exact vacuity this SD already committed once.
    const r = orphanOf(REAPER_SRC);
    expect(r.matched).toBe(false);
    expect(r.reason).toBe('source_tree_protected');
  });

  it(`hasOrphanSD REFUSES ${SPAWN_SRC} — and by the SOURCE-TREE rule, not by fail-closed`, () => {
    const r = orphanOf(SPAWN_SRC);
    expect(r.matched).toBe(false);
    expect(r.reason).toBe('source_tree_protected');
  });

  it('IDLE-2-R: a spoofed wt.key cannot make the two routes disagree', () => {
    // hasOrphanSD reads `wt.key || basename` while isIdle reads the basename. With a stale or
    // spoofed key on a directory that IS a source tree, the orphan route reaped while the idle
    // route protected. Not reachable from the production caller (which sets key=basename), so
    // "both routes agree" was true by caller CONVENTION rather than by construction — the same
    // shape as the claim IDLE-2 retracted. Protection is about WHERE the tree is; wt.key is a
    // claim about WHICH SD it belongs to.
    const wt = { ...wtAt(REAPER_SRC), key: 'SD-GONE-999' };
    const r = hasOrphanSD(wt, orphanCtx);
    expect(r.matched).toBe(false);
    expect(r.reason).toBe('source_tree_protected');
  });

  it('the two routes AGREE on a near-miss name — IDLE-2 regression pin', () => {
    // `.reaper-source-2` previously split: protected on orphan-sd (startsWith), reapable on idle
    // (exact). One name must get ONE answer from both classifiers.
    const near = '.reaper-source-2';
    expect(isIdle(wtAt(near), idleCtx).reason).not.toBe('source_tree_protected');
    expect(orphanOf(near).reason).not.toBe('source_tree_protected');
  });
});

describe('scope: the fix must not make ordinary worktrees immortal', () => {
  // Hardcoded, and each asserted individually so a shrinking list cannot hide a case.
  for (const name of ['qf-20260101-001', 'adhoc-thing', 'session-abc', '_archive-old']) {
    it(`${name} stays REAPABLE via the idle route`, () => {
      // NON_SD_PREFIXES means "this basename is not an SD key" — a statement about orphan-SD
      // detection, NOT about reapability. Blanket-applying it to isIdle would make these immortal,
      // a larger regression than the bug being fixed.
      expect(isIdle(wtAt(name), idleCtx).matched).toBe(true);
    });
  }

  it('POSITIVE CONTROL — an ordinary stale worktree IS still idle', () => {
    // Without this, an isIdle returning matched:false unconditionally would satisfy every refusal
    // assertion above while disabling idle reaping entirely.
    expect(isIdle(wtAt('SD-SOME-REAL-WORK-001'), idleCtx).matched).toBe(true);
  });
});
