/**
 * Tests for deliverables-completeness.js — QF-20260524-729 (feedback 53426445).
 *
 * Focus: an auto-inserted SYSTEM scaffold deliverable that stays incomplete after
 * evidence reconciliation must NOT block the EXEC-TO-PLAN gate, while a real
 * (non-SYSTEM) incomplete deliverable still must. Uses the real (pure)
 * semantic-gate-utils; only supabase is mocked.
 */
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { createDeliverablesCompletenessGate } from './deliverables-completeness.js';

// Routed mock: sd_scope_deliverables resolves the configured rows (and accepts
// reconcile UPDATEs); product_requirements_v2 / sd_phase_handoffs resolve empty
// so reconcileDeliverables finds NO evidence (the "no mapped work" condition).
function makeSupabase({ deliverables = [], prd = null, handoffs = [] }) {
  const updates = [];
  function chain(table) {
    const c = {
      _update: null,
      select() { return c; },
      eq() { return c; },
      update(p) { c._update = p; updates.push({ table, payload: p }); return c; },
      maybeSingle() { return Promise.resolve({ data: table === 'product_requirements_v2' ? prd : null, error: null }); },
      single() { return Promise.resolve({ data: table === 'product_requirements_v2' ? prd : null, error: null }); },
      then(resolve) {
        if (c._update) return Promise.resolve({ data: null, error: null }).then(resolve);
        if (table === 'sd_scope_deliverables') return Promise.resolve({ data: deliverables, error: null }).then(resolve);
        if (table === 'sd_phase_handoffs') return Promise.resolve({ data: handoffs, error: null }).then(resolve);
        return Promise.resolve({ data: null, error: null }).then(resolve);
      },
    };
    return c;
  }
  return { from: (t) => chain(t), _updates: updates };
}

const ctx = { sd: { id: 'sd-x', sd_type: 'feature' }, sdId: 'sd-x' }; // feature → REQ (blocking)

describe('DELIVERABLES_COMPLETENESS — QF-20260524-729 unmapped SYSTEM boilerplate', () => {
  beforeEach(() => { vi.spyOn(console, 'log').mockImplementation(() => {}); });

  it('PASSES when the only incomplete deliverables are unmapped SYSTEM scaffolding', async () => {
    const supabase = makeSupabase({ deliverables: [
      { id: '1', deliverable_name: 'Implement core widget', completion_status: 'completed', created_by: 'EXEC' },
      { id: '2', deliverable_name: 'Development environment setup', completion_status: 'pending', created_by: 'SYSTEM' },
      { id: '3', deliverable_name: 'Documentation updated', completion_status: 'pending', created_by: 'SYSTEM' },
    ] });
    const result = await createDeliverablesCompletenessGate(supabase).validator(ctx);
    expect(result.passed).toBe(true);
    expect(result.details.completed).toBe(1);
    // The 2 SYSTEM rows are counted as advisory (excluded), not scored as real work.
    expect(result.details.autoGenerated).toBe(2);
    expect(supabase._updates).toHaveLength(0); // no evidence → not force-completed in the DB
  });

  it('STILL FAILS when a real (non-SYSTEM) deliverable is incomplete (gate integrity)', async () => {
    const supabase = makeSupabase({ deliverables: [
      { id: '1', deliverable_name: 'Implement core widget', completion_status: 'completed', created_by: 'EXEC' },
      { id: '2', deliverable_name: 'Custom widget behavior', completion_status: 'pending', created_by: 'EXEC' },
    ] });
    const result = await createDeliverablesCompletenessGate(supabase).validator(ctx);
    expect(result.passed).toBe(false);
    expect(result.issues.length).toBeGreaterThan(0);
  });

  it('PASSES (vacuously) when every deliverable is unmapped SYSTEM scaffolding — effectiveTotal 0', async () => {
    const supabase = makeSupabase({ deliverables: [
      { id: '1', deliverable_name: 'Development environment setup', completion_status: 'pending', created_by: 'SYSTEM' },
      { id: '2', deliverable_name: 'Documentation updated', completion_status: 'pending', created_by: 'SYSTEM' },
    ] });
    const result = await createDeliverablesCompletenessGate(supabase).validator(ctx);
    expect(result.passed).toBe(true);
    expect(result.score).toBe(100);
  });

  it('counts COMPLETED SYSTEM deliverables normally (only incomplete ones are skipped)', async () => {
    const supabase = makeSupabase({ deliverables: [
      { id: '1', deliverable_name: 'Development environment setup', completion_status: 'completed', created_by: 'SYSTEM' },
      { id: '2', deliverable_name: 'Documentation updated', completion_status: 'completed', created_by: 'SYSTEM' },
      { id: '3', deliverable_name: 'Repo initialized', completion_status: 'completed', created_by: 'SYSTEM' },
    ] });
    const result = await createDeliverablesCompletenessGate(supabase).validator(ctx);
    expect(result.passed).toBe(true);
    expect(result.details.completed).toBe(3);
    expect(result.details.autoGenerated).toBe(0); // none skipped — they're done
  });
});
