#!/bin/bash

# SD Script Migration Commands
# Generated by migrate-sd-scripts.js
# Run these commands to replace SD-specific scripts with template calls

echo "🔄 Migrating SD-specific scripts to template system..."
echo "======================================================="

# HANDOFF SCRIPTS
echo "📋 Migrating handoff scripts..."
echo "Replacing create-lead-plan-handoff-sd028.js..."
# node templates/create-handoff.js LEAD PLAN SD028
echo "Replacing create-plan-exec-handoff-sd008.js..."
# node templates/create-handoff.js PLAN EXEC SD008
echo "Replacing sd003-lead-plan-handoff.js..."
# node templates/create-handoff.js LEAD PLAN SD003
echo "Replacing sd027-lead-plan-handoff.js..."
# node templates/create-handoff.js LEAD PLAN SD027
echo "Replacing sd027-plan-exec-handoff.js..."
# node templates/create-handoff.js PLAN EXEC SD027
echo "Replacing sd031-lead-plan-handoff.js..."
# node templates/create-handoff.js LEAD PLAN SD031
echo "Replacing sd037-lead-plan-handoff.js..."
# node templates/create-handoff.js LEAD PLAN SD037
echo "Replacing sd039-exec-plan-verification-handoff.js..."
# # Handoff phases unclear for sd039-exec-plan-verification-handoff.js
echo "Replacing sd039-lead-plan-handoff.js..."
# node templates/create-handoff.js LEAD PLAN SD039
echo "Replacing sd039-plan-exec-handoff.js..."
# node templates/create-handoff.js PLAN EXEC SD039
echo "Replacing sd039-plan-lead-approval-handoff.js..."
# # Handoff phases unclear for sd039-plan-lead-approval-handoff.js
echo "Replacing sd046-lead-plan-handoff.js..."
# node templates/create-handoff.js LEAD PLAN SD046
echo "Replacing sd046-plan-exec-handoff.js..."
# node templates/create-handoff.js PLAN EXEC SD046

# PRD GENERATION SCRIPTS
echo "📐 Migrating PRD generation scripts..."
echo "Replacing generate-prd-sd008.js..."
# node templates/generate-prd.js SD008
echo "Replacing generate-prd-sd027.js..."
# node templates/generate-prd.js SD027
echo "Replacing generate-prd-sd037.js..."
# node templates/generate-prd.js SD037
echo "Replacing generate-prd-sd039.js..."
# node templates/generate-prd.js SD039
echo "Replacing generate-prd-sd046.js..."
# node templates/generate-prd.js SD046

# EXECUTION SCRIPTS
echo "🚀 Migrating execution scripts..."
echo "Replacing execute-plan-sd008.js..."
# node templates/execute-phase.js EXEC SD008
echo "Replacing execute-sd-leo-001.js..."
# # Unable to extract SD ID from execute-sd-leo-001.js
echo "Replacing execute-sd-leo-002.js..."
# # Unable to extract SD ID from execute-sd-leo-002.js
echo "Replacing execute-sd-leo-003.js..."
# # Unable to extract SD ID from execute-sd-leo-003.js


# MANUAL REVIEW NEEDED
echo "⚠️  Manual review needed for:"
echo "  plan-verification-sd-2025-001.js - # Unknown script type for plan-verification-sd-2025-001.js"
echo "  plan-verify-sdip.js - # Unable to extract SD ID from plan-verify-sdip.js"
echo "  sd027-completion.js - # Unknown script type for sd027-completion.js"
echo "  sd027-exec-completion.js - # Unknown script type for sd027-exec-completion.js"
echo "  sd027-lead-final-approval.js - # Unknown script type for sd027-lead-final-approval.js"
echo "  sd027-lead-requirements-analysis.js - # Unknown script type for sd027-lead-requirements-analysis.js"
echo "  sd028-phase1-verification.js - # Unknown script type for sd028-phase1-verification.js"
echo "  sd028-phase2-verification.js - # Unknown script type for sd028-phase2-verification.js"
echo "  sd028-retrospective.js - # Unknown script type for sd028-retrospective.js"
echo "  sd039-lead-final-approval.js - # Unknown script type for sd039-lead-final-approval.js"
echo "  sd039-plan-supervisor-verification.js - # Unknown script type for sd039-plan-supervisor-verification.js"
echo "  sd046-exec-completion.js - # Unknown script type for sd046-exec-completion.js"
echo "  sd046-lead-final-approval.js - # Unknown script type for sd046-lead-final-approval.js"
echo "  sd046-lead-requirements-analysis.js - # Unknown script type for sd046-lead-requirements-analysis.js"
echo "  sd046-plan-supervisor-verification.js - # Unknown script type for sd046-plan-supervisor-verification.js"
echo "  update-prd-sd028.js - # Unknown script type for update-prd-sd028.js"


echo "✅ Migration commands generated!"
echo "💡 Remove '#' from commands above to execute them"
echo "💡 Test each template command before removing original scripts"
