import { createClient } from '@supabase/supabase-js';
import 'dotenv/config';
const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
const { data } = await sb.from('sub_agent_execution_results').select('*').eq('id','5d2832f7-386e-4686-aae8-33f68b61e06c').maybeSingle();
const m = data.metadata || {};
console.log('code/phase/verdict:', data.sub_agent_code, data.phase, data.verdict);
console.log('sd_id:', data.sd_id);
console.log('repo_path:', m.repo_path);
console.log('executed_from_cwd:', m.executed_from_cwd);
console.log('repo_resolved:', m.repo_resolved, '| registry_source:', m.registry_source);
console.log('session_id:', m.session_id);
console.log('content_hash:', m.content_hash);
console.log('evaluated_commit_sha:', m.evaluated_commit_sha);
console.log('measured:', m.measured);
console.log('test_execution:', JSON.stringify(m.test_execution));
console.log('lint_execution present:', !!m.lint_execution, '| smoke_execution len:', (m.smoke_execution||[]).length);
console.log('acceptance_criteria_coverage len:', (m.acceptance_criteria_coverage||[]).length);
console.log('e2e applicable/ran:', m.e2e_tier?.applicable, m.e2e_tier?.ran);
console.log('TOP-LEVEL path cols present?', ['repo_path','local_path'].filter(k=>k in data));
