-- R&D Proposals Table
-- SD: SD-AUTONOMOUS-SKUNKWORKS-RD-DEPARTMENT-ORCH-001-A
-- Purpose: Store autonomous R&D proposals generated by Monday batch job
-- Proposals are queued for chairman review at Friday EVA meetings

-- Status enum
DO $$ BEGIN
  CREATE TYPE rd_proposal_status AS ENUM (
    'pending_review', 'approved', 'rejected',
    'in_progress', 'completed', 'archived'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Proposal type enum
DO $$ BEGIN
  CREATE TYPE rd_proposal_type AS ENUM (
    'cross_pollination', 'capability_gap',
    'market_signal', 'stage_pattern'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Main table
CREATE TABLE IF NOT EXISTS rd_proposals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  hypothesis TEXT,
  methodology TEXT,
  expected_outcome TEXT,
  priority_score NUMERIC(5,2) CHECK (priority_score >= 0 AND priority_score <= 100),
  status rd_proposal_status NOT NULL DEFAULT 'pending_review',
  proposal_type rd_proposal_type,
  venture_ids JSONB DEFAULT '[]'::jsonb,
  metadata JSONB DEFAULT '{}'::jsonb,
  dedup_key TEXT,
  created_by TEXT NOT NULL DEFAULT 'batch-job',
  reviewed_at TIMESTAMPTZ,
  reviewer_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_rd_proposals_status ON rd_proposals(status);
CREATE INDEX IF NOT EXISTS idx_rd_proposals_created_at ON rd_proposals(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_rd_proposals_dedup ON rd_proposals(dedup_key);
CREATE INDEX IF NOT EXISTS idx_rd_proposals_type ON rd_proposals(proposal_type);

-- RLS
ALTER TABLE rd_proposals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_role_all_rd_proposals" ON rd_proposals
  FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "authenticated_read_rd_proposals" ON rd_proposals
  FOR SELECT TO authenticated USING (true);

-- Updated_at trigger
CREATE OR REPLACE FUNCTION update_rd_proposals_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_rd_proposals_updated_at
  BEFORE UPDATE ON rd_proposals
  FOR EACH ROW EXECUTE FUNCTION update_rd_proposals_updated_at();

COMMENT ON TABLE rd_proposals IS
  'Autonomous R&D proposals generated by Monday batch job. Queued for chairman review at Friday EVA meetings.';
