-- Migration: Create monthly_ceo_reports table
-- Purpose: Store monthly CEO performance reports generated by the CEO agent
-- Author: Database Sub-Agent (SD-EHG-ORCH-INTERFACE-AGENTS-001-B)
-- Date: 2026-02-20
-- Rollback: DROP TABLE IF EXISTS monthly_ceo_reports;

-- ============================================================================
-- 1. CREATE monthly_ceo_reports TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS monthly_ceo_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  venture_id UUID NOT NULL REFERENCES ventures(id),
  period VARCHAR(7) NOT NULL,                        -- Format: YYYY-MM
  content JSONB NOT NULL DEFAULT '{}',
  generated_by VARCHAR(100) DEFAULT 'ceo_agent',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT monthly_ceo_reports_venture_period_unique UNIQUE (venture_id, period),
  CONSTRAINT monthly_ceo_reports_period_format CHECK (period ~ '^\d{4}-\d{2}$')
);

COMMENT ON TABLE monthly_ceo_reports
  IS 'Monthly CEO performance reports generated by the VentureCEORuntime agent';

COMMENT ON COLUMN monthly_ceo_reports.venture_id
  IS 'FK to ventures table - which venture this report covers';

COMMENT ON COLUMN monthly_ceo_reports.period
  IS 'Report period in YYYY-MM format (e.g., 2026-02)';

COMMENT ON COLUMN monthly_ceo_reports.content
  IS 'JSONB report content including metrics, narrative, highlights, blockers';

COMMENT ON COLUMN monthly_ceo_reports.generated_by
  IS 'Agent or system that generated this report (default: ceo_agent)';

-- ============================================================================
-- 2. INDEXES for query performance
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_monthly_ceo_reports_venture_id
  ON monthly_ceo_reports(venture_id);

CREATE INDEX IF NOT EXISTS idx_monthly_ceo_reports_period
  ON monthly_ceo_reports(period);

CREATE INDEX IF NOT EXISTS idx_monthly_ceo_reports_content
  ON monthly_ceo_reports USING GIN (content);

-- ============================================================================
-- 3. RLS Policies
-- ============================================================================

ALTER TABLE monthly_ceo_reports ENABLE ROW LEVEL SECURITY;

-- Service role: full access (for agent backend operations)
CREATE POLICY "service_role_all_monthly_ceo_reports"
  ON monthly_ceo_reports FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Authenticated chairman: full access (matches objectives/key_results pattern)
CREATE POLICY "chairman_full_access_monthly_ceo_reports"
  ON monthly_ceo_reports FOR ALL
  TO authenticated
  USING ((auth.jwt() ->> 'email'::text) = 'rick@emeraldholdingsgroup.com'::text)
  WITH CHECK ((auth.jwt() ->> 'email'::text) = 'rick@emeraldholdingsgroup.com'::text);
