-- Migration: Add 'stitch_qa_report' to venture_artifacts_artifact_type_check
-- SD: SD-LEO-ORCH-STAGE-STITCH-DESIGN-001-C
-- US: US-001 (BLOCKER dependency for Stitch QA report artifact persistence)
-- DATABASE sub-agent: invoked via Claude Code database-agent
-- Date: 2026-04-09
--
-- Safety: CHECK constraint replacement does not rewrite the table.
--         Brief AccessExclusive lock on the catalog only. Zero downtime.
--         Existing rows are not re-validated.
--
-- All 90 existing values below are preserved verbatim from pg_get_constraintdef()
-- (including 'stitch_design_export' added by Child A migration on 2026-04-09).
-- The ONLY new addition is 'stitch_qa_report' at the end of the list.

BEGIN;

ALTER TABLE venture_artifacts
  DROP CONSTRAINT venture_artifacts_artifact_type_check;

ALTER TABLE venture_artifacts
  ADD CONSTRAINT venture_artifacts_artifact_type_check
  CHECK (((artifact_type)::text = ANY (ARRAY[
    'intake_venture_analysis'::text,
    'truth_idea_brief'::text,
    'truth_ai_critique'::text,
    'truth_validation_decision'::text,
    'truth_competitive_analysis'::text,
    'truth_financial_model'::text,
    'truth_problem_statement'::text,
    'truth_target_market_analysis'::text,
    'truth_value_proposition'::text,
    'engine_risk_matrix'::text,
    'engine_pricing_model'::text,
    'engine_business_model_canvas'::text,
    'engine_exit_strategy'::text,
    'engine_risk_assessment'::text,
    'engine_revenue_model'::text,
    'identity_persona_brand'::text,
    'identity_brand_guidelines'::text,
    'identity_naming_visual'::text,
    'identity_brand_name'::text,
    'identity_gtm_sales_strategy'::text,
    'blueprint_product_roadmap'::text,
    'blueprint_technical_architecture'::text,
    'blueprint_data_model'::text,
    'blueprint_erd_diagram'::text,
    'blueprint_api_contract'::text,
    'blueprint_schema_spec'::text,
    'blueprint_risk_register'::text,
    'blueprint_user_story_pack'::text,
    'blueprint_wireframes'::text,
    'blueprint_financial_projection'::text,
    'blueprint_launch_readiness'::text,
    'blueprint_sprint_plan'::text,
    'blueprint_promotion_gate'::text,
    'blueprint_project_plan'::text,
    'blueprint_review_summary'::text,
    'build_system_prompt'::text,
    'build_cicd_config'::text,
    'build_security_audit'::text,
    'build_mvp_build'::text,
    'build_test_coverage_report'::text,
    'launch_test_plan'::text,
    'launch_uat_report'::text,
    'launch_deployment_runbook'::text,
    'launch_marketing_checklist'::text,
    'launch_analytics_dashboard'::text,
    'launch_health_scoring'::text,
    'launch_churn_triggers'::text,
    'launch_retention_playbook'::text,
    'launch_optimization_roadmap'::text,
    'launch_assumptions_vs_reality'::text,
    'launch_launch_metrics'::text,
    'launch_user_feedback_summary'::text,
    'launch_production_app'::text,
    'system_devils_advocate_review'::text,
    'value_multiplier_assessment'::text,
    'economic_lens'::text,
    'lifecycle_sd_bridge'::text,
    'post_lifecycle_decision'::text,
    'stitch_project'::text,
    'stitch_curation'::text,
    'stitch_budget'::text,
    'stage_0_analysis'::text,
    'stage_1_analysis'::text,
    'stage_2_analysis'::text,
    'stage_3_analysis'::text,
    'stage_4_analysis'::text,
    'stage_5_analysis'::text,
    'stage_6_analysis'::text,
    'stage_7_analysis'::text,
    'stage_8_analysis'::text,
    'stage_9_analysis'::text,
    'stage_10_analysis'::text,
    'stage_11_analysis'::text,
    'stage_12_analysis'::text,
    'stage_13_analysis'::text,
    'stage_14_analysis'::text,
    'stage_15_analysis'::text,
    'stage_16_analysis'::text,
    'stage_17_analysis'::text,
    'stage_18_analysis'::text,
    'stage_19_analysis'::text,
    'stage_20_analysis'::text,
    'stage_21_analysis'::text,
    'stage_22_analysis'::text,
    'stage_23_analysis'::text,
    'stage_24_analysis'::text,
    'stage_25_analysis'::text,
    'stage_26_analysis'::text,
    'stitch_design_export'::text,
    'stitch_qa_report'::text
  ])));

COMMIT;

-- ROLLBACK (manual):
--   BEGIN;
--   ALTER TABLE venture_artifacts DROP CONSTRAINT venture_artifacts_artifact_type_check;
--   ALTER TABLE venture_artifacts ADD CONSTRAINT venture_artifacts_artifact_type_check
--     CHECK (((artifact_type)::text = ANY (ARRAY[
--       'intake_venture_analysis'::text,
--       'truth_idea_brief'::text,
--       'truth_ai_critique'::text,
--       'truth_validation_decision'::text,
--       'truth_competitive_analysis'::text,
--       'truth_financial_model'::text,
--       'truth_problem_statement'::text,
--       'truth_target_market_analysis'::text,
--       'truth_value_proposition'::text,
--       'engine_risk_matrix'::text,
--       'engine_pricing_model'::text,
--       'engine_business_model_canvas'::text,
--       'engine_exit_strategy'::text,
--       'engine_risk_assessment'::text,
--       'engine_revenue_model'::text,
--       'identity_persona_brand'::text,
--       'identity_brand_guidelines'::text,
--       'identity_naming_visual'::text,
--       'identity_brand_name'::text,
--       'identity_gtm_sales_strategy'::text,
--       'blueprint_product_roadmap'::text,
--       'blueprint_technical_architecture'::text,
--       'blueprint_data_model'::text,
--       'blueprint_erd_diagram'::text,
--       'blueprint_api_contract'::text,
--       'blueprint_schema_spec'::text,
--       'blueprint_risk_register'::text,
--       'blueprint_user_story_pack'::text,
--       'blueprint_wireframes'::text,
--       'blueprint_financial_projection'::text,
--       'blueprint_launch_readiness'::text,
--       'blueprint_sprint_plan'::text,
--       'blueprint_promotion_gate'::text,
--       'blueprint_project_plan'::text,
--       'blueprint_review_summary'::text,
--       'build_system_prompt'::text,
--       'build_cicd_config'::text,
--       'build_security_audit'::text,
--       'build_mvp_build'::text,
--       'build_test_coverage_report'::text,
--       'launch_test_plan'::text,
--       'launch_uat_report'::text,
--       'launch_deployment_runbook'::text,
--       'launch_marketing_checklist'::text,
--       'launch_analytics_dashboard'::text,
--       'launch_health_scoring'::text,
--       'launch_churn_triggers'::text,
--       'launch_retention_playbook'::text,
--       'launch_optimization_roadmap'::text,
--       'launch_assumptions_vs_reality'::text,
--       'launch_launch_metrics'::text,
--       'launch_user_feedback_summary'::text,
--       'launch_production_app'::text,
--       'system_devils_advocate_review'::text,
--       'value_multiplier_assessment'::text,
--       'economic_lens'::text,
--       'lifecycle_sd_bridge'::text,
--       'post_lifecycle_decision'::text,
--       'stitch_project'::text,
--       'stitch_curation'::text,
--       'stitch_budget'::text,
--       'stage_0_analysis'::text,
--       'stage_1_analysis'::text,
--       'stage_2_analysis'::text,
--       'stage_3_analysis'::text,
--       'stage_4_analysis'::text,
--       'stage_5_analysis'::text,
--       'stage_6_analysis'::text,
--       'stage_7_analysis'::text,
--       'stage_8_analysis'::text,
--       'stage_9_analysis'::text,
--       'stage_10_analysis'::text,
--       'stage_11_analysis'::text,
--       'stage_12_analysis'::text,
--       'stage_13_analysis'::text,
--       'stage_14_analysis'::text,
--       'stage_15_analysis'::text,
--       'stage_16_analysis'::text,
--       'stage_17_analysis'::text,
--       'stage_18_analysis'::text,
--       'stage_19_analysis'::text,
--       'stage_20_analysis'::text,
--       'stage_21_analysis'::text,
--       'stage_22_analysis'::text,
--       'stage_23_analysis'::text,
--       'stage_24_analysis'::text,
--       'stage_25_analysis'::text,
--       'stage_26_analysis'::text,
--       'stitch_design_export'::text
--     ])));
--   COMMIT;
