/*
 * =====================================================================
 * SD-LEO-INFRA-STAGE-ARCHETYPE-GENERATION-001 PR2 (ARMs B + E)
 *
 * Adds two artifact_type values used by Stage-17 archetype generator:
 *   - s17_variant_failed  ARM B: written when bounded retry exhausts
 *                                on a variant
 *   - s17_heartbeat       ARM E: written every 30s during generation
 *                                as a liveness signal
 *
 * Pattern: drop and re-add the CHECK constraint with the FULL live
 * whitelist (read from pg_get_constraintdef on 2026-04-26) plus the 2
 * new types. The live whitelist had drifted from the migration file
 * history; this migration re-anchors file history to live state.
 * =====================================================================
 */

BEGIN;

ALTER TABLE venture_artifacts
  DROP CONSTRAINT IF EXISTS venture_artifacts_artifact_type_check;

ALTER TABLE venture_artifacts
  ADD CONSTRAINT venture_artifacts_artifact_type_check
  CHECK (artifact_type IN (
    'intake_venture_analysis',
    'truth_idea_brief',
    'truth_ai_critique',
    'truth_validation_decision',
    'truth_competitive_analysis',
    'truth_financial_model',
    'truth_problem_statement',
    'truth_target_market_analysis',
    'truth_value_proposition',
    'engine_risk_matrix',
    'engine_pricing_model',
    'engine_business_model_canvas',
    'engine_exit_strategy',
    'engine_risk_assessment',
    'engine_revenue_model',
    'identity_persona_brand',
    'identity_brand_guidelines',
    'identity_naming_visual',
    'identity_brand_name',
    'identity_gtm_sales_strategy',
    'identity_logo_image',
    'blueprint_product_roadmap',
    'blueprint_technical_architecture',
    'blueprint_data_model',
    'blueprint_erd_diagram',
    'blueprint_api_contract',
    'blueprint_schema_spec',
    'blueprint_risk_register',
    'blueprint_user_story_pack',
    'blueprint_wireframes',
    'blueprint_financial_projection',
    'blueprint_launch_readiness',
    'blueprint_sprint_plan',
    'blueprint_promotion_gate',
    'blueprint_project_plan',
    'blueprint_review_summary',
    'blueprint_token_manifest',
    'build_system_prompt',
    'build_cicd_config',
    'build_security_audit',
    'build_mvp_build',
    'build_test_coverage_report',
    'build_brief',
    'marketing_tagline',
    'marketing_app_store_desc',
    'marketing_landing_hero',
    'marketing_email_welcome',
    'marketing_email_onboarding',
    'marketing_email_reengagement',
    'marketing_social_posts',
    'marketing_seo_meta',
    'marketing_blog_draft',
    'code_quality_report',
    'visual_device_screenshots',
    'visual_social_graphics',
    'distribution_channel_config',
    'distribution_ad_copy',
    'launch_test_plan',
    'launch_uat_report',
    'launch_deployment_runbook',
    'launch_marketing_checklist',
    'launch_analytics_dashboard',
    'launch_health_scoring',
    'launch_churn_triggers',
    'launch_retention_playbook',
    'launch_optimization_roadmap',
    'launch_assumptions_vs_reality',
    'launch_launch_metrics',
    'launch_user_feedback_summary',
    'launch_production_app',
    'launch_readiness_checklist',
    'growth_playbook',
    'system_devils_advocate_review',
    'value_multiplier_assessment',
    'economic_lens',
    'lifecycle_sd_bridge',
    'post_lifecycle_decision',
    'stitch_project',
    'stitch_curation',
    'stitch_budget',
    'stitch_design_export',
    'stitch_qa_report',
    's17_archetypes',
    's17_session_state',
    's17_strategy_recommendation',
    's17_variant_wip',
    's17_approved',
    's17_approved_png',
    's17_design_system',
    's17_fill_screen',
    's17_preview',
    's17_qa_report',
    's17_strategy_stats',
    's17_variant_scores',
    'stage_17_approved_desktop',
    'stage_17_approved_mobile',
    'stage_17_refined',
    's11_identity',
    'stage10_finalization',
    'stage11_identity',
    'stage12_guidelines',
    'stage13_implementation',
    'stage14_review',
    'stage15_wireframes',
    'stage16_soul',
    'stage18_sprint',
    'stage19_deployment',
    'stage1_raw_research',
    'stage2_market_analysis',
    'stage3_competitive',
    'stage4_strategy',
    'stage5_positioning',
    'stage6_validation',
    'stage7_formulation',
    'stage8_evaluation',
    'stage9_optimization',
    'architecture_plan',
    'design_token_manifest',
    'genesis_scaffold',
    'soul_document',
    'vision_document',
    'wireframe_screens',
    'stage_0_analysis',
    'stage_1_analysis',
    'stage_2_analysis',
    'stage_3_analysis',
    'stage_4_analysis',
    'stage_5_analysis',
    'stage_6_analysis',
    'stage_7_analysis',
    'stage_8_analysis',
    'stage_9_analysis',
    'stage_10_analysis',
    'stage_11_analysis',
    'stage_12_analysis',
    'stage_13_analysis',
    'stage_14_analysis',
    'stage_15_analysis',
    'stage_16_analysis',
    'stage_17_analysis',
    'stage_18_analysis',
    'stage_19_analysis',
    'stage_20_analysis',
    'stage_21_analysis',
    'stage_22_analysis',
    'stage_23_analysis',
    'stage_24_analysis',
    'stage_25_analysis',
    'stage_26_analysis',
    's17_heartbeat',
    's17_variant_failed'
  ));

COMMIT;
