-- Migration: rd_proposals table for Skunkworks R&D batch proposals
-- SD: SD-AUTONOMOUS-SKUNKWORKS-RD-DEPARTMENT-ORCH-001-A

-- Proposals generated by Monday batch job, reviewed at Friday EVA meeting
CREATE TABLE IF NOT EXISTS rd_proposals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  hypothesis TEXT NOT NULL,
  evidence JSONB DEFAULT '[]'::jsonb,
  expected_impact TEXT,
  target_application TEXT NOT NULL DEFAULT 'EHG_Engineer',
  priority_score NUMERIC(5,2) NOT NULL DEFAULT 50 CHECK (priority_score >= 0 AND priority_score <= 100),
  status TEXT NOT NULL DEFAULT 'pending_review'
    CHECK (status IN ('pending_review', 'accepted', 'dismissed', 'deferred')),
  signal_source TEXT NOT NULL CHECK (signal_source IN ('calibration', 'codebase_health', 'venture_portfolio', 'composite')),
  methodology TEXT,
  expected_outcome TEXT,
  batch_run_id UUID,
  decided_at TIMESTAMPTZ,
  decided_by TEXT,
  decision_notes TEXT,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Batch run log for auditing
CREATE TABLE IF NOT EXISTS rd_batch_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  batch_type TEXT NOT NULL DEFAULT 'monday_proposals',
  signals_collected INTEGER DEFAULT 0,
  proposals_generated INTEGER DEFAULT 0,
  dry_run BOOLEAN DEFAULT false,
  duration_ms INTEGER,
  error_log JSONB DEFAULT '[]'::jsonb,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_rd_proposals_status ON rd_proposals(status);
CREATE INDEX IF NOT EXISTS idx_rd_proposals_created_at ON rd_proposals(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_rd_proposals_batch_run ON rd_proposals(batch_run_id);
CREATE INDEX IF NOT EXISTS idx_rd_proposals_signal_source ON rd_proposals(signal_source);
CREATE INDEX IF NOT EXISTS idx_rd_batch_runs_created_at ON rd_batch_runs(created_at DESC);

-- RLS
ALTER TABLE rd_proposals ENABLE ROW LEVEL SECURITY;
ALTER TABLE rd_batch_runs ENABLE ROW LEVEL SECURITY;

CREATE POLICY rd_proposals_service_all ON rd_proposals
  FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY rd_proposals_authenticated_read ON rd_proposals
  FOR SELECT TO authenticated USING (true);

CREATE POLICY rd_batch_runs_service_all ON rd_batch_runs
  FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY rd_batch_runs_authenticated_read ON rd_batch_runs
  FOR SELECT TO authenticated USING (true);

-- Updated_at trigger
CREATE OR REPLACE FUNCTION update_rd_proposals_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_rd_proposals_updated_at
  BEFORE UPDATE ON rd_proposals
  FOR EACH ROW EXECUTE FUNCTION update_rd_proposals_updated_at();
