-- Migration: eva_consultant_recommendations table
-- Date: 2026-03-09
-- Purpose: Create the EVA Consultant Recommendations table for storing
--          actionable recommendations derived from trend analysis.
--          Also adds feedback_weight column to eva_consultant_trends.

-- ============================================================
-- 1. Add feedback_weight to eva_consultant_trends
-- ============================================================
ALTER TABLE eva_consultant_trends
  ADD COLUMN IF NOT EXISTS feedback_weight NUMERIC(3,2) DEFAULT 1.0;

COMMENT ON COLUMN eva_consultant_trends.feedback_weight
  IS 'Weight multiplier for trend confidence based on chairman feedback history (0.00-9.99)';

-- ============================================================
-- 2. Create eva_consultant_recommendations table
-- ============================================================
CREATE TABLE IF NOT EXISTS eva_consultant_recommendations (
  id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  recommendation_date   DATE        NOT NULL,
  trend_id              UUID        REFERENCES eva_consultant_trends(id) ON DELETE SET NULL,
  recommendation_type   TEXT        NOT NULL
                        CHECK (recommendation_type IN ('strategic', 'tactical', 'research', 'operational')),
  title                 TEXT        NOT NULL,
  description           TEXT,
  priority_score        NUMERIC(3,2)
                        CHECK (priority_score >= 0 AND priority_score <= 1),
  action_type           TEXT        NOT NULL
                        CHECK (action_type IN ('create_sd', 'research', 'review', 'defer', 'discuss')),
  status                TEXT        NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending', 'accepted', 'deferred', 'rejected')),
  chairman_feedback     TEXT,
  feedback_at           TIMESTAMPTZ,
  application_domain    TEXT,
  detected_by           TEXT        DEFAULT 'recommendation-engine.mjs',
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE(recommendation_date, title)
);

COMMENT ON TABLE eva_consultant_recommendations
  IS 'Actionable recommendations generated by EVA trend analysis for chairman review';

COMMENT ON COLUMN eva_consultant_recommendations.recommendation_type
  IS 'Category: strategic (long-term), tactical (short-term), research (investigation), operational (process)';

COMMENT ON COLUMN eva_consultant_recommendations.priority_score
  IS 'Normalized priority between 0.00 (low) and 1.00 (critical)';

COMMENT ON COLUMN eva_consultant_recommendations.action_type
  IS 'Suggested next action: create_sd, research, review, defer, or discuss';

COMMENT ON COLUMN eva_consultant_recommendations.status
  IS 'Chairman disposition: pending (awaiting review), accepted, deferred, rejected';

-- ============================================================
-- 3. Indexes
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_eva_consultant_recommendations_date
  ON eva_consultant_recommendations (recommendation_date DESC);

CREATE INDEX IF NOT EXISTS idx_eva_consultant_recommendations_status
  ON eva_consultant_recommendations (status);

CREATE INDEX IF NOT EXISTS idx_eva_consultant_recommendations_trend
  ON eva_consultant_recommendations (trend_id);

-- ============================================================
-- 4. RLS Policies
-- ============================================================
ALTER TABLE eva_consultant_recommendations ENABLE ROW LEVEL SECURITY;

-- Service role: full CRUD (bypasses RLS by default, but explicit policy for clarity)
CREATE POLICY service_role_all_eva_consultant_recommendations
  ON eva_consultant_recommendations
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Anon: SELECT only
CREATE POLICY anon_select_eva_consultant_recommendations
  ON eva_consultant_recommendations
  FOR SELECT
  TO anon
  USING (true);

-- ============================================================
-- Rollback SQL (for reference):
-- DROP POLICY IF EXISTS anon_select_eva_consultant_recommendations ON eva_consultant_recommendations;
-- DROP POLICY IF EXISTS service_role_all_eva_consultant_recommendations ON eva_consultant_recommendations;
-- DROP TABLE IF EXISTS eva_consultant_recommendations;
-- ALTER TABLE eva_consultant_trends DROP COLUMN IF EXISTS feedback_weight;
-- ============================================================
