/**
 * migration-guards — three-factor production-deploy guards (PRD FR-2, LEAD R2).
 *
 * For --prod-deploy mode, ALL three factors MUST pass:
 *   (a) --prod-deploy CLI flag present
 *   (b) MIGRATION_APPLY_TOKEN env var matches a token-issuance row in
 *       schema_migrations_applied with token_issued_at within last 1h and
 *       token_consumed_at IS NULL
 *   (c) Migration file contains `-- @approved-by: <email>` header matching
 *       `git config --get user.email` of the invoker
 *
 * Per SEC-C1: token VALUE is generated by crypto.randomBytes(32).toString('hex')
 * by the --issue-token mode and printed ONCE to stdout. ONLY the SHA-256 hash
 * is stored in schema_migrations_applied.token_hash. Apply path re-hashes the
 * env var value and SELECTs by token_hash. Plaintext NEVER persisted.
 *
 * SD: SD-LEO-INFRA-CANONICAL-SCRIPTS-APPLY-001
 */

import crypto from 'crypto';

export function hashToken(value) {
  return crypto.createHash('sha256').update(value, 'utf8').digest('hex');
}

export function generateTokenValue() {
  return crypto.randomBytes(32).toString('hex');
}

const APPROVED_BY_RE = /^\s*--\s*@approved-by:\s*([^\s<>"]+@[^\s<>"]+)\s*$/m;

export function extractApprovedBy(sqlContent) {
  if (typeof sqlContent !== 'string') return null;
  const m = APPROVED_BY_RE.exec(sqlContent);
  return m ? m[1].trim() : null;
}

export function checkFlagFactor(flagPresent) {
  return flagPresent === true
    ? { ok: true }
    : { ok: false, factor: 'flag', reason: '--prod-deploy flag not present' };
}

export function checkApproverFactor(sqlContent, gitUserEmail) {
  if (!gitUserEmail || typeof gitUserEmail !== 'string' || !gitUserEmail.includes('@')) {
    return { ok: false, factor: 'approver', reason: 'git user.email not configured' };
  }
  const approver = extractApprovedBy(sqlContent);
  if (!approver) {
    return { ok: false, factor: 'approver', reason: 'missing -- @approved-by: <email> header' };
  }
  if (approver.toLowerCase() !== gitUserEmail.trim().toLowerCase()) {
    return { ok: false, factor: 'approver', reason: `approver ${approver} does not match git user.email ${gitUserEmail}` };
  }
  return { ok: true, approver };
}

const TOKEN_TTL_MS = 60 * 60 * 1000;

export async function checkTokenFactor(client, tokenValue) {
  if (!tokenValue || typeof tokenValue !== 'string' || tokenValue.length < 32) {
    return { ok: false, factor: 'token', reason: 'MIGRATION_APPLY_TOKEN env var missing or too short' };
  }
  const tokenHash = hashToken(tokenValue);
  const r = await client.query(
    `SELECT id, token_issued_at, token_consumed_at
       FROM public.schema_migrations_applied
      WHERE token_hash = $1 AND migration_path IS NULL
      LIMIT 1`,
    [tokenHash]
  );
  if (r.rows.length === 0) {
    return { ok: false, factor: 'token', reason: 'token not found in audit table' };
  }
  const row = r.rows[0];
  if (row.token_consumed_at !== null) {
    return { ok: false, factor: 'token', reason: 'token already consumed' };
  }
  const issuedAt = new Date(row.token_issued_at).getTime();
  if (Date.now() - issuedAt > TOKEN_TTL_MS) {
    return { ok: false, factor: 'token', reason: 'token expired (>1h since issuance)' };
  }
  return { ok: true, tokenRowId: row.id, tokenHash };
}

export async function validateProdDeployGuards({ flagPresent, tokenEnv, sqlContent, gitUserEmail, client }) {
  const f = checkFlagFactor(flagPresent);
  if (!f.ok) return f;
  const a = checkApproverFactor(sqlContent, gitUserEmail);
  if (!a.ok) return a;
  const t = await checkTokenFactor(client, tokenEnv);
  if (!t.ok) return t;
  return { ok: true, approver: a.approver, tokenRowId: t.tokenRowId, tokenHash: t.tokenHash };
}

// ── SD-LEO-INFRA-ADAM-DBCHANGE-APPLY-DELEGATION-001 — Adam delegated-apply gate ──
// Chairman-authorized (2026-06-16) SCOPED delegation: Adam may APPLY additive + governed-data-row
// changes ONLY. This is a SEPARATE wrapper — checkApproverFactor / validateProdDeployGuards above
// are NOT broadened (the chairman path stays the only path for non-delegatable changes).
//
// SEC-H1 (confused-deputy defense): the `-- @delegated-by: adam` line is just a forgeable ROUTING
// marker — it is NOT the authority. The REAL secret factor is the SAME crypto token mechanism the
// chairman path uses (checkTokenFactor: an unconsumed, <1h, hashed-in-DB token). A forged
// @delegated-by line without a valid token is REJECTED. The fail-closed SCOPE boundary
// (isDelegatableForApply) + the default-OFF kill-switch (isDelegationEnabled) gate everything.
import { isDelegatableForApply, isDelegationEnabled } from '../../lib/migration/adam-delegated-apply.js';

const DELEGATED_BY_RE = /^\s*--\s*@delegated-by:\s*adam\s*$/im;

export function extractDelegatedBy(sqlContent) {
  if (typeof sqlContent !== 'string') return null;
  return DELEGATED_BY_RE.test(sqlContent) ? 'adam' : null;
}

/**
 * Adam delegated-apply guard. ALL factors must pass, in fail-closed order:
 *   (1) --prod-deploy flag present
 *   (2) kill-switch ON (LEO_ADAM_DBAPPLY_DELEGATION === 'on'); default-OFF => reject (chairman path)
 *   (3) SCOPE: isDelegatableForApply(sql) true (additive-no-policy/rls OR governed literal INSERT)
 *   (4) routing marker `-- @delegated-by: adam` present
 *   (5) REAL SECRET: a valid unconsumed delegation token (checkTokenFactor) — SEC-H1
 * Returns { ok, path:'delegated', kind, scopeReason, tokenRowId, tokenHash } or { ok:false, factor, reason }.
 */
export async function validateDelegatedApplyGuards({ flagPresent, tokenEnv, sqlContent, client, env }) {
  const f = checkFlagFactor(flagPresent);
  if (!f.ok) return { ...f, path: 'delegated' };
  if (!isDelegationEnabled(env)) {
    return { ok: false, factor: 'kill_switch', reason: 'delegation disabled (LEO_ADAM_DBAPPLY_DELEGATION != on) — chairman path required', path: 'delegated' };
  }
  const scope = isDelegatableForApply(sqlContent);
  if (!scope.delegatable) {
    return { ok: false, factor: 'scope', reason: `not delegatable (chairman-only): ${scope.reason}`, path: 'delegated', scope };
  }
  if (!extractDelegatedBy(sqlContent)) {
    return { ok: false, factor: 'delegated_marker', reason: 'missing -- @delegated-by: adam routing marker', path: 'delegated' };
  }
  const t = await checkTokenFactor(client, tokenEnv); // SEC-H1: the real secret (NOT the @delegated-by string)
  if (!t.ok) return { ...t, path: 'delegated' };
  return { ok: true, path: 'delegated', kind: scope.kind, scopeReason: scope.reason, tokenRowId: t.tokenRowId, tokenHash: t.tokenHash };
}
