#!/bin/bash
# Pre-commit hook for EHG Venture repositories
# Detects common secret patterns before commit
# Generated by SD-LEO-INFRA-VENTURE-DEVWORKFLOW-AWARENESS-001-C

# Branch guard — warn on direct main/master commits (non-blocking)
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
if [[ "$BRANCH" == "main" || "$BRANCH" == "master" ]]; then
  echo "WARNING: Committing directly to $BRANCH — consider using a feature branch."
fi

# Secret patterns to detect
PATTERNS=(
  'SUPABASE_SERVICE_ROLE_KEY\s*='
  'SUPABASE_ANON_KEY\s*='
  'sk-[a-zA-Z0-9]{20,}'
  'ghp_[a-zA-Z0-9]{36}'
  'ghs_[a-zA-Z0-9]{36}'
  'ANTHROPIC_API_KEY\s*='
  'OPENAI_API_KEY\s*='
  'password\s*=\s*["\x27][^"\x27]{8,}'
  'BEGIN (RSA|DSA|EC|OPENSSH) PRIVATE KEY'
  'AKIA[A-Z0-9]{16}'
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9\.'
)

# Exclusions — files that may legitimately contain pattern-like strings
EXCLUDE_PATTERN='(\.env\.example|__fixtures__|__mocks__|test/fixtures/)'

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -Ev "$EXCLUDE_PATTERN")

if [ -z "$STAGED_FILES" ]; then
  exit 0
fi

FOUND=0
for pattern in "${PATTERNS[@]}"; do
  MATCHES=$(echo "$STAGED_FILES" | xargs grep -lE "$pattern" 2>/dev/null)
  if [ -n "$MATCHES" ]; then
    echo "ERROR: Potential secret detected matching pattern: $pattern"
    echo "  Files: $MATCHES"
    FOUND=1
  fi
done

if [ $FOUND -ne 0 ]; then
  echo ""
  echo "Commit blocked: Remove secrets before committing."
  echo "If this is a false positive, use: git commit --no-verify"
  exit 1
fi

exit 0
