-- Create PRD table
CREATE TABLE IF NOT EXISTS product_requirements_v2 (
    id VARCHAR(100) PRIMARY KEY,
    directive_id VARCHAR(50) REFERENCES strategic_directives_v2(id) ON DELETE CASCADE,
    title VARCHAR(500) NOT NULL,
    version VARCHAR(20) NOT NULL DEFAULT '1.0',
    status VARCHAR(50) NOT NULL,
    category VARCHAR(50) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    executive_summary TEXT,
    business_context TEXT,
    technical_context TEXT,
    functional_requirements JSONB DEFAULT '[]'::jsonb,
    non_functional_requirements JSONB DEFAULT '[]'::jsonb,
    technical_requirements JSONB DEFAULT '[]'::jsonb,
    system_architecture TEXT,
    data_model JSONB DEFAULT '{}'::jsonb,
    api_specifications JSONB DEFAULT '[]'::jsonb,
    ui_ux_requirements JSONB DEFAULT '[]'::jsonb,
    implementation_approach TEXT,
    technology_stack JSONB DEFAULT '[]'::jsonb,
    dependencies JSONB DEFAULT '[]'::jsonb,
    test_scenarios JSONB DEFAULT '[]'::jsonb,
    acceptance_criteria JSONB DEFAULT '[]'::jsonb,
    performance_requirements JSONB DEFAULT '{}'::jsonb,
    plan_checklist JSONB DEFAULT '[]'::jsonb,
    exec_checklist JSONB DEFAULT '[]'::jsonb,
    validation_checklist JSONB DEFAULT '[]'::jsonb,
    progress INTEGER DEFAULT 0,
    phase VARCHAR(50),
    phase_progress JSONB DEFAULT '{}'::jsonb,
    risks JSONB DEFAULT '[]'::jsonb,
    constraints JSONB DEFAULT '[]'::jsonb,
    assumptions JSONB DEFAULT '[]'::jsonb,
    stakeholders JSONB DEFAULT '[]'::jsonb,
    approved_by VARCHAR(100),
    approval_date TIMESTAMP,
    planned_start TIMESTAMP,
    planned_end TIMESTAMP,
    actual_start TIMESTAMP,
    actual_end TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    metadata JSONB DEFAULT '{}'::jsonb,
    content TEXT
);