#!/usr/bin/env node

/**
 * Proposal Management CLI
 * LEO Protocol v4.4: Proactive SD Proposal System
 *
 * Commands:
 *   list                     - List pending proposals
 *   approve <id>             - Approve proposal and create draft SD
 *   dismiss <id> <reason>    - Dismiss proposal with reason
 *   view <id>                - View proposal details
 */

import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

// Cross-platform path resolution (SD-WIN-MIG-005 fix)
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const EHG_ENGINEER_ROOT = path.resolve(__dirname, '..');

// Load environment from EHG_Engineer regardless of cwd
const envPath = path.join(EHG_ENGINEER_ROOT, '.env');
if (fs.existsSync(envPath)) {
  dotenv.config({ path: envPath });
} else {
  dotenv.config();
}

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
);

// ANSI colors
const colors = {
  reset: '\x1b[0m',
  bold: '\x1b[1m',
  dim: '\x1b[2m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  cyan: '\x1b[36m',
  red: '\x1b[31m',
};

const VALID_REASONS = [
  'not_relevant',
  'wrong_timing',
  'duplicate',
  'too_small',
  'too_large',
  'already_fixed',
  'other'
];

async function listProposals() {
  console.log(`\n${colors.bold}${colors.cyan}═══════════════════════════════════════════════════════════════${colors.reset}`);
  console.log(`${colors.bold} PENDING SD PROPOSALS${colors.reset}`);
  console.log(`${colors.cyan}═══════════════════════════════════════════════════════════════${colors.reset}\n`);

  const { data: proposals, error } = await supabase
    .from('sd_proposals')
    .select('*')
    .eq('status', 'pending')
    .order('urgency_level', { ascending: true })
    .order('confidence_score', { ascending: false });

  if (error) {
    console.error(`${colors.red}Error: ${error.message}${colors.reset}`);
    process.exit(1);
  }

  if (!proposals || proposals.length === 0) {
    console.log(`${colors.dim}No pending proposals.${colors.reset}`);
    console.log(`\n${colors.dim}Proposals are generated by observer agents monitoring:${colors.reset}`);
    console.log('  - npm audit (dependency vulnerabilities)');
    console.log('  - Retrospective patterns');
    console.log('  - Code health metrics');
    return;
  }

  console.log(`Found ${proposals.length} pending proposal(s):\n`);

  for (const p of proposals) {
    const urgencyIcon = p.urgency_level === 'critical' ? `${colors.red}CRITICAL` :
                        p.urgency_level === 'medium' ? `${colors.yellow}MEDIUM` : `${colors.green}LOW`;
    const triggerLabel = {
      'dependency_update': 'Dependency',
      'retrospective_pattern': 'Pattern',
      'code_health': 'Code Health'
    }[p.trigger_type] || p.trigger_type;
    const confidence = (p.confidence_score * 100).toFixed(0);
    const created = new Date(p.created_at).toLocaleDateString();

    console.log(`${colors.bold}${p.id}${colors.reset}`);
    console.log(`  ${urgencyIcon}${colors.reset} | ${triggerLabel} | ${confidence}% confidence | ${created}`);
    console.log(`  ${colors.cyan}${p.title}${colors.reset}`);
    console.log(`  ${colors.dim}${p.description.substring(0, 100)}...${colors.reset}`);
    console.log();
  }

  console.log(`${colors.bold}Quick Commands:${colors.reset}`);
  console.log(`  ${colors.green}npm run proposal:approve <id>${colors.reset}  - Create draft SD`);
  console.log(`  ${colors.red}npm run proposal:dismiss <id> <reason>${colors.reset}  - Dismiss`);
  console.log(`  ${colors.cyan}npm run proposal:view <id>${colors.reset}  - View details`);
}

async function approveProposal(proposalId) {
  console.log(`\n${colors.bold}Approving proposal: ${proposalId}${colors.reset}\n`);

  // Find proposal by ID or partial ID
  let proposal;
  const { data: exactMatch } = await supabase
    .from('sd_proposals')
    .select('*')
    .eq('id', proposalId)
    .single();

  if (exactMatch) {
    proposal = exactMatch;
  } else {
    // Try partial match (first 8 chars)
    const { data: partialMatches } = await supabase
      .from('sd_proposals')
      .select('*')
      .ilike('id', `${proposalId}%`)
      .eq('status', 'pending');

    if (!partialMatches || partialMatches.length === 0) {
      console.error(`${colors.red}Proposal not found: ${proposalId}${colors.reset}`);
      process.exit(1);
    }

    if (partialMatches.length > 1) {
      console.error(`${colors.red}Multiple proposals match '${proposalId}'. Please provide more characters.${colors.reset}`);
      partialMatches.forEach(p => console.log(`  ${p.id}`));
      process.exit(1);
    }

    proposal = partialMatches[0];
  }

  if (proposal.status !== 'pending' && proposal.status !== 'seen') {
    console.error(`${colors.red}Proposal is not in approvable state: ${proposal.status}${colors.reset}`);
    if (proposal.created_sd_id) {
      console.log(`${colors.dim}Already approved as SD: ${proposal.created_sd_id}${colors.reset}`);
    }
    process.exit(1);
  }

  // Call the database function to create SD
  const { data: sdId, error } = await supabase
    .rpc('fn_create_sd_from_proposal', { proposal_id: proposal.id });

  if (error) {
    console.error(`${colors.red}Error creating SD: ${error.message}${colors.reset}`);
    process.exit(1);
  }

  console.log(`${colors.green}${colors.bold}Success!${colors.reset}`);
  console.log(`  Created SD: ${colors.cyan}${sdId}${colors.reset}`);
  console.log(`  Status: ${colors.yellow}draft${colors.reset} (ready for LEAD validation)`);
  console.log(`\n${colors.dim}Next steps:${colors.reset}`);
  console.log(`  1. Run: npm run sd:start ${sdId}`);
  console.log('  2. Complete LEAD phase validation');
  console.log('  3. Proceed through normal LEO Protocol workflow');
}

async function dismissProposal(proposalId, reason) {
  if (!reason) {
    console.error(`${colors.red}Reason required. Valid reasons:${colors.reset}`);
    VALID_REASONS.forEach(r => console.log(`  - ${r}`));
    process.exit(1);
  }

  if (!VALID_REASONS.includes(reason)) {
    console.error(`${colors.red}Invalid reason: ${reason}${colors.reset}`);
    console.log(`Valid reasons: ${VALID_REASONS.join(', ')}`);
    process.exit(1);
  }

  console.log(`\n${colors.bold}Dismissing proposal: ${proposalId}${colors.reset}\n`);

  // Find proposal by ID or partial ID
  let proposal;
  const { data: exactMatch } = await supabase
    .from('sd_proposals')
    .select('*')
    .eq('id', proposalId)
    .single();

  if (exactMatch) {
    proposal = exactMatch;
  } else {
    // Try partial match
    const { data: partialMatches } = await supabase
      .from('sd_proposals')
      .select('*')
      .ilike('id', `${proposalId}%`)
      .eq('status', 'pending');

    if (!partialMatches || partialMatches.length === 0) {
      console.error(`${colors.red}Proposal not found: ${proposalId}${colors.reset}`);
      process.exit(1);
    }

    if (partialMatches.length > 1) {
      console.error(`${colors.red}Multiple proposals match '${proposalId}'. Please provide more characters.${colors.reset}`);
      partialMatches.forEach(p => console.log(`  ${p.id}`));
      process.exit(1);
    }

    proposal = partialMatches[0];
  }

  if (proposal.status === 'dismissed') {
    console.error(`${colors.red}Proposal already dismissed${colors.reset}`);
    process.exit(1);
  }

  // Update proposal
  const { error } = await supabase
    .from('sd_proposals')
    .update({
      status: 'dismissed',
      dismissed_at: new Date().toISOString(),
      dismissal_reason: reason
    })
    .eq('id', proposal.id);

  if (error) {
    console.error(`${colors.red}Error dismissing: ${error.message}${colors.reset}`);
    process.exit(1);
  }

  console.log(`${colors.green}${colors.bold}Dismissed!${colors.reset}`);
  console.log(`  Proposal: ${proposal.id}`);
  console.log(`  Reason: ${reason}`);
  console.log(`\n${colors.dim}This feedback will improve future proposal quality.${colors.reset}`);
}

async function viewProposal(proposalId) {
  // Find proposal by ID or partial ID
  let proposal;
  const { data: exactMatch } = await supabase
    .from('sd_proposals')
    .select('*')
    .eq('id', proposalId)
    .single();

  if (exactMatch) {
    proposal = exactMatch;
  } else {
    // Try partial match
    const { data: partialMatches } = await supabase
      .from('sd_proposals')
      .select('*')
      .ilike('id', `${proposalId}%`);

    if (!partialMatches || partialMatches.length === 0) {
      console.error(`${colors.red}Proposal not found: ${proposalId}${colors.reset}`);
      process.exit(1);
    }

    if (partialMatches.length > 1) {
      console.error(`${colors.red}Multiple proposals match '${proposalId}'. Please provide more characters.${colors.reset}`);
      partialMatches.forEach(p => console.log(`  ${p.id}`));
      process.exit(1);
    }

    proposal = partialMatches[0];
  }

  console.log(`\n${colors.bold}${colors.cyan}═══════════════════════════════════════════════════════════════${colors.reset}`);
  console.log(`${colors.bold} PROPOSAL DETAILS${colors.reset}`);
  console.log(`${colors.cyan}═══════════════════════════════════════════════════════════════${colors.reset}\n`);

  const urgencyIcon = proposal.urgency_level === 'critical' ? `${colors.red}CRITICAL` :
                      proposal.urgency_level === 'medium' ? `${colors.yellow}MEDIUM` : `${colors.green}LOW`;
  const statusIcon = proposal.status === 'pending' ? `${colors.yellow}PENDING` :
                     proposal.status === 'approved' ? `${colors.green}APPROVED` :
                     proposal.status === 'dismissed' ? `${colors.red}DISMISSED` : proposal.status.toUpperCase();

  console.log(`${colors.bold}ID:${colors.reset} ${proposal.id}`);
  console.log(`${colors.bold}Status:${colors.reset} ${statusIcon}${colors.reset}`);
  console.log(`${colors.bold}Urgency:${colors.reset} ${urgencyIcon}${colors.reset}`);
  console.log(`${colors.bold}Trigger:${colors.reset} ${proposal.trigger_type}`);
  console.log(`${colors.bold}Confidence:${colors.reset} ${(proposal.confidence_score * 100).toFixed(0)}%`);
  console.log(`${colors.bold}Impact:${colors.reset} ${(proposal.impact_score * 100).toFixed(0)}%`);
  console.log(`${colors.bold}Created:${colors.reset} ${new Date(proposal.created_at).toLocaleString()}`);
  console.log(`${colors.bold}Created By:${colors.reset} ${proposal.created_by}`);

  console.log(`\n${colors.bold}${colors.cyan}Title:${colors.reset}`);
  console.log(`  ${proposal.title}`);

  console.log(`\n${colors.bold}${colors.cyan}Description:${colors.reset}`);
  console.log(proposal.description.split('\n').map(line => `  ${line}`).join('\n'));

  if (proposal.proposed_scope) {
    console.log(`\n${colors.bold}${colors.cyan}Proposed Scope:${colors.reset}`);
    if (proposal.proposed_scope.objectives) {
      console.log(`  ${colors.bold}Objectives:${colors.reset}`);
      proposal.proposed_scope.objectives.forEach(obj => console.log(`    - ${obj}`));
    }
    if (proposal.proposed_scope.success_criteria) {
      console.log(`  ${colors.bold}Success Criteria:${colors.reset}`);
      proposal.proposed_scope.success_criteria.forEach(sc => console.log(`    - ${sc}`));
    }
    if (proposal.proposed_scope.risks) {
      console.log(`  ${colors.bold}Risks:${colors.reset}`);
      proposal.proposed_scope.risks.forEach(r => console.log(`    - ${r.risk}: ${r.mitigation}`));
    }
  }

  if (proposal.evidence_data && Object.keys(proposal.evidence_data).length > 0) {
    console.log(`\n${colors.bold}${colors.cyan}Evidence Data:${colors.reset}`);
    console.log(JSON.stringify(proposal.evidence_data, null, 2).split('\n').map(line => `  ${line}`).join('\n'));
  }

  if (proposal.status === 'pending') {
    console.log(`\n${colors.bold}Actions:${colors.reset}`);
    console.log(`  ${colors.green}npm run proposal:approve ${proposal.id.substring(0, 8)}${colors.reset}`);
    console.log(`  ${colors.red}npm run proposal:dismiss ${proposal.id.substring(0, 8)} <reason>${colors.reset}`);
  }

  if (proposal.created_sd_id) {
    console.log(`\n${colors.bold}Created SD:${colors.reset} ${proposal.created_sd_id}`);
  }

  if (proposal.dismissal_reason) {
    console.log(`\n${colors.bold}Dismissal Reason:${colors.reset} ${proposal.dismissal_reason}`);
  }
}

// Main
const [, , command, ...args] = process.argv;

switch (command) {
  case 'list':
  case undefined:
    listProposals().catch(console.error);
    break;
  case 'approve':
    if (!args[0]) {
      console.error(`${colors.red}Usage: npm run proposal:approve <proposal-id>${colors.reset}`);
      process.exit(1);
    }
    approveProposal(args[0]).catch(console.error);
    break;
  case 'dismiss':
    if (!args[0]) {
      console.error(`${colors.red}Usage: npm run proposal:dismiss <proposal-id> <reason>${colors.reset}`);
      console.log(`Reasons: ${VALID_REASONS.join(', ')}`);
      process.exit(1);
    }
    dismissProposal(args[0], args[1]).catch(console.error);
    break;
  case 'view':
    if (!args[0]) {
      console.error(`${colors.red}Usage: npm run proposal:view <proposal-id>${colors.reset}`);
      process.exit(1);
    }
    viewProposal(args[0]).catch(console.error);
    break;
  default:
    console.log(`${colors.bold}Proposal Management CLI${colors.reset}`);
    console.log(`\n${colors.cyan}Commands:${colors.reset}`);
    console.log('  list                     List pending proposals');
    console.log('  approve <id>             Approve proposal and create draft SD');
    console.log('  dismiss <id> <reason>    Dismiss proposal with reason');
    console.log('  view <id>                View proposal details');
    console.log(`\n${colors.cyan}Valid dismiss reasons:${colors.reset}`);
    VALID_REASONS.forEach(r => console.log(`  ${r}`));
}
