/**
 * AI-provenance helper for Pocock pattern.
 *
 * Pure-function spec validator + kill-switch reader.
 * SD-LEO-PROTOCOL-POCOCK-PATTERNS-ORCH-001-F.
 *
 * Format spec (Phase-1 permissive):
 *   agent:SEAT:ROUND_ID   (e.g. agent:LEAD:557156f7, agent:TESTING:round-3)
 *   human:USER_ID         (e.g. human:rick@codestreetlabs.com)
 *   NULL                  (legacy compatible — pre-SD-F rows)
 *
 * Kill-switch precedence: env > app_config DB row > default OFF.
 * Env names: POCOCK_PROVENANCE_<WRITER> = "true" | "prefix" | "false" (case-insensitive).
 *   "true"   → {emit_source:true,  prefix_enabled:false}
 *   "prefix" → {emit_source:true,  prefix_enabled:true}
 *   "false"  → {emit_source:false, prefix_enabled:false}
 */

export const MAX_FIELD_LENGTH = 256;
export const AGENT_REGEX = /^agent:[a-zA-Z0-9_-]+:[a-zA-Z0-9_.-]+$/;
export const HUMAN_REGEX = /^human:[a-zA-Z0-9_.@-]+$/;
export const AI_PROVENANCE_PREFIX = '> *This was generated by AI during triage.*';
export const KNOWN_WRITERS = Object.freeze(['feedback', 'glossary', 'adr', 'handoff', 'retro']);
export const CONFIG_KEY = 'pocock_provenance_writers';

const DEFAULT_FLAG = Object.freeze({ emit_source: false, prefix_enabled: false });
const CACHE_TTL_MS = 60_000;
let dbCache = null;

/**
 * @param {string|null} s
 * @returns {boolean} true if NULL (legacy compat) or matches agent/human regex
 *                    AND length <= MAX_FIELD_LENGTH.
 */
export function validProvenanceSource(s) {
  if (s === null || s === undefined) return true;
  if (typeof s !== 'string') return false;
  if (s.length === 0 || s.length > MAX_FIELD_LENGTH) return false;
  return AGENT_REGEX.test(s) || HUMAN_REGEX.test(s);
}

export function formatAgent(seat, round) {
  if (!seat || !round) throw new Error('formatAgent: seat and round required');
  const s = `agent:${String(seat)}:${String(round)}`;
  if (!AGENT_REGEX.test(s)) throw new Error(`formatAgent: produced invalid value "${s}"`);
  return s;
}

export function formatHuman(user) {
  if (!user) throw new Error('formatHuman: user required');
  const s = `human:${String(user)}`;
  if (!HUMAN_REGEX.test(s)) throw new Error(`formatHuman: produced invalid value "${s}"`);
  return s;
}

/**
 * Idempotent prefix injection on content. Returns content unchanged if it
 * already starts with the AI_PROVENANCE_PREFIX. Otherwise prepends prefix
 * followed by two newlines. Double-call is byte-identical (idempotent).
 */
export function injectPrefixIdempotent(content) {
  if (typeof content !== 'string') return content;
  if (content.startsWith(AI_PROVENANCE_PREFIX)) return content;
  return AI_PROVENANCE_PREFIX + '\n\n' + content;
}

function envFlag(writerName) {
  const envKey = `POCOCK_PROVENANCE_${String(writerName).toUpperCase()}`;
  const raw = process.env[envKey];
  if (raw === undefined) return null;
  const v = String(raw).trim().toLowerCase();
  if (v === 'prefix') return { emit_source: true, prefix_enabled: true };
  if (v === 'true' || v === '1') return { emit_source: true, prefix_enabled: false };
  if (v === 'false' || v === '0' || v === '') return { emit_source: false, prefix_enabled: false };
  return null;
}

async function readFromDb(supabase) {
  if (dbCache && Date.now() - dbCache.fetchedAt < CACHE_TTL_MS) return dbCache.value;
  const { data, error } = await supabase
    .from('app_config')
    .select('value')
    .eq('key', CONFIG_KEY)
    .maybeSingle();
  if (error || !data || !data.value) {
    dbCache = { fetchedAt: Date.now(), value: null };
    return null;
  }
  let parsed = data.value;
  if (typeof parsed === 'string') {
    try { parsed = JSON.parse(parsed); } catch { parsed = null; }
  }
  dbCache = { fetchedAt: Date.now(), value: parsed };
  return parsed;
}

/**
 * @param {string} writerName one of KNOWN_WRITERS
 * @param {object} [opts] optional {supabase}
 * @returns {Promise<{emit_source:boolean, prefix_enabled:boolean}>}
 */
export async function readProvenanceFlag(writerName, opts = {}) {
  if (!KNOWN_WRITERS.includes(writerName)) return DEFAULT_FLAG;

  const envResult = envFlag(writerName);
  if (envResult !== null) return envResult;

  const supabase = opts.supabase;
  if (!supabase) return DEFAULT_FLAG;

  const dbValue = await readFromDb(supabase);
  if (!dbValue || typeof dbValue !== 'object') return DEFAULT_FLAG;
  const writerCfg = dbValue[writerName];
  if (!writerCfg || typeof writerCfg !== 'object') return DEFAULT_FLAG;
  return {
    emit_source: writerCfg.emit === true,
    prefix_enabled: writerCfg.prefix === true
  };
}

export function _resetCacheForTests() {
  dbCache = null;
}
