-- @approved-by: codestreetlabs@gmail.com
-- (approval transcribed by Adam per chairman ruling 2026-08-07; chairman 'run it' on Group 5 at terminal, 2026-08-16 ceremony)
-- SD-LEO-INFRA-COORDINATION-BUS-ACCESS-001 (FR-1)
-- Scope anon reads off the coordination bus.
--
-- ⚠️ STAGED, NOT APPLIED. chairman_gated_ddl=true, pre-flagged at sourcing. This directory is
-- outside all three auto-applied migration paths precisely so this file waits for a deliberate
-- human apply. The builder does not apply it. See database/chairman-gated/README.md.
--
-- ════════════════════════════════════════════════════════════════════════════════════════════
-- WHAT IS ACTUALLY WRONG (measured, not inherited)
-- ════════════════════════════════════════════════════════════════════════════════════════════
-- An anon-key client reads the ENTIRE bus. Measured live 2026-08-03T03:59Z from one process with
-- two clients: service_role returned 5295 rows, anon returned 5295 rows — identical. That bus now
-- carries a fleet-control primitive (the enforcement kill-switch sentinel), so anyone holding the
-- anon key — a by-convention PUBLIC credential — can read every control message.
--
-- ROOT CAUSE — CORRECTED. My first draft of this file blamed a misleading policy NAME. That was
-- wrong, and the truth is more useful. The policy was created here:
--
--   supabase/ehg_engineer/migrations/20260309_session_coordination.sql:67
--     -- Allow all operations for service role (hooks use service key)
--     CREATE POLICY "service_role_full_access" ON session_coordination
--       FOR ALL USING (true) WITH CHECK (true);
--
-- The name states the author's INTENT accurately. The defect is the OMITTED `TO service_role`
-- CLAUSE: a CREATE POLICY with no TO clause defaults to PUBLIC, so a policy written to scope access
-- to the service role in fact granted it to everyone, anon included. That generalises beyond this
-- table — any CREATE POLICY in this repo lacking an explicit TO is silently public — and it is a
-- far better thing to go looking for than a naming convention.
--
-- UNRECONCILED DRIFT, MUST BE SETTLED AT THE PRE-APPLY CAPTURE: git says this policy is FOR ALL
-- (i.e. all commands, with WITH CHECK). The 2026-08-02 live capture says cmd=SELECT. Those disagree,
-- so something altered the policy after creation or the capture describes a different object. DO NOT
-- DROP UNTIL THAT IS RESOLVED — a rollback written from the wrong one restores the wrong grant.
--
-- ════════════════════════════════════════════════════════════════════════════════════════════
-- WHY THIS MIGRATION IS A DROP AND NOT A REPLACEMENT — read before "improving" it
-- ════════════════════════════════════════════════════════════════════════════════════════════
-- The SD's scope says "replace the public-read policy with SEAT-SCOPED access — a session reads
-- rows it sends or receives". Authoring that predicate revealed it has NO PRINCIPAL TO APPLY TO:
--
--   1. service_role has rolbypassrls = TRUE (captured evidence, Delta 64b7328a). RLS policies are
--      NOT CONSULTED for it at all. So a policy granting service_role access is DECORATIVE — it
--      changes nothing, and its presence would imply a control that is not operating.
--   2. There is NO per-seat authentication in this system. Three Supabase keys exist (ANON,
--      SCHEMA_READER, SERVICE_ROLE) and all are SHARED; there is no sign-in flow for fleet seats.
--      A seat-scoped predicate for `authenticated` would key on an identity nothing ever presents.
--   3. Therefore every real reader is either service_role (bypasses RLS) or anon (the thing being
--      removed). A seat-scoped policy would be a rule that CAN NEVER FIRE, sitting in pg_policies
--      looking like protection. That is the exact defect class this SD exists to remove, and
--      shipping it inside the fix would be self-refuting.
--
-- So the honest change is: remove anon's ability to read, and add NOTHING that cannot fire.
-- Seat-scoping becomes meaningful only if per-seat credentials are introduced; that is a separate
-- SD and is called out in the PRD rather than pre-built here as dead protection.
--
-- ════════════════════════════════════════════════════════════════════════════════════════════
-- PRE-APPLY REQUIREMENT (do not skip — this IS the rollback plan)
-- ════════════════════════════════════════════════════════════════════════════════════════════
-- Capture the live policy state IMMEDIATELY BEFORE applying:
--
--   SELECT policyname, roles::text, cmd, qual, with_check
--     FROM pg_policies WHERE tablename = 'session_coordination';
--   SELECT relrowsecurity, relforcerowsecurity
--     FROM pg_class WHERE oid = 'public.session_coordination'::regclass;
--
-- ⚠️ CORRECTION — an earlier version of this file asserted "NO CREATE POLICY for this table exists
-- anywhere in git, so that capture is the ONLY rollback source". THAT WAS FALSE, and it was the
-- worst possible place for a false load-bearing claim: it would have justified dropping a policy
-- with no git-side reference to restore from. One DOES exist, at
-- supabase/ehg_engineer/migrations/20260309_session_coordination.sql:67 (see ROOT CAUSE above).
--
-- So there are TWO candidate rollback sources and they DISAGREE (git: FOR ALL; captured live:
-- cmd=SELECT). The fresh capture is authoritative for what is actually there, and the git original
-- is authoritative for what was intended. DIFF THEM BEFORE DROPPING ANYTHING — restoring from the
-- wrong one silently re-grants a different scope than existed.
--
-- The definition below was captured 2026-08-02 and is POINT-IN-TIME — a reference, not a substitute
-- for a fresh read.
--
-- NOTE ON PROVENANCE: the live cmd/roles/qual values below are RELAYED from that capture and were
-- NOT independently re-verified from this seat — no SQL RPC is exposed and no client-side probe
-- discriminates policy shape. Treat them as evidence of what was reported, not as a measurement.
--
-- Captured state as of 2026-08-02:
--   policy   : service_role_full_access | cmd=SELECT | roles={public} | qual=true
--   table    : rowsecurity=true, forcerowsecurity=false
--   grants   : anon holds SELECT, no INSERT
--   roles    : rolbypassrls = true for service_role only
--
-- ROLLBACK (restores the prior, deliberately-permissive state):
--   CREATE POLICY service_role_full_access ON public.session_coordination
--     FOR SELECT TO public USING (true);
--   GRANT SELECT ON public.session_coordination TO anon;
--
-- ════════════════════════════════════════════════════════════════════════════════════════════

BEGIN;

-- DROP + CREATE, never CREATE POLICY IF NOT EXISTS: that syntax is NOT valid PostgreSQL and fails
-- with "syntax error at or near NOT". This repo has already paid for that once — see
-- docs/retrospectives/lessons-learned-database-agent-rls-policy-chain.md (PAT-RLS-001).
DROP POLICY IF EXISTS service_role_full_access ON public.session_coordination;

-- Remove the grant as well as the policy. Anon needs BOTH a table GRANT and a permitting policy;
-- dropping only one leaves the other in place as a latent re-enable — the next permissive policy
-- added to this table would silently restore anon read access with nobody deciding to.
REVOKE SELECT ON public.session_coordination FROM anon;

-- Belt-and-braces: FORCE row security so a future table OWNER is also subject to policy, closing
-- the "owner quietly bypasses RLS" path. service_role is unaffected — rolbypassrls outranks this.
ALTER TABLE public.session_coordination FORCE ROW LEVEL SECURITY;

COMMIT;

-- ════════════════════════════════════════════════════════════════════════════════════════════
-- POST-APPLY VERIFICATION — both halves are required
-- ════════════════════════════════════════════════════════════════════════════════════════════
-- Run the two-sided probe from the repo root. ANON must read 0-or-denied AND service_role must
-- still read the full count. Anon-denied alone could mean the table broke; service-full alone says
-- nothing about anon. Assert the RELATION, not a literal — the count was 5295 at 03:59Z and 5322
-- hours later, so a pinned number turns ordinary row growth into a false failure.
--
-- Then confirm a live seat still reads its own lanes by ROUND-TRIP: send one row, read it back.
-- An EMPTY inbox is a FAILURE, not a pass. FR-3 (shipped, c2bf834dda8) removed the anon fallback
-- that would otherwise have turned a credential failure into a silent empty read at exactly this
-- moment.
