-- @approved-by:
-- SD-LEO-SEC-DEFACL-ANON-AUTH-AXIS-001 — per-role default-ACL REVOKE, schema public, functions.
--
-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- STAGED, NOT APPLIED. CHAIRMAN-GATED. DO NOT RUN THIS FILE except at the named ceremony.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- AWAITING CHAIRMAN REVIEW — no @approved-by stamp exists for this file yet, deliberately (house
-- convention: never write an approval stamp until an approval actually happened). Re-staged for
-- ceremony N+2 (QF-20260817-193) after ceremony N+1 (2026-08-17 ~11:0xZ) MEASURED this file
-- unapplyable as originally staged and rolled back cleanly with nothing applied -- see the
-- REWORK section below for what changed and why.
--
-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- THE MECHANISM THIS CLOSES — FUTURE-SCOPED ONLY (measured live 2026-08-16, LEAD phase, see
-- scripts/one-off/verify-defacl-anon-auth-axis-mechanism-001.mjs; re-confirmed EXEC phase via
-- .artifacts/defacl-full-census.json)
-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- pg_default_acl for schema public, objtype='f' (functions), grants EXECUTE to anon and
-- authenticated BY NAME for both roles that mint functions here (postgres, supabase_admin) — NOT
-- via a literal PUBLIC entry. Live-measured raw_acl for (postgres, public):
--   {postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}
-- and for (supabase_admin, public):
--   {postgres=X/supabase_admin,anon=X/supabase_admin,authenticated=X/supabase_admin,service_role=X/supabase_admin}
-- Consequence: a REVOKE EXECUTE ... FROM PUBLIC-only ADP (the shape SD-LEO-INFRA-CLOSE-REMAINING-
-- SECURITY-001 originally scoped for its own descoped FR-4) removes a grant that was never there
-- and leaves the anon/authenticated defaults fully intact — every CREATE FUNCTION issued by either
-- role since then has inherited anon/authenticated EXECUTE by default, which is the recurrence
-- engine behind repeated SECDEF exposure findings on this database.
--
-- CRITICAL SCOPE NOTE (prospective TESTING sub-agent finding, PLAN phase, evidence row
-- d2d233ca-0c2c-4c5c-8982-5be923c28a61): ALTER DEFAULT PRIVILEGES is FUTURE-SCOPED ONLY. This
-- statement changes nothing about the 145 functions that already exist in public today — it only
-- changes what a function CREATEd by postgres/supabase_admin AFTER this applies will inherit. The
-- separate, already-triaged existing-function exposure (28 anon-EXEC / 18 literal-PUBLIC) is
-- closed by a DIFFERENT, already-staged migration:
--   database/chairman-gated/20260816_close_remaining_secdef_execute_exposure.sql
-- (SD-LEO-INFRA-CLOSE-REMAINING-SECURITY-001, completed, authoring done, ceremony-apply pending —
-- this SD does not re-author or duplicate that work). Applying THIS file alone does not revoke any
-- currently-anon-executable function; applying that OTHER file alone does not stop new functions
-- from being born anon/authenticated-executable. Both are required for full closure; they are
-- independent, non-overlapping, and safely apply in either order.
--
-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- WHY PER-ROLE, NOT BARE PER-SCHEMA (TR-1 / the ADP-IN-SCHEMA=ADD-ONLY trap)
-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- `ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ...` with no FOR ROLE clause only affects
-- defaults for the role RUNNING this statement (the chairman's own connection role at apply
-- time) — it does NOT retroactively change postgres's own default-ACL rows, and a per-schema-only
-- ADP is additive-only (cannot subtract an existing role-scoped grant). This is the exact trap
-- that caused SD-LEO-INFRA-CLOSE-REMAINING-SECURITY-001's original FR-4 to fail identically across
-- three independent fix attempts before being descoped. The target role is named explicitly below
-- with its own FOR ROLE clause, not left to the bare per-schema form.
--
-- Does NOT touch: service_role grants (unaffected — service_role keeps its default EXECUTE);
-- any function body; any already-existing function's grants (see the separate migration above).
--
-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- REWORK (QF-20260817-193): postgres-only, not postgres+supabase_admin as originally staged
-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- Ceremony N+1 (2026-08-17 ~11:0xZ, chairman verbal HOLD on this file) MEASURED the original
-- two-role version unapplyable: applying as the standard apply identity failed
-- MIGRATION_APPLY_PROD_FAIL_DDL_ERROR "permission denied to change default privileges" on the
-- `FOR ROLE supabase_admin` clause. Live-confirmed at that ceremony: current_user=postgres,
-- pg_has_role(postgres, 'supabase_admin', 'MEMBER')=false. ALTER DEFAULT PRIVILEGES FOR ROLE X
-- requires the applying session to BE X or hold membership in X (same rule PostgreSQL applies to
-- SET ROLE) — supabase_admin is a Supabase platform-reserved role no customer credential,
-- including this project's own `postgres` superuser, is a member of. That clause is therefore
-- unapplyable from any identity this house's ceremony process can ever hold, not a one-off
-- permission gap to route around.
--
-- Scoped to `FOR ROLE postgres` only. This still closes the actual growth vector this SD exists
-- for: every function this house's own migrations create is authored as `postgres` (this file's
-- own apply identity, and every other chairman-gated migration's), so postgres's default-ACL row
-- is what determines whether OUR future CREATE FUNCTIONs inherit anon/authenticated EXECUTE by
-- default. supabase_admin's own default-ACL row (quoted above, still live and still granting
-- anon/authenticated EXECUTE to anything IT creates) is a genuine, disclosed residual gap, not a
-- silently-dropped one -- it governs Supabase-platform-managed function creation this house's own
-- migrations never perform, and is out of scope for a per-project chairman-gated migration by
-- construction (fixing it, if ever needed, would require a Supabase-platform-level change, not a
-- database/chairman-gated/ file). The paired acceptance script keeps supabase_admin as an explicit
-- expected-UNCHANGED fixture case rather than removing all mention of it, so a future regression
-- that silently re-adds this clause (or one that silently narrows the guard's own coverage) does
-- not go unnoticed either way.
--
-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- REVOKE ... FROM PUBLIC IS ALSO A NO-OP TODAY — KEPT FOR HYGIENE, NOT RESTORED BY THE DOWN FILE
-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- (SECURITY sub-agent, EXEC review, evidence 3bcccfb8-abf0-4a88-9751-c8e81e0bf120). The live
-- raw_acl strings quoted above name exactly three grantees each (postgres/supabase_admin,anon,
-- authenticated,service_role) — never a bare `=X/<role>` (which is how a literal-PUBLIC default-
-- ACL entry renders). So, same as this SD's entire premise about the PREDECESSOR migration's
-- PUBLIC-only REVOKE: revoking PUBLIC here removes a grant that isn't there. It is kept in this
-- statement only as forward-looking hygiene (so a literal-PUBLIC default can never silently
-- reappear), NOT because it changes today's state. Consequence for the paired DOWN file: it does
-- NOT re-grant PUBLIC — doing so would GRANT something this UP never actually revoked, leaving
-- post-DOWN state broader than pre-UP state. See that file's own header for the full reasoning.

BEGIN;

-- ACCESS EXCLUSIVE is not required for ALTER DEFAULT PRIVILEGES (it only mutates pg_default_acl
-- catalog rows, not any live object), but a bounded wait is still the house convention for every
-- statement in a chairman-gated transaction.
SET LOCAL lock_timeout = '5s';

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE EXECUTE ON FUNCTIONS FROM anon, authenticated, PUBLIC;

-- No PostgREST schema-cache reload needed: default-ACL rows are not part of the exposed API
-- surface PostgREST introspects (they govern FUTURE objects, not any live route).

COMMIT;
