/**
 * SD-ARCH-HOTSPOT-LEO-CREATE-001: capture-equivalence spec.
 *
 * fixtures/leo-create-captures.json was generated by extracting the pure helpers
 * VERBATIM from the PRE-refactor scripts/leo-create-sd.js and dumping their outputs
 * for fixed inputs. This spec re-runs the SAME fixed inputs against the moved code
 * (lib/sd-creation/pipeline.js + the source adapters + the proposal lanes) and
 * requires byte-identical results — proving the moves preserved the mapping logic.
 */
import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  mapToDbType,
  inferDefaultSdTypeFromKey,
  resolveSdType,
  buildDefaultSuccessMetrics,
  buildDefaultStrategicObjectives,
  buildDefaultKeyChanges,
  buildDefaultSmokeTestSteps,
  buildDefaultSuccessCriteria,
  inheritStrategicFields,
  mapPriority,
  formatDependencyForDisplay,
} from '../../../lib/sd-creation/pipeline.js';
import { buildPromotionRepoOverrides } from '../../../lib/sd-creation/source-adapters/roadmap-item.js';
import { computePlanContentHash } from '../../../lib/sd-creation/source-adapters/plan.js';
import { normalizeDependsOn } from '../../../scripts/modules/leo-create-sd/proposal-lanes.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const captures = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'fixtures', 'leo-create-captures.json'), 'utf8')
).captures;

function runOrThrowMarker(fn, arg) {
  try { return fn(arg); } catch { return { __throws: true }; }
}

describe('SD-ARCH-HOTSPOT-LEO-CREATE-001: pre-refactor capture equivalence', () => {
  it('mapToDbType matches every captured mapping (incl. fail-loud throws)', () => {
    for (const [input, expected] of Object.entries(captures.mapToDbType)) {
      const arg = input.startsWith('__bad_')
        ? (input === '__bad_null' ? null : input === '__bad_undefined' ? undefined : input.slice('__bad_'.length))
        : input;
      expect(runOrThrowMarker(mapToDbType, arg), `mapToDbType(${input})`).toEqual(expected);
    }
  });

  it('inferDefaultSdTypeFromKey matches captures', () => {
    for (const [key, expected] of Object.entries(captures.inferDefaultSdTypeFromKey)) {
      expect(inferDefaultSdTypeFromKey(key), key).toEqual(expected);
    }
  });

  it('resolveSdType matches captures', () => {
    for (const [k, expected] of Object.entries(captures.resolveSdType)) {
      const [rawStr, key] = k.split('|');
      const raw = rawStr === 'null' ? null : rawStr === 'undefined' ? undefined : rawStr;
      expect(resolveSdType(raw, key), k).toEqual(expected);
    }
  });

  it.each([
    ['buildDefaultSuccessMetrics', buildDefaultSuccessMetrics],
    ['buildDefaultStrategicObjectives', buildDefaultStrategicObjectives],
    ['buildDefaultKeyChanges', buildDefaultKeyChanges],
    ['buildDefaultSuccessCriteria', buildDefaultSuccessCriteria],
  ])('%s matches captures across all captured types', (name, fn) => {
    for (const [type, expected] of Object.entries(captures[name])) {
      expect(fn(type, 'Fixture Title'), `${name}(${type})`).toEqual(expected);
    }
  });

  it('buildDefaultSmokeTestSteps matches captures (lightweight / infra-keyword / feature paths)', () => {
    const args = {
      'documentation|any': ['documentation', 'T', 'edits a script'],
      'orchestrator|flag': ['orchestrator', 'T', 'adds a flag'],
      'infrastructure|nocode': ['infrastructure', 'Update product roadmap copy', undefined],
      'infrastructure|script': ['infrastructure', 'T', 'Adds a script to the harness.'],
      'infrastructure|wizard': ['infrastructure', 'T', 'add a wizard'],
      'feature|any': ['feature', 'My Feature', 'whatever'],
      'bugfix|any': ['bugfix', 'My Fix', null],
    };
    for (const [k, expected] of Object.entries(captures.buildDefaultSmokeTestSteps)) {
      expect(buildDefaultSmokeTestSteps(...args[k]), k).toEqual(expected);
    }
  });

  it('inheritStrategicFields matches captures', () => {
    expect(inheritStrategicFields({
      category: 'Infrastructure',
      strategic_objectives: ['obj1', 'obj2'],
      success_metrics: [{ metric: 'x', target: 'y' }],
      key_principles: ['p1'],
    })).toEqual(captures.inheritStrategicFields.full);
    expect(inheritStrategicFields({})).toEqual(captures.inheritStrategicFields.empty);
    expect(inheritStrategicFields({ category: null, strategic_objectives: [], key_principles: [] }))
      .toEqual(captures.inheritStrategicFields.emptyArrays);
  });

  it('mapPriority matches captures', () => {
    for (const [p, expected] of Object.entries(captures.mapPriority)) {
      expect(mapPriority(p === 'null' ? null : p), p).toEqual(expected);
    }
  });

  it('formatDependencyForDisplay matches captures', () => {
    const c = captures.formatDependencyForDisplay;
    expect(formatDependencyForDisplay('SD-X-001')).toEqual(c.string);
    expect(formatDependencyForDisplay(null)).toEqual(c.null);
    expect(formatDependencyForDisplay(42)).toEqual(c.number);
    expect(formatDependencyForDisplay({ type: 'sd', dependency: 'SD-A-001', dependency_id: 'u' })).toEqual(c.canonical);
    expect(formatDependencyForDisplay({ sd_key: 'SD-B-001' })).toEqual(c.sd_key);
    expect(formatDependencyForDisplay({ sd_id: 'SD-C-001' })).toEqual(c.sd_id);
    expect(formatDependencyForDisplay({ foo: 'bar' })).toEqual(c.weird);
  });

  it('buildPromotionRepoOverrides matches captures', () => {
    const c = captures.buildPromotionRepoOverrides;
    expect(buildPromotionRepoOverrides([])).toEqual(c.empty);
    expect(buildPromotionRepoOverrides(null)).toEqual(c.null);
    expect(buildPromotionRepoOverrides(['EHG'])).toEqual(c.one);
    expect(buildPromotionRepoOverrides(['EHG', 'EHG_Engineer'])).toEqual(c.two);
  });

  it('normalizeDependsOn matches captures', () => {
    const c = captures.normalizeDependsOn;
    expect(normalizeDependsOn(null)).toEqual(c.nonarray);
    expect(normalizeDependsOn(['SD-A-001', '  SD-B-001 ', ''])).toEqual(c.strings);
    expect(normalizeDependsOn([{ sd_id: 'SD-C-001' }, { sd_key: 'SD-D-001' }, { nope: 1 }, 5])).toEqual(c.objects);
  });

  it('computePlanContentHash matches captures (incl. CRLF/trailing-whitespace normalization)', () => {
    const c = captures.computePlanContentHash;
    expect(computePlanContentHash('')).toEqual(c.empty);
    expect(computePlanContentHash('# Plan: X\r\nline one   \nline two\n\n')).toEqual(c.simple);
    expect(
      computePlanContentHash('# Plan: X\nline one\nline two')
        === computePlanContentHash('# Plan: X\r\nline one   \r\nline two\n')
    ).toEqual(c.normalizedEquivalence);
  });
});
