import fs from 'fs';
const P = '.artifacts/testing-exec-to-plan-receipts-evidence.json';
const j = JSON.parse(fs.readFileSync(P, 'utf8'));

j.critical_issues[1] = "FR-3 widening changes a hard gate whose existing coverage does not reach the new keys. scripts/post-merge-handoff-orchestrator.js line 24 imports resolveHoldProvenance, classifyState calls it at line 69, and line 72 returns refuse_held whenever a reason resolves. The gate itself IS tested: tests/unit/ship-auto-handoff-hold-refusal.test.js has 9 tests covering refuse_held. What is untested is the WIDENING. That suite exercises only 2 resolved source keys, requires_human_action_reason and not_worker_claimable_reason, both pre-existing. None of the four new keys has coverage, so the suite passes unchanged while behavior moves underneath it. Measured consequence: 64 live SDs newly resolve a hold, 11 of them non-terminal, and those would now be refused by post-merge auto-handoff where they previously advanced.";

j.critical_issues.push("The widening moves against a measurement the codebase already recorded. lib/fleet/claim-eligibility.cjs lines 806-812 document VAL-1 (evidence cc6f72a7): resolveHoldProvenance was measured over-matching 42 completed SDs across 6 source keys, and deferred_by, not_worker_claimable_reason, dispatch_ineligible_reason and pilot_throwaway were recorded as legitimately compatible with completion. Only requires_human_action_reason and review_hold_reason mean chairman-must-act, and only while unreleased. FR-3 widened that same reader from 6 keys to 10. The 64-SD number is that recorded over-match reproduced in production, one widening later.");

j.warnings.push("Justification gap worth raising with PLAN: the comment at post-merge-handoff-orchestrator.js lines 64-68 justifies choosing resolveHoldProvenance over classifyDispatchIneligibility on the grounds that the claim question is the wrong question. That reasoning is sound but never considers isUnreleasedChairmanHold, the narrow predicate purpose-built for completion-writer refusal in LeadFinalApprovalExecutor and complete_orchestrator_sd. Auto-handoff asks the same should-this-be-allowed-to-complete question, so the narrow predicate is the closer fit and is the one alternative the comment does not address.");

j.recommendations[1] = "Extend the EXISTING suite rather than instrumenting a new one: tests/unit/ship-auto-handoff-hold-refusal.test.js already covers refuse_held with 9 tests. Add cases for an SD carrying only a new key, and for one carrying a released (unfenced_at) new key. Scoping this as a from-scratch gate test would oversize the fix.";

j.recommendations[2] = "Decide explicitly whether classifyState should refuse on the widened key set. The codebase already answered the adjacent question: isUnreleasedChairmanHold (claim-eligibility.cjs) is the narrow completion-class predicate built after VAL-1 measured resolveHoldProvenance over-matching. Switching classifyState to it, or to an explicit narrow key list, follows both that precedent and the one at lead-final-approval/index.js:573 which uses resolveHoldProvenance for display text only.";

j.summary = "All 5 PRD functional requirements are implemented and every SD-owned test passes (63 tests across 6 new files plus 4 updated fixtures). Full unit suite: 47963 passed, 23 failed across 11 files. All 11 are pre-existing Windows git-tmp-repo hook timeouts, none imports any module this SD changed, and the failure count varies run-to-run (25 then 23) on the identical commit, proving flake not regression. 19 of 20 acceptance criteria have a passing test. Three findings hold this back from PASS: the AC-9 db-tier drift test cannot execute and would fail if it did; the FR-3 resolver widening changes the refuse_held gate in post-merge-handoff-orchestrator.js whose existing 9-test suite exercises only 2 pre-existing source keys and so passes unchanged; and that widening moves against VAL-1 (evidence cc6f72a7), a measurement the codebase already recorded showing this same reader over-matching 42 completed SDs.";

j.metadata = j.metadata || {};
j.metadata.amends_row = '4298bd82-d59d-4ac6-b585-eb6aaf206915';
j.metadata.amendment_reason = 'Corrects an imprecision in the superseded row, which framed post-merge-handoff-orchestrator classifyState as an untested gate. The gate has 9 existing tests; the untested surface is the widening (2 of 10 resolved source keys covered, none of them new). Correction raised by test-receipts-lead and independently verified here. Adds the VAL-1/cc6f72a7 corroboration and the isUnreleasedChairmanHold remedy.';
j.metrics.existing_refuse_held_tests = 9;
j.metrics.source_keys_covered_by_existing_suite = 2;
j.metrics.source_keys_total = 10;
j.detailed_analysis.regression_sweep = j.detailed_analysis.regression_sweep.replace('post-merge-handoff-orchestrator.js:70 (hard gate, critical finding)', 'post-merge-handoff-orchestrator.js:69 (hard gate, critical finding; covered by a 9-test suite that exercises only 2 pre-existing source keys, so it passes unchanged while behavior moves)');
fs.writeFileSync(P, JSON.stringify(j, null, 2));
console.log('amended; critical_issues:', j.critical_issues.length, '| warnings:', j.warnings.length);
