import { resolveSubAgentRepo, applySubAgentRepoVerdict } from '../lib/sub-agents/resolve-repo.js';
import { storeSubAgentResults } from '../lib/sub-agent-executor/results-storage.js';

const SD_ID = 'SD-LEO-ORCH-MICHAEL-ROLE-FORMALIZATION-002-C';

const payload = {
  verdict: 'CONDITIONAL_PASS',
  confidence: 90,
  summary:
    'GATE 1 (LEAD pre-approval) passes with five conditions. No duplicate work: lib/integrations/google/, '
    + 'lib/michael/gmail-client.mjs, scripts/michael/google-consent.mjs and server/routes/michael.js do not '
    + 'exist on main, and google-auth-library ^10.5.0 + googleapis ^171.4.0 are already dependencies. The '
    + 'silent-key-generation hazard in lib/security/encryption.cjs is CONFIRMED by measurement, and the '
    + 'proposed MICHAEL_ENCRYPTION_KEY resolution is CONFIRMED implementable without duplicating crypto. '
    + 'Conditions cover the absent live migration, the child-B import seam, requireAuth enforcement that no '
    + 'existing lint covers, and key_fingerprint semantics.',
  findings: [
    { id: 'hazard-confirmed-encryption-cjs-silently-generates-a-throwaway-key', severity: 'critical', note: 'CONFIRMED BY MEASUREMENT, not by reading. lib/security/encryption.cjs:22 sets keyPath = path.join(__dirname, "../../.leo-keys"); getMasterKey() (lines 28-56) catches the fs.access failure and GENERATES a fresh random 32-byte key, writes it, and returns it. Measured in an isolated temp dir: key file absent -> encrypt() created it (key ea4b2e93afd6); key file deleted -> decrypt() of the SAME blob printed the generation banner again, produced a DIFFERENT key (67ebad910ed1) and failed with "Decryption failed: Unsupported state or unable to authenticate data". Venue facts measured: the root checkout C:/Users/rickf/Projects/_EHG/EHG_Engineer/.leo-keys EXISTS (169 bytes, Aug 26); the worktree .worktrees/SD-LEO-ORCH-MICHAEL-ROLE-FORMALIZATION-002-C/.leo-keys DOES NOT; .gitignore:49-50 ignores .leo-keys and .leo-keys.backup*. So a consent flow run from a worktree, a fresh clone, or GHA would encrypt the chairman refresh token under a key generated on the spot, never committed, never backed up, and different on the next venue -- storage that reads as successful and is unrecoverable. This is the exact class the migration comment "child C resolves the key source" was left open for.' },
    { id: 'resolution-confirmed-implementable-export-the-class-not-a-second-crypto-impl', severity: 'critical', note: 'CONFIRMED, three separate measurements. (1) The class is already reachable with NO source change: Object.getPrototypeOf(singleton).constructor.name === "CredentialEncryption". (2) Overriding getMasterKey on an instance WORKS -- encrypt() then decrypt() called the override exactly 2 times and round-tripped {refresh_token:"x"} correctly, because encrypt and decrypt both go through this.getMasterKey(). (3) A wrong key is REFUSED by the GCM auth tag, not silently mis-decrypted: a second instance with a different key threw "Decryption failed: Unsupported state or unable to authenticate data". (4) The clean export is one line, module.exports.CredentialEncryption = CredentialEncryption; appended after the singleton -- measured on a probe copy: the ESM namespace then carries CredentialEncryption, default and module.exports, so BOTH the existing default import (lib/integrations/youtube/oauth-manager.js:24 and lib/operator/cash-sources/token-vault.js keep the singleton) and a named import of the class work. cjs-module-lexer detects it. No crypto duplicated, no existing consumer changed. CONDITION: the instance must OVERRIDE getMasterKey so the inherited self-generating implementation can never run, and it must throw when MICHAEL_ENCRYPTION_KEY is absent or is not 64 hex chars -- never fall back to the inherited method.' },
    { id: 'condition-michael-credentials-is-absent-live-preflight-before-the-browser-opens', severity: 'critical', note: 'MEASURED against the live DB: michael_credentials, michael_gmail_triage_items and michael_feeder_runs all return PGRST205 "Could not find the table in the schema". database/migrations/20260906_michael_tables.sql is child B and is chairman-gated, NOT applied. Two consequences. (a) The repo client factory THROWS on this, it does not return an error: lib/supabase-client-schema-drift.cjs:33 builds and throws a schema-drift Error. A consent script that calls storeTokens after the OAuth callback would CRASH holding a live refresh token it never persisted, burning a consent round-trip that costs the chairman a browser grant. (b) The fix already exists in-repo and must be reused, not re-invented: lib/michael/db.mjs exports isMissingRelation (handles 42P01, PGRST205 and the "schema drift detected" message) plus readRows/writeRows which never throw and return tables_absent / refusal TABLES_ABSENT. CONDITION: google-consent.mjs must pre-flight michael_credentials and refuse with TABLES_ABSENT BEFORE generating the auth URL or opening the browser. This is the identical ordering child B already shipped and tested in scripts/michael/gmail-act.mjs (comment "pre-flight the recording table BEFORE the Gmail call") and act.test.js case "SEC-L1: absent tables refuse BEFORE the Gmail call".' },
    { id: 'condition-gmail-client-mjs-must-not-throw-at-import-time', severity: 'critical', note: 'READ AT THE CALL SITE, scripts/michael/gmail-act.mjs:33-42. defaultLoadClient() returns null ONLY for e.code === "ERR_MODULE_NOT_FOUND" or a message matching /Cannot find module|Failed to load/. ANY OTHER import-time throw is RE-THROWN, and runGmailAct does not wrap the loadClient() call in try/catch despite its "Never throws" contract -- it would escape to main() and exit 1 instead of the designed exit-2 refusal. So if lib/michael/gmail-client.mjs resolves MICHAEL_ENCRYPTION_KEY or GOOGLE_CLIENT_ID at module top level, then on a host with the key missing the verb dies with an uncaught error rather than a legible refusal. CONDITION: gmail-client.mjs performs ZERO env or credential work at import time; every key and client resolution is lazy, inside modifyThread. Contract to satisfy, taken from the shipped green tests (scripts/michael/act.test.js:54-99): a NAMED export modifyThread({ threadId, addLabelIds, removeLabelIds }) returning { ok, modified }; the label arrays are built by planModify (archive => removeLabelIds ["INBOX"], unarchive => addLabelIds ["INBOX"]); returning { ok:false, error } is handled and THROWING is handled as GMAIL_MODIFY_FAILED. The lazy specifier is relative to the importing module, so the file must land at exactly lib/michael/gmail-client.mjs.' },
    { id: 'condition-requireauth-on-a-read-only-route-is-covered-by-no-existing-lint', severity: 'critical', note: 'THE AUDIT IS BLIND HERE AND THAT IS THE POINT. lib/audit-mounts.js:32 sets MUTATING_METHODS = post, put, patch, delete, all -- a GET-only router mounted with optionalAuth instead of requireAuth is NOT a finding for that audit, and its own header states it OVER-reports and cannot UNDER-report only for the mutating class. tests/unit/audit-mounts.test.js therefore cannot catch a mis-guarded /api/michael. Placement measured in server/index.js: the requireAuth block runs 247-270 and app.use("/api", optionalAuth, dashboardRoutes) is at 272. CONDITION: mount /api/michael with requireAuth INSIDE the 247-270 block (before the /api optionalAuth line, matching the /api/github precedent the audit header calls out), and ship a dedicated test asserting an unauthenticated GET is rejected. Two content conditions on the route: it returns status only (identifier, scopes, expires_at, last_refreshed_at, last_error, whether key_fingerprint is present) and NEVER encrypted_blob, encryption_metadata or any decrypted material; and it must not decrypt at all, because the API server is not necessarily the chairman host venue.' },
    { id: 'condition-key-fingerprint-semantics-and-a-mismatch-refusal', severity: 'warning', note: 'database/migrations/20260906_michael_tables.sql:296 declares key_fingerprint TEXT NULL with the comment "makes a wrong-key decrypt diagnosable (child C resolves the key source)", and tests/unit/migrations/michael-tables-migration-shape.test.js:107 already pins that column, so the shape is fixed and no migration is needed in this child -- confirmed, child C ships zero DDL. The measured wrong-key failure is a bare GCM message with no diagnosis, which is exactly what the column is for. CONDITIONS: fingerprint = first 16 hex of sha256(RAW KEY BYTES) and never any part of the key itself; stamp it on every write; and on read, compare the current key fingerprint to the stored one and refuse with a NAMED refusal such as KEY_FINGERPRINT_MISMATCH BEFORE attempting decrypt, so the operator gets "wrong key" rather than "unable to authenticate data". Note the encryption_metadata appId is NOT a domain separator -- oauth-manager.js:38-44 already records that decrypt() ignores its metadata argument entirely -- so the fingerprint is the only key-identity signal on the row.' },
    { id: 'no-duplicate-implementation-and-no-name-conflict', severity: 'info', note: 'GATE 1 duplicate check, measured with git grep on the worktree at 9126e8903f2. ABSENT (safe to create): lib/integrations/google/ (directory does not exist), lib/michael/gmail-client.mjs, scripts/michael/google-consent.mjs, server/routes/michael.js. PRESENT (reuse, do not rebuild): lib/integrations/youtube/oauth-manager.js (the generalization source -- OAuth2Client construction, the localhost:3456 http callback catcher, the 5-minute timeout, the browser-open shim, the encrypt-before-store discipline and its fail-soft getStoredTokens contract are all directly liftable); lib/security/encryption.cjs (AES-256-GCM, PBKDF2 100k, per-blob random salt); lib/michael/db.mjs (isMissingRelation, readRows, writeRows, refusal, emit, parseArgs, canonicalJson, sha256Hex); server/middleware/auth.js requireAuth. Dependencies already present in package.json: google-auth-library ^10.5.0 and googleapis ^171.4.0 -- no new dependency is needed for either the OAuth leg or the Gmail leg.' },
    { id: 'the-two-google-modules-share-one-client-id-and-one-redirect-port', severity: 'warning', note: 'oauth-manager.js:29-31 fixes REDIRECT_PORT 3456 and reads the same GOOGLE_CLIENT_ID/GOOGLE_CLIENT_SECRET the spec assigns to the chairman grant, and spec section 4 puts the new consent flow on localhost:3456 too. Consequences to state in the PRD rather than discover: the two consent flows can never run concurrently (port collision on the same host), and the two grants must stay in SEPARATE storage -- the youtube tokens live in eva_sync_state source_identifier "youtube_oauth" and the chairman grant lives in michael_credentials identifier "google_chairman_oauth". chairman-oauth.js must never read or write the eva_sync_state row; scripts/eva-idea-sync-cron-assert.mjs already excludes that row via the exported SYNC_STATE_IDENTIFIER constant. Follow the same convention and export the identifier string rather than repeating the literal.' },
    { id: 'server-routes-michael-js-is-also-child-e-territory-c-creates-it-first', severity: 'info', note: 'docs/michael/02-SPEC.md:129 assigns server/routes/michael.js to child E (GET /api/michael/brief/latest and /:date). This child needs the same file for the credential-status route and for the requireAuth mount. Not a conflict if stated: child C CREATES server/routes/michael.js with the status route plus the single mount line, and child E EXTENDS it. Left unstated, child E lands a second mount or overwrites the guard. Recommend the PRD say so explicitly and treat the mount line as child C deliverable of record.' },
    { id: 'gate-1-inputs-zero-backlog-rows-matches-sibling-precedent-advisory-only', severity: 'info', note: 'MEASURED: strategic_directives_v2 row id 591400cf-7b88-4974-832a-6043e4f59152 (the caller-supplied 1315f7f7-3b4e-44f4-97f9-f174be21789b is the uuid_id column, not id -- both resolve to this row), sd_key SD-LEO-ORCH-MICHAEL-ROLE-FORMALIZATION-002-C, status draft, phase LEAD, priority medium, target_application EHG_Engineer, parent 47695217-d641-486a-959e-7acd0f07737a, needs_coordinator_review false and no not_before fence (siblings D through J all still carry hold true with not_before 2026-12-31, so this child is the one unfenced item). No PRD exists yet, as expected at LEAD. sd_backlog_map returns 0 rows for both the uuid and the sd_key. The standing GATE 1 rule wants at least one backlog item, but ALL TEN children of this orchestrator have 0, including -A and -B which are status completed with 16 and 15 sub-agent rows -- so the requirement is satisfied through the parent orchestrator decomposition, not per child. Recording as advisory, NOT as a blocker, because blocking here would contradict the established precedent of the two completed siblings.' },
    { id: 'qa-smoke-the-consumer-suite-runs-and-is-green', severity: 'info', note: 'RAN from the worktree: npx vitest run --project unit scripts/michael/act.test.js -> 1 file passed, 14 tests passed, 2.14s, vitest 4.1.4. Test infrastructure executes in this worktree and the seam child C must satisfy is already covered by live assertions, so a regression in the modifyThread contract is detectable immediately. This suite is the acceptance surface for the gmail-client leg and must stay green with the real module in place, including the A14 absent-seam case, which must keep passing via loadClient injection even after the real module lands.' },
    { id: 'doc-drift-spec-line-citation-for-the-requireauth-block-is-stale', severity: 'info', note: 'docs/michael/02-SPEC.md:66 and docs/michael/03-CHALLENGE.md:28 both cite server/index.js:248-254 for the requireAuth precedent. On the evaluated commit the requireAuth mounts occupy 247-270 and the /api optionalAuth mount is at 272. Cosmetic, and no action is required beyond not treating the cited range as the insertion point.' }
  ],
  metadata: {
    gate: 'GATE_1_LEAD_PRE_APPROVAL',
    phase_intent: 'LEAD pre-approval duplicate and infrastructure validation for the Google chairman OAuth child',
    scope_of_record: 'docs/michael/02-SPEC.md v0.3 section 4 plus the SD description',
    conditions: 5,
    duplicates_found: 0,
    ddl_in_child: 0,
    reads_only: true,
    sd_row_id: '591400cf-7b88-4974-832a-6043e4f59152',
    sd_uuid_id: '1315f7f7-3b4e-44f4-97f9-f174be21789b',
    backlog_items: 0,
    prds_found: 0,
    qa_smoke: { command: 'npx vitest run --project unit scripts/michael/act.test.js', files_passed: 1, tests_passed: 14, tests_failed: 0 },
    mechanism_verifications: [
      { verified: 'confirmed', claim: 'encryption.cjs silently generates a new master key when .leo-keys is absent', how: 'isolated temp keyPath: encrypt() created the file (key ea4b2e93afd6); after deleting it, decrypt() of the same blob regenerated a DIFFERENT key (67ebad910ed1) and failed with unable to authenticate data' },
      { verified: 'confirmed', claim: 'the worktree has no .leo-keys while the root checkout does, and both are gitignored', how: 'root .leo-keys 169 bytes Aug 26; worktree .leo-keys ENOENT; .gitignore lines 49-50' },
      { verified: 'confirmed', claim: 'CredentialEncryption can be reused without duplicating crypto', how: 'Object.getPrototypeOf(singleton).constructor is CredentialEncryption; instance with getMasterKey overridden round-tripped encrypt and decrypt with the override called twice' },
      { verified: 'confirmed', claim: 'a wrong master key is refused rather than silently mis-decrypted', how: 'second instance with a different 32-byte key threw Decryption failed: Unsupported state or unable to authenticate data' },
      { verified: 'confirmed', claim: 'exporting the class keeps the default singleton and enables a named ESM import', how: 'probe copy of encryption.cjs with module.exports.CredentialEncryption appended: ESM namespace keys were CredentialEncryption, default, module.exports and the named binding was a function' },
      { verified: 'confirmed', claim: 'michael_credentials does not exist in the live database', how: 'service-role select on michael_credentials, michael_gmail_triage_items and michael_feeder_runs: all PGRST205 Could not find the table in the schema, raised as a THROWN schema-drift error by lib/supabase-client-schema-drift.cjs:33' },
      { verified: 'confirmed', claim: 'the migration already declares michael_credentials with key_fingerprint, so this child ships no DDL', how: 'database/migrations/20260906_michael_tables.sql:290-312 and tests/unit/migrations/michael-tables-migration-shape.test.js:107' },
      { verified: 'confirmed', claim: 'gmail-act.mjs re-throws any import failure that is not module-not-found', how: 'scripts/michael/gmail-act.mjs:33-42 narrows the catch to ERR_MODULE_NOT_FOUND, Cannot find module and Failed to load, and rethrows otherwise; runGmailAct line 47 does not wrap loadClient()' },
      { verified: 'confirmed', claim: 'the modifyThread contract is already pinned by green tests', how: 'scripts/michael/act.test.js:54-99 exercises ok true with modified 1, ok false with an error, and a throwing modifyThread; 14 of 14 passing' },
      { verified: 'confirmed', claim: 'the mount audit cannot catch a mis-guarded read-only /api/michael', how: 'lib/audit-mounts.js:32 MUTATING_METHODS excludes get; the requireAuth block at server/index.js:247-270 precedes the /api optionalAuth mount at 272' },
      { verified: 'confirmed', claim: 'no name conflicts and no duplicate implementation', how: 'git grep at 9126e8903f2: lib/integrations/google absent, lib/michael/gmail-client.mjs absent, scripts/michael/google-consent.mjs absent, server/routes/michael.js absent' },
      { verified: 'confirmed', claim: 'google-auth-library and googleapis are already dependencies', how: 'package.json dependencies google-auth-library ^10.5.0 and googleapis ^171.4.0' },
      { verified: 'refuted', claim: 'GATE 1 should block this SD for having zero sd_backlog_map rows', how: 'all ten children of parent 47695217 have 0 backlog rows, including -A and -B which are status completed; the per-child rule does not apply to this orchestrator decomposition' }
    ]
  },
  execution_time_ms: 1020000
};

const res = await resolveSubAgentRepo({ sdId: SD_ID, subAgentCode: 'VALIDATION', targetApplication: 'EHG_Engineer' });
applySubAgentRepoVerdict(payload, res);
const s = await storeSubAgentResults('VALIDATION', SD_ID, { name: 'Principal Systems Analyst' }, payload, { phase: 'LEAD' });
console.log('STORED VALIDATION/LEAD id=' + (s && s.id));
