# Venture Vision v2.0 - 25-Stage Lifecycle Configuration
# SD: SD-VISION-TRANSITION-001D
# Created: 2025-12-06
# Purpose: Definitive configuration for the streamlined 25-stage venture lifecycle

version: "2.0"
name: "Venture Vision v2.0"
description: "Streamlined 25-stage venture lifecycle for Solo AI Entrepreneur workflows"

phases:
  - id: 1
    name: "THE TRUTH"
    description: "Validation and market reality assessment"
    stages: [1, 2, 3, 4, 5]
  - id: 2
    name: "THE ENGINE"
    description: "Business model and strategy foundation"
    stages: [6, 7, 8, 9]
  - id: 3
    name: "THE IDENTITY"
    description: "Brand, positioning, and go-to-market"
    stages: [10, 11, 12]
  - id: 4
    name: "THE BLUEPRINT"
    description: "Technical architecture and specification"
    stages: [13, 14, 15, 16]
  - id: 5
    name: "THE BUILD LOOP"
    description: "Implementation and development cycle"
    stages: [17, 18, 19, 20]
  - id: 6
    name: "LAUNCH & LEARN"
    description: "Deployment, analytics, and optimization"
    stages: [21, 22, 23, 24, 25]

stages:
  # ============================================================================
  # PHASE 1: THE TRUTH (Stages 1-5)
  # ============================================================================
  - id: 1
    title: "Draft Idea & Chairman Review"
    description: "Capture and validate initial venture ideas with AI assistance and Chairman feedback."
    phase_number: 1
    phase_name: "THE TRUTH"
    work_type: artifact_only
    sd_required: false
    advisory_enabled: false
    depends_on: []
    inputs:
      - Voice recording
      - Text input
      - Chairman feedback
    outputs:
      - Structured idea document
      - Initial validation
      - Risk assessment
    artifacts:
      - idea_brief
    metrics:
      - Idea quality score
      - Validation completeness
    gates:
      entry: []
      exit:
        - Title validated (3-120 chars)
        - Description validated (20-2000 chars)
        - Category assigned

  - id: 2
    title: "AI Multi-Model Critique"
    description: "Multi-agent AI system reviews and critiques the idea from multiple perspectives."
    phase_number: 1
    phase_name: "THE TRUTH"
    work_type: automated_check
    sd_required: false
    advisory_enabled: false
    depends_on: [1]
    inputs:
      - Structured idea
      - Historical data
      - Market signals
    outputs:
      - AI critique report
      - Contrarian analysis
      - Risk assessment
    artifacts:
      - critique_report
    metrics:
      - Review thoroughness
      - Risk identification rate
    gates:
      entry:
        - Idea document complete
      exit:
        - Multi-model pass complete
        - Contrarian review done
        - Top-5 risks identified

  - id: 3
    title: "Market Validation & RAT"
    description: "Validate problem-solution fit, user willingness to pay, and technical feasibility."
    phase_number: 1
    phase_name: "THE TRUTH"
    work_type: decision_gate
    sd_required: false
    advisory_enabled: true  # ADVISORY CHECKPOINT
    depends_on: [2]
    inputs:
      - AI review report
      - Market research
      - User interviews
    outputs:
      - Validation report
      - User feedback
      - Feasibility assessment
    artifacts:
      - validation_report
    metrics:
      - Validation score (1-10)
      - WTP confidence
    gates:
      entry:
        - AI critique complete
      exit:
        - Validation score >= 6
        - Chairman decision: advance/revise/reject
    decision_options:
      - advance
      - revise
      - reject
    tier_cap: 3  # Tier 0 ventures capped at this stage

  - id: 4
    title: "Competitive Intelligence"
    description: "Deep analysis of competitive landscape, market gaps, and positioning opportunities."
    phase_number: 1
    phase_name: "THE TRUTH"
    work_type: artifact_only
    sd_required: false
    advisory_enabled: false
    depends_on: [3]
    inputs:
      - Market validation results
      - Competitor data
      - Industry reports
    outputs:
      - Competitive analysis
      - Gap identification
      - Positioning strategy
    artifacts:
      - competitive_analysis
    metrics:
      - Competitors identified
      - Gap opportunities scored

  - id: 5
    title: "Profitability Forecasting"
    description: "Financial modeling, unit economics validation, and ROI projections."
    phase_number: 1
    phase_name: "THE TRUTH"
    work_type: decision_gate
    sd_required: false
    advisory_enabled: true  # ADVISORY CHECKPOINT
    depends_on: [4]
    inputs:
      - Competitive analysis
      - Pricing assumptions
      - Cost structure
    outputs:
      - Financial model
      - Unit economics
      - ROI projections
    artifacts:
      - financial_model
    metrics:
      - Gross margin target (40%+)
      - Breakeven months (<18)
      - CAC:LTV ratio (1:3+)
    gates:
      entry:
        - Competitive analysis complete
      exit:
        - Financial model complete
        - Unit economics viable

  # ============================================================================
  # PHASE 2: THE ENGINE (Stages 6-9)
  # ============================================================================
  - id: 6
    title: "Risk Evaluation Matrix"
    description: "Comprehensive risk identification, probability assessment, and mitigation planning."
    phase_number: 2
    phase_name: "THE ENGINE"
    work_type: artifact_only
    sd_required: false
    advisory_enabled: false
    depends_on: [5]
    inputs:
      - Financial model
      - Market analysis
      - Technical assessment
    outputs:
      - Risk matrix
      - Mitigation strategies
      - Contingency plans
    artifacts:
      - risk_matrix
    metrics:
      - Risks identified
      - Mitigation coverage

  - id: 7
    title: "Pricing Strategy"
    description: "Pricing model development, tier structure, and value-based pricing analysis."
    phase_number: 2
    phase_name: "THE ENGINE"
    work_type: artifact_only
    sd_required: false
    advisory_enabled: false
    depends_on: [6]
    inputs:
      - Financial model
      - Competitor pricing
      - Value analysis
    outputs:
      - Pricing model
      - Tier structure
      - Discount policies
    artifacts:
      - pricing_model
    metrics:
      - Price sensitivity analysis
      - Margin optimization

  - id: 8
    title: "Business Model Canvas"
    description: "Complete business model documentation using BMC framework."
    phase_number: 2
    phase_name: "THE ENGINE"
    work_type: artifact_only
    sd_required: false
    advisory_enabled: false
    depends_on: [7]
    inputs:
      - All previous analyses
      - Pricing strategy
      - Risk assessment
    outputs:
      - Business Model Canvas
      - Value propositions
      - Revenue streams
    artifacts:
      - business_model_canvas
    metrics:
      - BMC completeness
      - Strategic alignment

  - id: 9
    title: "Exit-Oriented Design"
    description: "Strategic exit planning, valuation targets, and acquisition-friendly architecture."
    phase_number: 2
    phase_name: "THE ENGINE"
    work_type: artifact_only
    sd_required: false
    advisory_enabled: false
    depends_on: [8]
    inputs:
      - Business model
      - Market multiples
      - Comparable exits
    outputs:
      - Exit strategy
      - Valuation targets
      - Timeline planning
    artifacts:
      - exit_strategy
    metrics:
      - Exit scenarios defined
      - Valuation methodology

  # ============================================================================
  # PHASE 3: THE IDENTITY (Stages 10-12)
  # ============================================================================
  - id: 10
    title: "Strategic Naming"
    description: "Brand naming, identity development, and guidelines creation."
    phase_number: 3
    phase_name: "THE IDENTITY"
    work_type: sd_required
    sd_required: true
    sd_suffix: "BRAND"
    advisory_enabled: false
    depends_on: [9]
    inputs:
      - Business model
      - Target audience
      - Competitive positioning
    outputs:
      - Brand name
      - Brand guidelines
      - Visual identity specs
    artifacts:
      - brand_guidelines
    metrics:
      - Name availability
      - Brand strength score

  - id: 11
    title: "Go-to-Market Strategy"
    description: "Marketing strategy, channel selection, and launch planning."
    phase_number: 3
    phase_name: "THE IDENTITY"
    work_type: artifact_only
    sd_required: false
    advisory_enabled: false
    depends_on: [10]
    inputs:
      - Brand identity
      - Target segments
      - Competitive position
    outputs:
      - GTM plan
      - Marketing manifest
      - Channel strategy
    artifacts:
      - gtm_plan
      - marketing_manifest
    metrics:
      - Channel coverage
      - Launch readiness

  - id: 12
    title: "Sales & Success Logic"
    description: "Sales process design, customer success workflows, and support model."
    phase_number: 3
    phase_name: "THE IDENTITY"
    work_type: artifact_only
    sd_required: false
    advisory_enabled: false
    depends_on: [11]
    inputs:
      - GTM strategy
      - Customer segments
      - Product capabilities
    outputs:
      - Sales playbook
      - Success workflows
      - Support model
    artifacts:
      - sales_playbook
    metrics:
      - Process completeness
      - Handoff clarity

  # ============================================================================
  # PHASE 4: THE BLUEPRINT (Stages 13-16) - "Kochel Firewall"
  # ============================================================================
  - id: 13
    title: "Tech Stack Interrogation"
    description: "AI-driven challenge of technology choices, architecture decisions, and trade-offs."
    phase_number: 4
    phase_name: "THE BLUEPRINT"
    work_type: decision_gate
    sd_required: false
    advisory_enabled: false
    depends_on: [12]
    inputs:
      - Business requirements
      - Scale projections
      - Team capabilities
    outputs:
      - Tech stack decision
      - Architecture rationale
      - Trade-off analysis
    artifacts:
      - tech_stack_decision
    metrics:
      - Decision confidence
      - Future-proofing score

  - id: 14
    title: "Data Model & Architecture"
    description: "Entity relationship design, schema architecture, and data flow planning."
    phase_number: 4
    phase_name: "THE BLUEPRINT"
    work_type: sd_required
    sd_required: true
    sd_suffix: "DATAMODEL"
    advisory_enabled: false
    depends_on: [13]
    inputs:
      - Tech stack decision
      - Business entities
      - Integration requirements
    outputs:
      - Data model
      - ERD diagrams
      - Schema specifications
    artifacts:
      - data_model
      - erd_diagram
    metrics:
      - Entity coverage
      - Relationship clarity

  - id: 15
    title: "Epic & User Story Breakdown"
    description: "Feature decomposition into epics and user stories with acceptance criteria."
    phase_number: 4
    phase_name: "THE BLUEPRINT"
    work_type: sd_required
    sd_required: true
    sd_suffix: "STORIES"
    advisory_enabled: false
    depends_on: [14]
    inputs:
      - Data model
      - Business requirements
      - User journeys
    outputs:
      - Epic definitions
      - User story pack
      - Acceptance criteria
    artifacts:
      - user_story_pack
    metrics:
      - Story completeness
      - INVEST compliance

  - id: 16
    title: "Spec-Driven Schema Generation"
    description: "TypeScript interfaces, SQL schemas, and API contract generation from specifications."
    phase_number: 4
    phase_name: "THE BLUEPRINT"
    work_type: decision_gate
    sd_required: true
    sd_suffix: "SCHEMA"
    advisory_enabled: true  # ADVISORY CHECKPOINT - Schema Firewall
    depends_on: [15]
    inputs:
      - User stories
      - Data model
      - API requirements
    outputs:
      - TypeScript interfaces
      - SQL schemas
      - API contracts
    artifacts:
      - api_contract
      - schema_spec
    metrics:
      - Schema completeness
      - Type coverage
    schema_checklist:
      - All entities named
      - All relationships explicit
      - All fields typed
      - All constraints stated
      - API contracts generated
      - TypeScript interfaces generated

  # ============================================================================
  # PHASE 5: THE BUILD LOOP (Stages 17-20)
  # ============================================================================
  - id: 17
    title: "Environment & Agent Config"
    description: "Development environment setup, AI agent configuration, and CI/CD pipeline."
    phase_number: 5
    phase_name: "THE BUILD LOOP"
    work_type: sd_required
    sd_required: true
    sd_suffix: "ENVCONFIG"
    advisory_enabled: false
    depends_on: [16]
    inputs:
      - Tech stack decision
      - Schema specifications
      - Team requirements
    outputs:
      - Environment setup
      - System prompts
      - CI/CD pipeline
    artifacts:
      - system_prompt
      - cicd_config
    metrics:
      - Environment readiness
      - Agent effectiveness

  - id: 18
    title: "MVP Development Loop"
    description: "Core feature implementation following story-driven development."
    phase_number: 5
    phase_name: "THE BUILD LOOP"
    work_type: sd_required
    sd_required: true
    sd_suffix: "MVP"
    advisory_enabled: false
    depends_on: [17]
    inputs:
      - User stories
      - Schema specifications
      - Environment config
    outputs:
      - Working code
      - Feature implementations
      - Technical debt log
    artifacts: []
    metrics:
      - Story completion rate
      - Code quality score

  - id: 19
    title: "Integration & API Layer"
    description: "System integration, API implementation, and third-party connections."
    phase_number: 5
    phase_name: "THE BUILD LOOP"
    work_type: sd_required
    sd_required: true
    sd_suffix: "INTEGRATION"
    advisory_enabled: false
    depends_on: [18]
    inputs:
      - MVP implementation
      - API contracts
      - External services
    outputs:
      - Integrated system
      - API endpoints
      - Integration tests
    artifacts: []
    metrics:
      - API coverage
      - Integration success rate

  - id: 20
    title: "Security & Performance"
    description: "Security hardening, performance optimization, and accessibility compliance."
    phase_number: 5
    phase_name: "THE BUILD LOOP"
    work_type: sd_required
    sd_required: true
    sd_suffix: "SECURITY"
    advisory_enabled: false
    depends_on: [19]
    inputs:
      - Integrated system
      - Security requirements
      - Performance targets
    outputs:
      - Hardened system
      - Performance metrics
      - Security audit
    artifacts:
      - security_audit
    metrics:
      - Security scan clean
      - Performance targets met
      - WCAG 2.1 AA compliant

  # ============================================================================
  # PHASE 6: LAUNCH & LEARN (Stages 21-25)
  # ============================================================================
  - id: 21
    title: "QA & UAT"
    description: "Quality assurance testing, user acceptance testing, and bug resolution."
    phase_number: 6
    phase_name: "LAUNCH & LEARN"
    work_type: sd_required
    sd_required: true
    sd_suffix: "QA"
    advisory_enabled: false
    depends_on: [20]
    inputs:
      - Hardened system
      - Test scenarios
      - User test cases
    outputs:
      - Test reports
      - Bug fixes
      - UAT signoff
    artifacts:
      - test_plan
      - uat_report
    metrics:
      - Test coverage >= 80%
      - Bug resolution rate
      - UAT pass rate

  - id: 22
    title: "Deployment & Infrastructure"
    description: "Production deployment, infrastructure provisioning, and monitoring setup."
    phase_number: 6
    phase_name: "LAUNCH & LEARN"
    work_type: sd_required
    sd_required: true
    sd_suffix: "DEPLOY"
    advisory_enabled: false
    depends_on: [21]
    inputs:
      - QA-passed system
      - Infrastructure specs
      - Deployment plan
    outputs:
      - Deployed system
      - Monitoring setup
      - Runbooks
    artifacts:
      - deployment_runbook
    metrics:
      - Deployment success
      - Monitoring coverage

  - id: 23
    title: "Production Launch"
    description: "Go-live execution, launch checklist completion, and initial user onboarding."
    phase_number: 6
    phase_name: "LAUNCH & LEARN"
    work_type: decision_gate
    sd_required: false
    advisory_enabled: false
    depends_on: [22]
    inputs:
      - Deployed system
      - Launch checklist
      - Marketing assets
    outputs:
      - Live product
      - Launch metrics
      - User feedback
    artifacts:
      - launch_checklist
    metrics:
      - Launch checklist complete
      - Initial users onboarded

  - id: 24
    title: "Analytics & Feedback"
    description: "Analytics implementation, feedback collection, and metric tracking."
    phase_number: 6
    phase_name: "LAUNCH & LEARN"
    work_type: artifact_only
    sd_required: false
    advisory_enabled: false
    depends_on: [23]
    inputs:
      - Live product
      - User activity
      - Market feedback
    outputs:
      - Analytics dashboard
      - Feedback reports
      - KPI tracking
    artifacts:
      - analytics_dashboard
    metrics:
      - DAU/MAU tracking
      - NPS score
      - Feature adoption

  - id: 25
    title: "Optimization & Scale"
    description: "Continuous improvement, scaling preparation, and growth optimization."
    phase_number: 6
    phase_name: "LAUNCH & LEARN"
    work_type: sd_required
    sd_required: true
    sd_suffix: "OPTIMIZE"
    advisory_enabled: false
    depends_on: [24]
    inputs:
      - Analytics data
      - User feedback
      - Performance metrics
    outputs:
      - Optimization roadmap
      - Scaling plan
      - Growth experiments
    artifacts:
      - optimization_roadmap
    metrics:
      - Performance improvements
      - Scale readiness

# Advisory Checkpoint Configuration
advisory_checkpoints:
  - stage: 3
    name: "Validation Checkpoint"
    description: "Kill/Revise/Proceed decision based on market validation score"
    trigger: "validation_score < 6"
  - stage: 5
    name: "Profitability Gate"
    description: "Financial viability assessment against archetype benchmarks"
    trigger: "gross_margin < threshold OR breakeven_months > threshold"
  - stage: 16
    name: "Schema Firewall"
    description: "Pre-implementation schema completeness verification"
    trigger: "schema_checklist incomplete"
